### ISSUE TITLE
[Question] Cannot find module `react-tooltip/dist/react-tooltip.css`

### ISSUE THREAD

**Issue by warendmir** [ReactTooltip/react-tooltip#1004]
**Describe the bug**
When running tests via Jest. Get error `Cannot find module 'react-tooltip/dist/react-tooltip.css'`
As i can see, file was removed in this version.
**Version of Package**
v5.10.5

**Screenshots**
![image](https://user-images.githubusercontent.com/45854841/230649150-a853f700-3422-4463-b884-21b8dbb1a474.png)

**Comment by danielbarion** [comment]
Hi, thanks for reporting, I'll take a look

**Comment by warendmir** [comment]
Found. Sorry it`s not a bug.
I`m just forgot about excluding node_modules from jest config in packaje.json

The answer is to add ignore pattern to transformIgnorePatterns. Somthing like this:
`"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(react-tooltip|react-dnd|...)/)"
    ],
  }`

**Comment by warendmir** [comment]
:(...not it`s not help. Im just pass tests that not include this import.

**Comment by gabrieljablonski** [comment]
Until we can do a release with a fix for this, you can manually create the missing file like this:

```
cp node_module/react-tooltip/dist/react-tooltip.min.css node_module/react-tooltip/dist/react-tooltip.css
```

**Comment by danielbarion** [comment]
Hi, can you test this beta release and let us know, please?

Beta version:
```
yarn add react-tooltip@5.10.6-beta.1005.1
```
or
```
npm i react-tooltip@5.10.6-beta.1005.1
```

**Comment by warendmir** [comment]
![image](https://user-images.githubusercontent.com/45854841/230666354-9a6adca8-59ba-4d0a-8d83-f4d25fc56223.png)
new message

**Comment by warendmir** [comment]
`"moduleNameMapper": {`
      `"^react-tooltip/dist/react-tooltip\\.css$": "<rootDir>/node_modules/react-tooltip/dist/react-tooltip.min.css"`
   ` },`
   
   this jest  config helps but its not fair

**Comment by danielbarion** [comment]
@warendmir can you confirm if you have other CSS files working in Jest?

Also, can you check this line in our Jest configuration and try it in your, please?
https://github.com/ReactTooltip/react-tooltip/blob/master/jest.config.ts#L194

**Comment by warendmir** [comment]
@danielbarion `"^.+\\.css$": "jest-transform-css"` not helps.
about confirming that other CSS works: I copy your react-tooltip.min.css to my files as react-tooltip.css and replace import that cause error in tests. All tests passed. And without  `"^.+\\.css$": "jest-transform-css"`

**Comment by danielbarion** [comment]
@warendmir can you please confirm if this PR closes this issue? https://github.com/ReactTooltip/react-tooltip/pull/1005
Thanks!

**Comment by gabrieljablonski** [comment]
Please test the official release `react-tooltip@5.11.1` and let us know.
