### ISSUE TITLE
[BUG] 66.68~83.35ms delay when delayShow and delayHide are set to 0

### ISSUE THREAD

**Issue by knubie** [ReactTooltip/react-tooltip#1008]
**Describe the bug**
When the `delayShow` and `delayHide` props are set to `0`, there is still a 66.68~83.35ms delay. At least 50ms of delay can be attributed to the debounce function wraping the `handleShowTooltip` and `handleHideTooltip` methods here: 

https://github.com/ReactTooltip/react-tooltip/blob/01c4a6fa1729b860639077d22dba8c47e1db808f/src/components/Tooltip/Tooltip.tsx#L168-L171

Removing the call to `debounce` drops the delay to 16.67~33.34ms. The problem is that debounce is calling the functions on the trailing edge of the delay as opposed to the leading edge. The function also accepts an `immediate` argument, but with the the way that `debounce` is implemented here, passing `true` for `immediate` just disables the function call entirely.

https://github.com/ReactTooltip/react-tooltip/blob/01c4a6fa1729b860639077d22dba8c47e1db808f/src/utils/debounce.ts#L14-L16

I recommend taking a look at underscore.js for how to implement `debounce` with the `immediate` param.
https://underscorejs.org/docs/modules/debounce.html

**Version of Package**
v5.10.5

**To Reproduce**
1. Create an anchor that has a hover state (used to compare with tooltip delay).
2. Add a tooltip with `0` for `delayShow` and `delayHide`.
3. Observe delay on both show and hide.

**Expected behavior**
The hiding and showing of the tooltip should track with the hover state of the anchor.

**Screenshots**
With `debounce`:

<img src="https://user-images.githubusercontent.com/431251/230899937-e8f56f25-6618-41b9-b344-1ea655bf4a9b.mp4">
<img src="https://user-images.githubusercontent.com/431251/230899521-55b16649-d7be-458e-b303-5cbff9348f59.mp4">

---

Without `debounce`:

<img src="https://user-images.githubusercontent.com/431251/230899498-2c4f2a6b-2e9c-4762-943a-3976f8bc5a1d.mp4">
<img src="https://user-images.githubusercontent.com/431251/230899547-5a4b0941-8f5d-42e7-8e3f-48e6c12a6e72.mp4">

**Comment by gabrieljablonski** [comment]
Try out the beta version for #1009 `react-tooltip@5.10.6-beta.1009.1`.

> The hiding and showing of the tooltip should track with the hover state of the anchor.

Although it might be theorically possible (maybe doing some clever stuff with `useLayoutEffect()`? not sure), I don't believe it is worth the trouble. I tried recording at 200 fps just to make sure, and got around 3/4 frames, so consistent with around 1 frame at 60 fps.

**Comment by knubie** [comment]
Awesome! Much better in both my test repo and actual project. Thanks for the quick turn around @gabrieljablonski. 

The additional 1-2 frame delay was not noticeable to my naked eye until I recorded it and went frame by frame, so I don't know if it's worth looking into or not unless you are looking for a challenge. 🙂

**Comment by gabrieljablonski** [comment]
Good to know, we'll leave this open until we do an official release with the fix. Thanks for reporting.

> I don't know if it's worth looking into or not unless you are looking for a challenge.

Not right now haha, maybe in the future. 

If you ever run into any UI libraries that are able to do stuff like this with consistent 0-frame delay, let me know so I can have a look, but I doubt it's an easy thing to achieve.

**Comment by gabrieljablonski** [comment]
Fixed on official release `react-tooltip@5.10.6`.

**Comment by knubie** [comment]
So I might have spoken too soon. It seems like that extra 1 frame delay is actually causing some issues. Take a look at this recording:

https://user-images.githubusercontent.com/431251/230912027-9c153db4-1789-4dd7-b1c6-25e59660debc.mp4

What's happening is that the position of the tooltip is getting updated immediately, but the hiding of the tooltip is delayed by a frame.

I would like to dig into this more, but I'm having trouble working on the package locally. I tried using `yarn link` to link to a local copy of the package, but I can't seem to get any of my changes to show up in the `create-react-app` app.

I'd like to try and figure out why the position is getting updated before the visibility.

**Comment by danielbarion** [comment]
@knubie you can try the package locally with this doc: https://github.com/ReactTooltip/react-tooltip/blob/master/CONTRIBUTION.md

Also you can try `yalc`: https://github.com/wclr/yalc

Yalc simulates a local package registry, so, you just need to install Yalc globally with NPM or yarn, after this:

1. on the tooltip repository: `yalc publish`
2. on your project: `yalc add NAME_OF_THE_PACKAGE --link` (the link param will make changes into react tooltip repository be reflected to your project)
3. after **every** change on react-tooltip repository, you need to run `yalc push` to update the local package registry

PS: normally I always run `yalc publish && yalc push` just as double-check :)

**Comment by knubie** [comment]
Cool, thanks @danielbarion I will try that.

For now, here's the new issue: https://github.com/ReactTooltip/react-tooltip/issues/1010
