### ISSUE TITLE
Closing tag error in the docs

### ISSUE THREAD

**Issue by sakakibara-dev** [ReactTooltip/react-tooltip#1012]
Hello,
There are closing tag errors in code snippets on the [Getting Started](https://react-tooltip.com/docs/getting-started#using-reacttooltip-props) page.

```HTML 
<a className="my-anchor-element">◕‿‿◕</p>
<a className="my-anchor-element">◕‿‿◕</p>
<a className="my-anchor-element">◕‿‿◕</p>
```

Did there mean the following?
```HTML 
<a className="my-anchor-element">◕‿‿◕</a>
<a className="my-anchor-element">◕‿‿◕</a>
<a className="my-anchor-element">◕‿‿◕</a>
```
Can I fix it?

**Comment by gabrieljablonski** [comment]
Yeah, please submit a PR.

**Comment by sakakibara-dev** [comment]
okay, I submitted a PR.
confirm, please.
