### ISSUE TITLE
[BUG] Changing `data-tooltip-id` in component renders multiple tooltips

### ISSUE THREAD

**Issue by NicerDicerPro** [ReactTooltip/react-tooltip#1015]
**Describe the bug**
Changing the `data-tooltip-id` attribute inside a component (forcing a rerender of the component) doesnt remove the existing tooltip but only adds the new.

After the first change there are two tooltips shown. After the second change there are three tooltips shown (and so on).

**Version of Package**
v5.11.1

**To Reproduce**

1. Render a component with a dynamically generated `data-tooltip-id` attribute.
2. Change the dynamic part of the `data-tooltip-id` forcing the component to rerender.
3. The old tooltip(s) and the new tooltip show up.

Demo Code:
```
import React from 'react'

export default function LanguageFlag ({ language }: { language: string }) {
  return (
    <div data-tooltip-id={`language-tooltip-${language}`}>
      {language}
    </div>
  )
}
```
Note: The corrospondending `<ReactTooltip/>` components are rendered in a more general scope.

[StackBlitz demonstrating the issue](https://stackblitz.com/edit/react-ts-vh6yrr?file=App.tsx)

**Expected behavior**
When `data-tooltip-id` changes (which obviously gets recognized by react-tooltip) all old tooltips should be removed before adding the new one.

**Screenshots**
Initial render:
![image](https://user-images.githubusercontent.com/100697546/232689770-e64c9147-8fee-4b37-9f5e-b4f01a0c6569.png)

After changing language:
![image](https://user-images.githubusercontent.com/100697546/232689841-b0bb42f1-12e7-48a8-b1f2-6bc3ca8ccf67.png)

**Desktop:**
 - Device: MacBook Pro M1, 2020
 - OS: iOS 13.3.1
 - Browser: Chrome
 - Version 112.0.5615.49
 - Frameworks React 18.2.0, Next.JS 13.2.4, NodeJS 18.12.1

**Comment by gabrieljablonski** [comment]
Thanks for reporting, we'll take a look at this soon.

Until then, you should check [the examples for the `render` prop](https://react-tooltip.com/docs/examples/render), since having a different tooltip component for each language does not seem to me like a great way to achieve what you're trying to do.

**Comment by gabrieljablonski** [comment]
More easily, you could also achieve this without the `render` prop, using the `data-tooltip-content` attribute, though I'd still recommend using `render` if you're planning on doing more than just text on the tooltip (maybe icons or something like that). 

If it's just text, `data-tooltip-content` should do fine.

**Comment by NicerDicerPro** [comment]
It actually is a pure string.

Were using the language tooltips in multiple occasions and therefore we render one tooltip per language exactly once at the very outmost part of our layout.

So we currently have like 10 language tooltips rendered which we reference whereever we need them.

To work around the problem i added a "language-tooltip-generic" Tooltip (empty) which i now reference by `data-tooltip-id` and fill by `data-tooltip-content` which makes the error disappear for my exact case.

Still, reassigning tooltip ids in component re-renders doesnt properly work.

**Comment by gabrieljablonski** [comment]
> Still, reassigning tooltip ids in component re-renders doesnt properly work

Yes, there is indeed a bug.

Although it should indeed be working, we still wouldn't recommend updating the `data-tooltip-id` attribute, since it makes a lot more sense to update the content dynamically of a single tooltip, as I believe you have done now.

**Comment by gabrieljablonski** [comment]
I've created a simple example reproducing this issue [here](https://stackblitz.com/edit/react-ts-vh6yrr?file=App.tsx).

We'll probably fix this, but it will probably be a bit until we get to it, since I'd personally consider changing the attached tooltip dynamically to not be an intended feature.

**Comment by gabrieljablonski** [comment]
Thanks for the suggestion. We'll definitely do something like that if we decide to not fix this.

**Comment by gabrieljablonski** [comment]
After some testing, it would not be trivial to fix this. We might revisit this in the future, but as of right now changing `data-tooltip-id` after it is set is not supported.

The proper way to achieve something like this is using the methods the docs already suggest, such as `data-tooltip-content`, `data-tooltip-html`, and the `render` prop.
