### ISSUE TITLE
[BUG] When using render property and the render callback returns a falsy value an empty tooltip is displayed

### ISSUE THREAD

**Issue by yurigenin** [ReactTooltip/react-tooltip#1018]
**Describe the bug**
When using the **render** property for the Tooltip and the **render** callback returns a falsy value an empty tooltip is displayed. 

**Version of Package**
latest

**To Reproduce**
Use a **render** property and assign it a callback that returns an empty string. An empty tooltip will be displayed.

**Expected behavior**
No tooltip should be displayed when the **render** callback returns a falsy value

**Desktop (please complete the following information if possible or delete this section):**
 - OS: [MacOS]
 - Browser [all]
 - Frameworks [React 18]

**Additional context**
This happens because the result of the **render** callback is always wrapped into a div regardless of whether it returns a falsy value or not. It causes a non-empty content which makes the tooltip component to show the tooltip whose content is just an empty div.

See here: https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/TooltipController/TooltipController.tsx#L211

Instead, it should only be wrapped if the render callback returns a truthy value.

**Comment by gabrieljablonski** [comment]
Thanks for reporting! #1019 should fix this.

**Comment by gabrieljablonski** [comment]
Until #1019 is merged, you cant test with `react-tooltip@5.11.2-beta.1019.0`

**Comment by yurigenin** [comment]
Ok, I think I figured out how to make it work. In my pointer events (enter/leave) I can call forceUpdate which will force the Tooltip to retrieve the new content. The issue I still have is that data-tooltip-content or data-tooltip-html only take a string but I need to render React elements as content sometimes. Render and children support it but you cannot use it on an anchor since attributes are always string. This prevents me from using a shared Tooltip instance since I need to use its render or children properties. Any idea how to make it work?

**Comment by gabrieljablonski** [comment]
Fixed on `react-tooltip@5.11.2`.
