### ISSUE TITLE
Update property "variant" dynamically inside "render" method 

### ISSUE THREAD

**Issue by siddhutm** [ReactTooltip/react-tooltip#1021]
Hello,

I'm trying to set "variant" property dynamically based on the content.
https://react-tooltip.com/docs/examples/variant

Could you please let me know if it's feasible or any other better way to do it ?
Please find the code here -> https://codesandbox.io/s/eager-glitter-nc5nqp 

Code snippet where I'm trying to make the change is as shown below.

`

      <Tooltip
        id="package-status-tooltip"
        place="bottom"
        delayShow={300}
        render={({ content, activeAnchor }) => {
          /** Rendering dynamic content*/
          /**
           * I would like to update tooltip varient property based on the content value
           * INFO -> DARK
           * ERROR -> error
           * Success -> success
           */
          return (
            <div className="flex flex-col max-w-lg">
             {content}
            </div>
          );
        }}
      />
`

**Comment by gabrieljablonski** [comment]
Use `data-tooltip-variant`. https://codesandbox.io/s/busy-tdd-7twch0?file=/src/App.js

**Comment by siddhutm** [comment]
thank you so much @gabrieljablonski !!
