### ISSUE TITLE
[BUG] Can't import the named export 'xxx' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by masonlouchart** [ReactTooltip/react-tooltip#1022]
**Describe the bug**

```shell
webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 181:23-24
webpack-dev-server : Can't import the named export 'arrow' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 184:9-10
webpack-dev-server : Can't import the named export 'computePosition' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 36:6-7
webpack-dev-server : Can't import the named export 'createContext' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 167:56-57
webpack-dev-server : Can't import the named export 'flip' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 167:61-62
webpack-dev-server : Can't import the named export 'shift' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 76:10-11
webpack-dev-server : Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 135:11-12
webpack-dev-server : Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)

webpack-dev-server : ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 41:15-16
webpack-dev-server : Can't import the named export 'useState' from non EcmaScript module (only default export is available)


...AND SO ON...
```

**Version of Package**
v5.11.2

**To Reproduce**
- Install react-tooltip 5.11.2, import it, and try to use it
- Run your application (error raised at compile time)

**Expected behavior**
No internal error happens, the app can be rendered as usual.

**Desktop:**
 - OS: Mac OS Ventura 13.3.1 (a)
 - Browser: Chrome Version 113.0.5672.92 (Official Build) (x86_64)
 - Frameworks: React 17.0.2

**Additional information**
Already tested another version (5.10.4) and reproduced similar error.

**Comment by gabrieljablonski** [comment]
Are you able to provide a sample repo reproducing this problem?

**Comment by masonlouchart** [comment]
I will try to do it in the coming days 🙂

**Comment by masonlouchart** [comment]
I fixed it. It was a missing Webpack configuration.
Solution found on StackOverflow: https://stackoverflow.com/a/65982614/1832572

**Comment by awproj** [comment]
I am seeing this issue as well. Can you share what exactly you had to add to which config? Thank you.

**Comment by Stanley288** [comment]
@masonlouchart can you please share what exactly you had to add in the webpack config? Thank you.

**Comment by awproj** [comment]
In my case, I was using an outdated version of react-scripts (via create-react-app). Updating react-scripts from 4.0.3 to  5.0.1 fixed this issue because it includes newer configs that support .min.mjs

**Comment by gabrieljablonski** [comment]
@awproj Thanks for letting us know.

If we get more issues being opened about this, we'll probably add that to our troubleshooting guide.

**Comment by josephecombs** [comment]
I had to do this too - what was tricky was that it didn't initially seem like it worked - I had to nuke node_modules then re run (in my case) yarn.
