### ISSUE TITLE
[BUG] TypeError: Object(...).getElementsByTagName is not a function

### ISSUE THREAD

**Issue by samiashi** [ReactTooltip/react-tooltip#1024]
Upgrading from v5.11.1 to v5.13.0 breaks with 
```
TypeError: Object(...).getElementsByTagName is not a function
    at h (/home/project/hypernova-service/dist/hypernova-service.js:40721:129)
```

I'm using a combination of Hypernova for SSR & React 18 for CSR but it seems that this package breaks my app when being loaded on the SSR after the latest upgrade.

**Comment by samiashi** [comment]
@gabrieljablonski I would need a some time to create one and share it. 
I believe the issue here is we need something similar to `use-client` for NextJS where we only import the module on the client

I'm happy to test any fixes locally to confirm if they work or not

**Comment by gabrieljablonski** [comment]
Is this relevant at all in your case?

https://stackoverflow.com/a/50763521/7731997

**Comment by gabrieljablonski** [comment]
Closing since no response from OP.

Feel free to reopen with more info so we can discuss it.
