### ISSUE TITLE
[BUG] Can't import the named export 'arrow' from non EcmaScript module

### ISSUE THREAD

**Issue by Nagrom33** [ReactTooltip/react-tooltip#1032]
**Describe the bug**
Since today I getting this error:

```
Failed to compile.

./node_modules/react-tooltip/dist/react-tooltip.min.mjs
Can't import the named export 'arrow' from non EcmaScript module (only default export is available)
```

**Version of Package**
v5.13.1

**Desktop (please complete the following information if possible or delete this section):**
 - OS: iOS
 - Browser None
 - Version None
 - Frameworks React 17.0.1

**Additional context**
What I have done today is try to getting "faker" library but getting errors after that, so i removed this library and now i can't get it running again. Hope that somebody can help me out.

**Comment by awproj** [comment]
Can you share why you closed this? It doesn't look like a fix was merged, and I am getting the same error. Did you find the cause? Thank you

**Comment by gabrieljablonski** [comment]
@awproj this is not an issue with this package directly, but with your project configuration. We definitely should add a section covering this under our troubleshooting guide.

Have you tried the stackoverflow link mentioned in #1022?
