### ISSUE TITLE
Not showing up on serve(Azure)

### ISSUE THREAD

**Issue by Sathishvel** [ReactTooltip/react-tooltip#1033]
Works locally. But not showing up in the UAT server(azure)

Version: 5.11.1

**Comment by gabrieljablonski** [comment]
When you say it works locally, have you tried building and running a local production build, or only a development build?

Are there any warnings during build, or errors showing up in the browser console when you hover the anchor element?

Also please try upgrading to v5.13.0.

**Comment by Sathishvel** [comment]
Actually, it's a Next.js project.... so I'm exporting the project (npm run export)

No warnings or error during the export time.

When I hover in the browser it returns a typeerror please find the attached screenshot
![image](https://github.com/ReactTooltip/react-tooltip/assets/24644668/55d01d54-1833-4faa-8ab9-22c81b49f2bb)

**Comment by Sathishvel** [comment]
I've tried the latest version also... the same issue persists

**Comment by gabrieljablonski** [comment]
https://react-tooltip.com/docs/troubleshooting#nextjs-typeerror-f-is-not-a-function

**Comment by Sathishvel** [comment]
It's resolved. Thanks, buddy
