### ISSUE TITLE
[BUG] Error: Module level directives cause errors when bundled, 'use client' was ignored

### ISSUE THREAD

**Issue by roelkoops** [ReactTooltip/react-tooltip#1037]
Hello! I'm using react-tooltip within my Mendix pluggable widget.
When I upgrade react-tooltip from 5.12.0 to 5.13.0 or 5.13.1 I'm no longer able to build my widget and I'm getting this error:

node_modules\react-tooltip\dist\react-tooltip.min.mjs (7:0) Error: Module level directives cause errors when bundled, 'use client' was ignored.5

I see that 'use client' is added in commit 0ae1c20 to prevent breaking Next.js 13 projects.
Any idea how to fix this issue?

**Comment by danielbarion** [comment]
After checking the example repo and checking for the issue at the web, I believe the best way to handle this issue is to remove the `'use client'` from our library, and in our troubleshooting section, suggest to the devs to create a Tooltip component in their projects with the `'use client'` at the top of it.

Does it make sense @gabrieljablonski?

**Comment by gabrieljablonski** [comment]
@danielbarion How do other libraries usually tackle this issue? My guess is they just ignore it and let the user handle it themselves, so removing `"use client"` and adding a troubleshooting section seems adequate.

Another possibility would be to add a `postinstall` script that checks whether we're in a next.js project and automatically adding the directive to the build files, but that seems excessive.

For the troubleshooting section, we should definitely add a snippet the user can just copy and paste to get it to work, such as:


```tsx
// ./ReactTooltip.tsx
"use client"

export * from 'react-tooltip'
```

Not sure if this exact snippet would work as is, but it should be as simple as possible.

**Comment by roelkoops** [comment]
Thanks a lot!
