### ISSUE TITLE
[BUG] TypeError: createContext only works in Client Components

### ISSUE THREAD

**Issue by r1zyn** [ReactTooltip/react-tooltip#1049]
**Describe the bug**
Attempting to use `react-tooltip` in my Next.js project gives this error:
```
TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
```
**Call Stack**
```
createContext
node_modules\react-tooltip\dist\react-tooltip.min.cjs (7:1095)
(sc_server)/./node_modules/react-tooltip/dist/react-tooltip.min.cjs
file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/app/page.js (4409:1)

__webpack_require__
file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/webpack-runtime.js (33:43)

eval
webpack-internal:///(sc_server)/./src/components/core/index.ts (17:71)
(sc_server)/./src/components/core/index.ts
file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/app/page.js (3407:1)

__webpack_require__
file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/webpack-runtime.js (33:43)

eval
webpack-internal:///(sc_server)/./src/components/buttons/AnimatedLink.tsx (7:81)
(sc_server)/./src/components/buttons/AnimatedLink.tsx
file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/app/page.js (3260:1)
__webpack_require__

file:///C:/Users/ascen/OneDrive/Documents/Programming/Websites/MatrixWebsiteV3/.next/server/webpack-runtime.js (33:43)

eval
webpack-internal:///(sc_server)/./src/components/buttons/index.ts (7:71)
```

**Version of Package**
v5.15.0

**To Reproduce**
1) Install Next.js v13.4.4
2) Setup a basic Next.js project
3) Install react-tooltip v5.15.0 and setup using the documentation
4) Use the Tooltip component somewhere in your project
5) Run the development server

**Expected behavior**
The error should appear on localhost:3000 or whichever port you are running the server on.

**Screenshots**
![image](https://github.com/ReactTooltip/react-tooltip/assets/72182515/c5f7d3a0-6cf5-4d2d-a76c-b4d5b1ebad3c)

**Desktop (please complete the following information if possible or delete this section):**
 - OS: Windows 10 Home
 - Browser: Opera GX
 - Version: Already specified
 - Frameworks: Next.js 13

**Comment by gabrieljablonski** [comment]
https://react-tooltip.com/docs/troubleshooting#nextjs-use-client-error

If that doesn't work, feel free to reopen and add more info.
