### ISSUE TITLE
[BUG] React Tooltip ignores classNames since version 5.13

### ISSUE THREAD

**Issue by ansgarsteinkamp** [ReactTooltip/react-tooltip#1050]
Everything was working smoothly up to version 5.12.0, but from version 5.13 onwards, it hasn't been: classNames, such as the Tailwind class `bg-blue-900`, are being overlooked by React Tooltip. This issue still persists in version 5.16.1.
Example:
```
<Tooltip className="z-50 bg-blue-900" id="Home" delayShow={200}>
   Home
</Tooltip>
```

**Comment by danielbarion** [comment]
I'm sorry for not being clear enough on https://github.com/ReactTooltip/react-tooltip/issues/1025

You can:
* work with CSS specificity by adding a class to the tooltip and the Tailwind classes using `@apply` - already explained in another issue.
* you can override the CSS variable - check styling on docs to see the variables.
* [you can disable the styling CSS related to colors from react tooltip](https://react-tooltip.com/docs/examples/styling) - this was introduced into `v5.16.0`, and this is what I said before.
