### ISSUE TITLE
[FEAT REQ] `opacity` prop

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#1051]
**Is your feature request related to a problem? Please describe.**
Previously, the way to change the tooltip opacity (from the 0.9 default value) was to set the CSS variable like so:

```
:root {
  --rt-opacity: 1;
}
```

I believe the recent change in the way the styles are injected broke this.

**Describe the solution you'd like**
- Add a `opacity` tooltip prop to override the default value.
- Add a check on the `style` prop and `console.warn()` if `opacity` is set (only if `env !== 'production'`), advising to use the prop instead (same as done with `border`).

**Additional context**
As mentioned on #1010 ([comment](https://github.com/ReactTooltip/react-tooltip/issues/1010#issuecomment-1616699108)).

**Comment by danielbarion** [comment]
I didn't realize the CSS tokens override is no longer working after the CSS injection feature, but this makes sense! Nice catch!

This gave me one idea: https://github.com/ReactTooltip/react-tooltip/pull/1052

Please feel free to continue the implementation
