### ISSUE TITLE
Which is CSS property/styles which automatically adjusts the height of tooltip if the content goes beyond 'max-width'

### ISSUE THREAD

**Issue by nik32** [ReactTooltip/react-tooltip#1055]
So I am applying max-width property on tooltip so that if the content message is too long... it automatically goes to next line (as shown below) -
<img width="1375" alt="image" src="https://github.com/ReactTooltip/react-tooltip/assets/51018572/ed777d09-0a9d-41b1-9b98-98cbbd1dd2c7">

But sometimes what is happening is that the height of the tooltip is not adjusted and the content flows out of the tooltip (as shown in below img). I feel this is due to some style property overriden by the FullCalendar I am using in the background (in 'month view' of the calendar I am getting this issue. But in 'week view'... tooltip is coming fine)
<img width="987" alt="image" src="https://github.com/ReactTooltip/react-tooltip/assets/51018572/15689a40-c529-4ae9-8b22-65fe2644e729">

So I wanted to know which is the CSS property/styles which was enabling the text to go in nextLine by automatically adjusting the height of tooltip... so that I can explicitly specify in my custom CSS (applied to the tooltip) to make the Content come in next line in 'month view' also

**Comment by gabrieljablonski** [comment]
It's hard to give any suggestions without seing the project firsthand.

But going by what you said, that the tooltip works fine in one mode, and breaks in another one, you can try moving the tooltip component outside whatever component might be overriding the styling, so only your tooltip-specific styling is applied to it.

**Comment by nik32** [comment]
@gabrieljablonski thanks for the instant reply. Actually I can't do it coz... the calendar is not in my hand (the library decides when and where to render the Item). Any other solution coming to your mind? I though of explicitly providing the same style on my tooltip instance... which is used in the your library to get the text come in next line

**Comment by gabrieljablonski** [comment]
Can you provide a summary of how your project looks when it comes to the DOM structure? 

I'm guess you have a custom view that you pass to the `<FullCalendar />` component, and you're placing the `<Tooltip />` component inside the custom view render.

If that's the case, try placing the `<Tooltip />` alongside `<FullCalendar />` and see if that works. Like so:

```tsx
<div>
  <FullCalendar
    {...}
  />
  <Tooltip />
</div>
```

---

If that's not the case, or it doesn't work, you would have to provide a sample project reproducing it. Without that, it's really hard to give any suggestions.

**Comment by nik32** [comment]
I tried the above but in that case tooltip goes under the calendar and doesn’t appear as intended. 
But I got the problematic CSS style. It was `white-space`. The 'month view' was applying `white-space: nowrap`. Adding `white-space: normal` in the styles of the tooltip instance worked. @gabrieljablonski thanks a lot for taking time to help me out. I really appreciate it!

**Comment by gabrieljablonski** [comment]
No problem. If you run into similar issues in the future, try my suggestion again, and set the z-index so the tooltip shows up properly, either with css, or with inline styling:

```tsx
<Tooltip style={{ zIndex: 99 }} />
```

**Comment by nik32** [comment]
Yes I tried the above and can confirm that it also works. And I think is a bit more efficient as the `<Tooltip>` instance is not created for each event in the calendar ([as mentioned here](https://react-tooltip.com/docs/troubleshooting#dynamically-generated-anchor-elements))

**Comment by nik32** [comment]
@gabrieljablonski related to performance... it is mentioned [here](https://react-tooltip.com/docs/troubleshooting#move-tooltip--on-the-dom) that we should try and keep `<Tooltip>` in the `App.tsx`. In that case how do we target this Global `<Tooltip />` instance to show some content in it?

**Comment by gabrieljablonski** [comment]
> we should try and keep `<Tooltip>` in the `App.tsx`

That is mostly a suggestion if you're running into weird issues when using the tooltip, it's not a hard rule.

> In that case how do we target this Global `<Tooltip />` instance to show some content in it?

See the [data attributes section](https://react-tooltip.com/docs/getting-started#using-anchor-data-attributes).

**Comment by nik32** [comment]
Got it! Thanks for your time!
