### ISSUE TITLE
[BUG] Tooltip is not tracking trigger element when resizing window

### ISSUE THREAD

**Issue by hurrmun** [ReactTooltip/react-tooltip#1057]
**Bug description**
resizing the window does not move the tooltip along with the anchor element

**Version of Package**
v5.18.0

**To Reproduce**
codesandbox: **https://codesandbox.io/p/sandbox/react-tooltip-resize-tracking-mszsgp?file=%2Fsrc%2FApp.tsx%3A6%2C17** 

**Expected behavior**
Expected the tooltip to track the trigger element upon page resize

**Desktop (please complete the following information if possible or delete this section):**
 - OS: MacOS
 - Browser: Chrome
 - Frameworks [e.g. React 17/18, Vite]

**Additional context**
Not sure if this is considered a bug as the behaviour is not explicitly stated on the docs, but floating-ui seems to support the resize using autoUpdate and the library already tracks scrolling

**Comment by gabrieljablonski** [comment]
We indeed do not track page resize. We'll leave this open so we can try using `autoUpdate()` in the future.

Until then, my suggestion is to use `closeOnResize`.

**Comment by gabrieljablonski** [comment]
`react-tooltip@v5.20.0` now uses `floating-ui`'s `autoUpdate()` function.
