### ISSUE TITLE
[BUG] Tooltip does not work when CSP is set to style-src: 'self'

### ISSUE THREAD

**Issue by zachary-woodridge** [ReactTooltip/react-tooltip#1059]
**Bug Description**
When I run a local development server the tooltip appears fine, but when I deploy to my server that has a Content Security Policy set to `style-src: 'self'` and load my webpage I get a bunch of errors in console that point to the react-tooltip files. The html element will appear and disappear from the DOM on hover but nothing will display.

**Version of Package**
v5.18.0

**Expected Behavior**
The style is included without being injected inline and the tooltip can render

**Screenshots**
![error](https://github.com/ReactTooltip/react-tooltip/assets/97980341/a61789c7-3d3b-4355-9a5f-a56a3c4d3d72)
![error2](https://github.com/ReactTooltip/react-tooltip/assets/97980341/14d64e67-d700-40f1-b970-cf5cc83e40ce)

**Comment by danielbarion** [comment]
@zachary-woodridge can you please try disabling the style injection: https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css

and try importing the CSS file like previous versions: https://github.com/ReactTooltip/react-tooltip#usage

And let we know about the result, thanks!

**Comment by zachary-woodridge** [comment]
This solved my issue, thanks a bunch! I wish I had known to look at that part of the docs earlier. 
Style Injection
unsafe inline
