### ISSUE TITLE
[BUG] Unable to disable style injection

### ISSUE THREAD

**Issue by ShahwarNisar** [ReactTooltip/react-tooltip#1060]
Hi,
I have to apply CSP standards in my React application. So, according to your docs, we have to set REACT_TOOLTIP_DISABLE_BASE_STYLES=true & REACT_TOOLTIP_DISABLE_CORE_STYLES=true to disable styles and import the CSS styles file in app.js. But apparently, after following all the steps I'm still seeing react-tooltip adding inline styles.

Can you please suggest a way how can I achieve this? You can check SS of the error.

![image](https://github.com/ReactTooltip/react-tooltip/assets/22368580/47f978f2-f779-4c73-942d-8e75258f9cff)

Regards,
Shahwar

**Comment by gabrieljablonski** [comment]
Please give more details about your dev environment. 

Are you running a `create-react-app` project or something else? 
What is your bundler?

**Comment by danielbarion** [comment]
@ShahwarNisar have you seen it? https://github.com/ReactTooltip/react-tooltip/issues/1059

Also, are you sure those environment variables are being loaded correctly?

Can you provide the information that @gabrieljablonski asked, please? and if possible, a reproducible example

**Comment by ShahwarNisar** [comment]
Hi, Thanks for the quick response really appreciate that.

@gabrieljablonski I'm using react-scripts

@danielbarion Yes I have followed both ways mentioned here (https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css) but neither one worked for me. Also, I have tried setting values directly to the env files as well as in the build value in the package.json like:

`"build": "npm run generate-meta-tag && (SET REACT_TOOLTIP_DISABLE_CORE_STYLES=true) && (SET REACT_TOOLTIP_DISABLE_BASE_STYLES=true) && (SET INLINE_RUNTIME_CHUNK=false) && react-scripts build"`

Let me know/guide please if I'm doing something wrong, please.

**Comment by gabrieljablonski** [comment]
I believe this is happening because `react-scripts` only imports environment variables that start with `REACT_APP_`.

Bundlers like `esbuild` and `rollup` usually have a `define` config option which is used to "find and replace" occurrences of `process.env.<variable>`, and I believe `react-scripts` does not have something similar.

@danielbarion we might have to consider extra env variables with the `REACT_APP_` prefix to support `react-scripts`.

**Comment by gabrieljablonski** [comment]
@ShahwarNisar please test what we're trying on #1052 with the beta version `react-tooltip@5.19.0-beta.1052.0`.

If I understand your use-case correctly, you should do `<Tooltip disableStyleInjection='core' />`, and then do  the import manually with `import 'react-tooltip/dist/react-tooltip.css'`.

Please let us know the results.

**Comment by ShahwarNisar** [comment]
> @ShahwarNisar please test what we're trying on #1052 with the beta version `react-tooltip@5.19.0-beta.1052.0`
> 
> If I understand your use-case correctly, you should do `<Tooltip disableStyleInjection='core' />`, and then do the import manually with `import 'react-tooltip/dist/react-tooltip.css'`.
> 
> Please let us know the results.

Hey @gabrieljablonski,
I hope you're doing well. I wanted to inform you that I've tested the code with the changes you suggested, and I'm happy to report that it works perfectly! Your fix has resolved the issue we were facing, and everything is functioning as expected now.

Once again, thank you for your excellent work!

Best regards,
Shahwar

**Comment by gabrieljablonski** [comment]
That's great to hear.

I suggest upgrading to the official release `react-tooltip@5.19.0`
