### ISSUE TITLE
Tooltip default export not working

### ISSUE THREAD

**Issue by saravanapandi** [ReactTooltip/react-tooltip#1061]
import styled from 'styled-components';
import {Tooltip} from 'react-tooltip'

export const StyledReactTooltip = styled(Tooltip)`
  background-color: white !important;
  color: black !important;
  box-shadow: 0px 2px 20px lightgray;
  &:after {
    border-top-color: white !important;
  }
`;

./node_modules/react-tooltip/dist/react-tooltip.min.mjs
Can't import the named export 'arrow' from non EcmaScript module (only default export is available)

**Comment by gabrieljablonski** [comment]
What version of `react-scripts` are you running? Are you able to upgrade to at least `5.0.1`? Please let us know so we can add this solution to our troubleshooting section.

**Comment by gabrieljablonski** [comment]
We've had confirmation on #1070 that updating your webpack config fixes this.

If you're not using webpack, please reopen with more info.
