### ISSUE TITLE
[BUG] anchorSelect is broken for dynamic elements after v5.12.0

### ISSUE THREAD

**Issue by NemeZZiZZ** [ReactTooltip/react-tooltip#1063]
**Bug description**
I updated to latest version to get style disabling.
After that I got tons of bugs from my testing crew about tooltip doesn't work randomly.
After my research I found out, that tooltip only works for element, that were on page before tooltip initialization, but doesn't work on any other element, that added to dom after that.
I downgraded tooltip version step by step via every minor - and found out, that the last working one was 5.12.0, that I used before upgrade.

**Version of Package**
^5.13.0

**To Reproduce**
Add static element with tooltip via attached `anchorSelect`.
Dynamically add element to page after tooltip with the same selector.
Tooltip wil work only for first static one.

**Expected behavior**
Tooltip with `anchorSelect` should work with dynamically created elements, like it was for v5.12.0

**Comment by gabrieljablonski** [comment]
Cannot reproduce on v5.18.1

https://stackblitz.com/edit/stackblitz-starters-tmrv6e?file=src%2FApp.tsx

I believe this example follows your steps to reproduce. I memoized the component to make sure the tooltip wasn't getting re-rendered. Please provide an example reproducing the issue.

**Comment by NemeZZiZZ** [comment]
Thanks for fast response. Seems to be related to my SSR env. Made it to be client-only for sure, it really works for now.
Excuse me for doubting you :) Closing this one.
