### ISSUE TITLE
[FEAT REQ]  Add animations to the tooltip

### ISSUE THREAD

**Issue by Lirak-f** [ReactTooltip/react-tooltip#1077]
**Is your feature request related to a problem? Please describe.**
Would like to be able to add animations to the tooltip when it is showing and hiding.

**Describe the solution you'd like**
Add a class name that indicates when tooltip is shown.

**Describe alternatives you've considered**
Replace module css with a simple class name that does not change

**Additional context**
Currently for shown class name, 'react-tooltip' uses module css that adds some hash class names '.core-styles-module_tooltip__3vRRp', that could change overtime and break the changes

**Comment by gabrieljablonski** [comment]
Thanks for the suggestion. #1078 implements this.

We'll close the issue when we do a new release.

**Comment by gabrieljablonski** [comment]
Tooltip now has the `react-tooltip__show` class on `react-tooltip@v5.20.0`
