### ISSUE TITLE
[BUG] Test `'tooltip with delay show'` inconsistent snapshot

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#1080]
Managed to reproduce locally the problem with the workflow sometimes failing, and passing on re-run, though this time it is happening with the newer `react-tooltip__show` class.

https://github.com/ReactTooltip/react-tooltip/blob/master/src/test/tooltip-props.spec.js#L118-L144

https://github.com/ReactTooltip/react-tooltip/blob/master/src/test/__snapshots__/tooltip-props.spec.js.snap#L86

The snapshot switches between having and not having `react-tooltip__show`. I believe this is likely because we're not using `waitFor()` correctly to account for the `delayShow` timer.

**Comment by victorpavlenko** [comment]
what about __disappear?
