### ISSUE TITLE
How to use it in Next.js Server Components?

### ISSUE THREAD

**Issue by erfanium** [ReactTooltip/react-tooltip#1081]
currently i got this error in Next.js 13 app directory:

```
You're importing a component that needs useLayoutEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
```

I really do not want to use "use client" to sacrifice my component performance because of some tooltips.

is there any way to use it in Sever Components?

**Comment by erfanium** [comment]
I fixed by problem using this component instead. not sure it's the best way to do it or not
```tsx
"use client";
export { Tooltip } from "react-tooltip";
```

**Comment by gabrieljablonski** [comment]
As per [our troubleshooting](https://react-tooltip.com/docs/troubleshooting#nextjs-use-client-error), this is indeed the recommended method.
