### ISSUE TITLE
Alternative to Provider/wrapper that doesn't require id or class

### ISSUE THREAD

**Issue by deanmraz** [ReactTooltip/react-tooltip#1085]
The deprecated Provider/wrapper has the ideal API since you don't need to specify an id or class as the anchor. I haven't seen a way to achieve this with the latest API, but maybe I missed it. Can someone point me in the right direction? 

https://react-tooltip.com/docs/examples/provider-wrapper

```
import { Tooltip, TooltipWrapper } from 'react-tooltip';

<TooltipWrapper content="I am using a global tooltip!">
  <a> ◕‿‿◕ </a>
</TooltipWrapper>
<TooltipWrapper content="This is the same tooltip!">
  <a> ◕‿‿◕ </a>
</TooltipWrapper>
// the tooltip component can be placed anywhere inside the provider
<Tooltip />
```

Ideal use case 
* Works great and do not have to manage anchors for all buttons/links. 

```
    <TooltipWrapper
      place={place}
      content={message}
      positionStrategy={positionStrategy}
    >
      {children}
    </TooltipWrapper>

```

Not ideal 
* This doesn't work because all tooltips will have the same anchor tag.. so that means we always have to specify custom anchor for every button / link that needs a tool tip.

```

    <div className="tooltipAnchor">{children}</div>
    <Tooltip
      anchorSelect={`.tooltipAnchor`}
      place={place}
      content={message}
      positionStrategy={positionStrategy}
    />

```

**Comment by gabrieljablonski** [comment]
Support for the Provider/Wrapper was dropped because of the overhead for setting up, and complexity added to the tooltip internal code, so definitely avoid using it, since it will be removed in a future version.

To best help you here, can you be more specific on what you mean by not having to "manage anchors for all buttons"?

Have you looked at the `data-tooltip-*` attributes? 

https://react-tooltip.com/docs/options#available-attributes

Does this not work for your use case?

**Comment by deanmraz** [comment]
@gabrieljablonski Yes you are right I can use `data-tooltip-id` and `<Tooltip id="my-tooltip" />` Thanks for the quick help!

--- 

FYI,

Looks like I understood the documentation wrong, thought it meant to have the `<Tooltip id="my-tooltip" />` on each component which caused rendering problems. 

I think I was confused because other examples show it together... 

```
<a id="not-clickable">◕‿‿◕</a>
<Tooltip anchorSelect="#not-clickable">
  <button>You can't click me :(</button>
</Tooltip>
```

Maybe it makes sense to specify that `<Tooltip id="my-tooltip" />` can be placed in the App.tsx?

**Comment by gabrieljablonski** [comment]
Good to know.

Right now we feel like the documentation is clear enough. If more people end up having the same trouble, we'll consider updating it. Thanks for the suggestion though.
