### ISSUE TITLE
named export 'arrow' from non EcmaScript

### ISSUE THREAD

**Issue by chayaf324** [ReactTooltip/react-tooltip#1086]
# Check the troubleshooting page before opening an issue!

Make sure your problem isn't already covered at the troubleshooting page: https://react-tooltip.com/docs/troubleshooting

----

**Bug description**
Getting error:
./node_modules/react-tooltip/dist/react-tooltip.min.mjs
Can't import the named export 'arrow' from non EcmaScript module (only default export is available)

I'm not using webpack.config.js and not equivalent

**Version of Package**
"^5.21.1"

**To Reproduce**
copy package to node-modules and add to package.json (I can't install with npm)
and just import:
import { Tooltip} from "react-tooltip";
 - it fails to compile:

**Comment by gabrieljablonski** [comment]
Please check the troubleshooting page:

https://react-tooltip.com/docs/troubleshooting#cant-import-the-named-export-xxx-from-non-ecmascript-module-only-default-export-is-available

**Comment by chayaf324** [comment]
thanks, but I'm not using webpack

**Comment by gabrieljablonski** [comment]
Unfortunately there's not enough information for us to suggest any way to fix this. Are you able to provide a sample project to reproduce it?

**Comment by chrisbeach** [comment]
+1 

also couldn't fix after reading that page

**Comment by gabrieljablonski** [comment]
@chrisbeach if possible, please provide more info about your environment, or even a sample project so we can reproduce the issue.

Without more info, the best I can suggest is to edit `node_modules/react-tooltip/package.json` to use `react-tooltip.min.cjs` instead of the `.mjs` version, but that's a workaround and not a fix.

**Comment by chayaf324** [comment]
I found the webpack file in node-modules/react-scripts and it solved the problem.
