### ISSUE TITLE
GitHub & npm mismatch

### ISSUE THREAD

**Issue by targumon** [ReactTooltip/react-tooltip#1093]
In NPM latest version is 5.21.4 and was published 4 days ago: https://www.npmjs.com/package/react-tooltip?activeTab=versions

However in GitHub the latest commit is from 2 weeks ago and it's a chore for version 5.21.3: https://github.com/ReactTooltip/react-tooltip/commits/master

There's also no mention of 5.21.4 in the releases: https://github.com/ReactTooltip/react-tooltip/releases

I hope you weren't hacked and a rouge package was published under your name.

I think other maintainers have processes in place to keep these in sync.

**Comment by danielbarion** [comment]
Hey @targumon,

I just checked, and the last publish was by @gabrieljablonski:

![image](https://github.com/ReactTooltip/react-tooltip/assets/9615850/c020ffc8-3c8c-4cb7-9677-cdd8c895dd0a)

we probably forgot to update the release notes, but our last releases have no code changes, only adjusting the sponsoring banner.

I'll confirm with Gabriel and we will update the release notes.

Thank you so much for checking and letting us know!

**Comment by gabrieljablonski** [comment]
Hi @targumon.

Thanks for letting us know, but no need to worry. Sometimes we do minor releases related to some tests we do, and end up not updating the release notes. Though we'll make sure this doesn't happen again so it doesn't cause any confusion.

Thanks again.
