### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by giumi437** [ReactTooltip/react-tooltip#1094]
Hello, I have the following error after install last version of the package

Compiled with problems:
×
ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs 24:44-51
Module not found: Error: Can't resolve 'process/browser' in 'D:\xxxx\node_modules\react-tooltip\dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
ERROR in ./node_modules/react-tooltip/dist/react-tooltip.min.mjs
Cannot read properties of undefined (reading 'module')

**Comment by gabrieljablonski** [comment]
Hi @giumi437. Please provide some information about your project environment, such as framework or bundler (`create-react-app`, Next.js, ...).

It seems like your project is not supporting `.mjs` files, but with some more info we might be able to give some suggestions on how to fix that.

**Comment by tiagoberwanger** [comment]
I'm having the same issue!

```
ERROR in ../node_modules/react-tooltip/dist/react-tooltip.min.mjs
Cannot read properties of undefined (reading 'module')
TypeError: Cannot read properties of undefined (reading 'module')
```

**Comment by gabrieljablonski** [comment]
Not much can be done without more info about the dev environment.

@giumi437 or @tiagoberwanger, feel free to reopen with more info.

**Comment by huurray** [comment]
I faced same issue. I fixed it with this info.
https://github.com/react-dnd/react-dnd/issues/3425
