### ISSUE TITLE
can you lazily load the tooltip

### ISSUE THREAD

**Issue by PTAHume** [ReactTooltip/react-tooltip#1095]
Hi,

I was wondering if it's possible to use the lazy load the tooltip module, I have if added based on a condition

```
{activity.host?.following && (
<>
    <Icon 
            name="info"
            data-tooltip-id="following"
            data-tooltip-content="You are following this person"
            className="micro" circular />
    <Tooltip id="following" place='left' />
</>
)}
```

I am using [react-lazily](https://www.npmjs.com/package/react-lazily) not to be confused with React.Lazy

if I use 

```
const { Tooltip } = lazily(() => import("react-tooltip"))
```

The component doesn't show, but VSCode shows that it knows the component location in the npm packages, so not sure why this wouldn't work ?

many thanks in advarnce

**Comment by gabrieljablonski** [comment]
Hi @PTAHume, have you figured it out? I'm guessing it was something simple that was overlooked.

Even so, do you mind sharing what it was? Someone might stumble into the same thing in the future. Thanks!

**Comment by PTAHume** [comment]
sure, it actually worked from the beginning but the browser cache was able to fool me into thinking it didn't despite the fact I was sure I had cleared it out beforehand 🤪
