### ISSUE TITLE
Document proxy caused error because of observe window.document in trackRemoval

### ISSUE THREAD

**Issue by CrazyWood007** [ReactTooltip/react-tooltip#1115]
I make a proxy of window.document and replaced it.
After that, `observer.observe(window.document)` will throw error as below.
`Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'`

For some reason, I have to make this proxy. But I cant solve this error.

Could you please change this window.document to window.document.documentElement?

react-tooltip version:  V4

**Comment by gabrieljablonski** [comment]
We're not maintaining V4 anymore. Please fork from [the latest V4 tag](https://github.com/ReactTooltip/react-tooltip/tree/v4.5.1) and make the changes you need.
