### ISSUE TITLE
[BUG] Unexpected behavior with `delayShow`

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#1119]
**Bug description**
`delayShow={1000}` results in unexpected behavior when hovering between anchor elements.

**Version of Package**
v5.22.0

**To Reproduce**
Hover between two anchor elements that share a tooltip with a value set for `delayShow`. The tooltip will change to the second anchor element before closing.

**Expected behavior**
Two options:

1. The tooltip should stay open when hovering between two elements that are close enough
2. The tooltip should abruptly close, and open again for the new anchor only after the set delay

I lean towards 1.

**Additional context**
CodeSandbox sample: https://codesandbox.io/s/frosty-noether-y4m79q?file=/src/App.js

#1114 related

**Comment by gabrieljablonski** [comment]
@dsims01 tagging you so you know when it's fixed.

**Comment by gabrieljablonski** [comment]
Forgot to mention, a viable workaround is to also set `delayHide` to something like 150ms, which should mitigate greatly this specific scenario of switching between anchor elements that are close by.

**Comment by OahMada** [comment]
Same here.

**Comment by gabrieljablonski** [comment]
`react-tooltip@5.26.1-beta.1168.0` (from #1168) seems to fix this.

Feel free to test it out until we are ready to release an official version.

**Comment by gabrieljablonski** [comment]
Fixed on official release `react-tooltip@5.26.1`
