### ISSUE TITLE
[BUG] Tooltip with no content is still shown

### ISSUE THREAD

**Issue by yriklin** [ReactTooltip/react-tooltip#1120]
**Bug description**
A tooltip is displayed even when its contents are null or undefined.
In our case, we have a react-simple-maps component, and when the users hover over countries, only for countries with data should the tooltip be displayed.

**Version of Package**
5.22.0

**To Reproduce**
Import the Tooltip component from react-tooltip and use it as follows:

`
<Tooltip>
    {tooltipData ? renderTooltipData() : null}
</Tooltip>
`

Change the state of tooltipData, and see that when it's null, an empty tooltip is displayed.

**Expected behavior**
If tooltipData is null or undefined, the tooltip should not be displayed.

**Screenshots**
![image](https://github.com/ReactTooltip/react-tooltip/assets/52748314/b2252a03-d900-4700-a280-335b9948203a)

**Additional context**
1. The bug is not reproduced on version 5.21.7.
2. React version we use: ^17.0.2

**Comment by gabrieljablonski** [comment]
Please test with beta version `react-tooltip@5.22.1-beta.1118.0`

**Comment by gabrieljablonski** [comment]
Fixed on official release `react-tooltip@5.23.0` (alongside the new ["imperative mode"](https://react-tooltip.com/docs/examples/imperative-mode), check it out 😀😀)
