### ISSUE TITLE
[BUG] Tooltip get sometimes stuck

### ISSUE THREAD

**Issue by marcantoinegodde** [ReactTooltip/react-tooltip#1121]
Hello guys, first of all thanks for the bug fix in 5.23.0

**Bug description**
When hovering, the tooltip might get stuck. Check out this video. The bug was introduced in 5.22.0 and 5.23.0 patch didn't catch it unfortunately. :( It seems that the bug was already there in 5.22.0.

https://github.com/ReactTooltip/react-tooltip/assets/6016732/0c33587a-713a-454c-aff5-54e0f898603c

**Version of Package**
v5.23.0

**Expected behavior**
Tooltips should disappear when not hovering

**Comment by gabrieljablonski** [comment]
Have you taken a look at this? https://react-tooltip.com/docs/troubleshooting#the-tooltip-doesnt-close

Not sure what else might be causing this. Can you provide a CodeSandbox or similar reproducing it?

**Comment by marcantoinegodde** [comment]
How can you possibly be so fast ? 😆 You fixed my issue, this was indeed an opacity issue. 

For future readers, since I am using Tailwind, replacing `className="!opacity-100"` by `opacity={1}` made the trick.
