### ISSUE TITLE
[FEAT REQ] Changeable role attribute (v5)

### ISSUE THREAD

**Issue by mailinhdang** [ReactTooltip/react-tooltip#1123]
**Is your feature request related to a problem? Please describe.**
Regarding the tooltip design pattern of the W3C (https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/), a tooltip should "_not receive focus. A hover that contains focusable elements can be made using a non-modal dialog_". 
Currently, I have a use case where my tooltip contains multiple buttons or links. Hence, my tooltip should rather be a non-modal dialog and for dialogs, you usually set `role=dialog` instead of `role=tooltip`.

**Describe the solution you'd like**
Making the role of the tooltip component a changeable property or adding a prop `asDialog` would be very helpful to set the correct role attribute.

**Comment by gabrieljablonski** [comment]
Definitely doable. You're welcome to submit a PR if you'd like. If not, we'll probably get around to this in a few days.

Thanks for the suggestion.

**Comment by gabrieljablonski** [comment]
Available on official release `react-tooltip@5.24.0`

Thanks @mailinhdang for the contribution!
