### ISSUE TITLE
Disable auto position when using place?

### ISSUE THREAD

**Issue by thomas-hogan** [ReactTooltip/react-tooltip#1127]
Currently I am using `place="bottom-start"` and it works as expected. When the anchor element is towards the bottom of the screen the tooltip opens above. Is there a way to disable that auto positioning and have the tooltip always open bottom-start regardless of where it is on the screen?

**Comment by gabrieljablonski** [comment]
Hi @thomas-hogan.

Although we don't have an explicit way of doing this, you can achieve it by using customizing the `middlewares` prop. Here's [an explanation from a previous issue](https://github.com/ReactTooltip/react-tooltip/issues/1044#issuecomment-1602744677).

As explained there, what you probably want to do is remove both `shift()` and `flip()`, so you'll end up with something like this

```tsx
import { offset } from '@floating-ui/dom'

<Tooltip
  middlewares={[offset(10)]}
/>
```

**Comment by thomas-hogan** [comment]
Thanks, that did the trick!
