### ISSUE TITLE
[Question]: Why do I keep seeing this warning?

### ISSUE THREAD

**Issue by mycroft-cesar** [ReactTooltip/react-tooltip#1131]
Hi everyone!

I'm using the library on my project and this warning keeps being rendered a lot of times (I have one usage in one page and it renders 4x). It's really annoying and I would like to understand why is this happening.

I took a look on the source code and there's this custom event being triggered `react-tooltip-inject-styles`. This is only happening in non-prod environments. I wonder if this has anything to do with Strict Mode. 

![image](https://github.com/ReactTooltip/react-tooltip/assets/121102630/3141e0bb-e964-44c3-8136-9891c521e764)

**Comment by danielbarion** [comment]
React on development mode and re-render the component a few times to test if the lifecycle will be the same every time and prevent bugs in production. On production, this doesn't happen.

You can read more about it here:
https://react.dev/reference/react/StrictMode

**Comment by mycroft-cesar** [comment]
@danielbarion I added the strict mode and now it logs 8x. It shows up only on the first page render but I'd like it to go away still. 

![image](https://github.com/ReactTooltip/react-tooltip/assets/121102630/dd76abd4-b50c-4a74-b469-309fc83f47be)

**Comment by gabrieljablonski** [comment]
It's hard to suggest a solution without details about your environment, but there's something you can try to workaround it.

Set `disableStyleInjection` to `'core'`, and add the import `import 'react-tooltip/dist/react-tooltip.css'` to your `App.jsx` or equivalent file.

https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css

**Comment by gabrieljablonski** [comment]
Closing this since it's been a while with no response. Please reopen if you have anything more to add.
