### ISSUE TITLE
Question regarding tooltip width and element padding

### ISSUE THREAD

**Issue by Hotmanics** [ReactTooltip/react-tooltip#1134]
<img width="852" alt="Screenshot 2023-12-09 at 6 16 11 PM" src="https://github.com/ReactTooltip/react-tooltip/assets/32080359/339ff8f5-fdc8-4075-afbe-18552af45d8c">

```
<Tooltip id="my-tooltip">
          <p className="text-green-400 font-bold text-xl">{"Member Hat"}</p>
          <p>Binds when claimed</p>
          <p>Unique</p>
          <div className="flex">
            <p className="flex-auto">Head</p>
            <p className="flex-auto">Cloth</p>
          </div>
          <p className="">{hatDetails?.data.description}</p>
          <p>Requires 100 Reputation Tokens</p>
          <p className=" text-green-400 font-bold">{"Equip: Grants access to view and edit specific ATX DAO CharmVerse documents."}</p>
</Tooltip >
```

1. I would like to reduce the spacing between elements and changing their padding doesn't seem to do anything. Is this possible?
2. I would like to have the tooltip ignore the size of the description property and either have the tooltip's width at a fixed size or have it be based on a different element. Is this possible?

Glad to further clarify if this is confusing.

Thank you!

**Comment by gabrieljablonski** [comment]
If the code you pasted is correct, you have multiple elements as direct children for the tooltip. This makes it a little harder to style the content.

Try wrapping these elements in a single element, and apply your fixed width and other spacing rules to it.

I'll close this since it's not directly related to the tooltip, but rather general CSS stuff.

But let me know if my suggestion works for you, if not, try providing a CodeSandbox so it's easier to give specific suggestions.

**Comment by Hotmanics** [comment]
> If the code you pasted is correct, you have multiple elements as direct children for the tooltip. This makes it a little harder to style the content.
> 
> Try wrapping these elements in a single element, and apply your fixed width and other spacing rules to it.
> 
> I'll close this since it's not directly related to the tooltip, but rather general CSS stuff.
> 
> But let me know if my suggestion works for you, if not, try providing a CodeSandbox so it's easier to give specific suggestions.

Thanks that worked!

**Comment by Hotmanics** [comment]
<img width="826" alt="Screenshot 2023-12-09 at 9 00 02 PM" src="https://github.com/ReactTooltip/react-tooltip/assets/32080359/ba989ce8-f474-4f42-9532-abd22a180cea">

I am having a new problem where Iam dynamically rendering a list of elements as their own components. 

It seems that each consecutive element is placed in front of the previous, leading to the tooltip to appear behind certain components. Setting the z-index of things doesn't seem to work. Any ideas?

I know this also probably a CSS question, but I appreciate your help! Thanks. @gabrieljablonski

**Comment by gabrieljablonski** [comment]
Try also setting your other elements to a lower z-index, and the tooltip itself (try using `className` or the `.react-tooltip-selector`).

You should also consider moving the tooltip component outside your hat component, and using the `render` prop or the `data-tooltip-html` (or simply `data-tooltip-content` if the tooltip content is generic enough) attribute to render the content dynamically. See the [troubleshooting page](https://react-tooltip.com/docs/troubleshooting#dynamically-generated-anchor-elements) for more info on why.

**Comment by Hotmanics** [comment]
> Try also setting your other elements to a lower z-index, and the tooltip itself (try using `className` or the `.react-tooltip-selector`).
> 
> You should also consider moving the tooltip component outside your hat component, and using the `render` prop or the `data-tooltip-html` (or simply `data-tooltip-content` if the tooltip content is generic enough) attribute to render the content dynamically. See the [troubleshooting page](https://react-tooltip.com/docs/troubleshooting#dynamically-generated-anchor-elements) for more info on why.

Ah yes! It seems after explicitly setting the tooltip to z-index 10 and everything else to z-index 1, it properly renders over it. 

I will have to look into your other recommendation. I see the point, much better to have 1 instance of tooltip rather than many of them. Will reach out if I struggle with the process.

Thanks a ton! I really appreciate your help!
