### ISSUE TITLE
Bundle bloated to 14kb gzip

### ISSUE THREAD

**Issue by JiLiZART** [ReactTooltip/react-tooltip#1143]
# Check the troubleshooting page before opening an issue!

Make sure your problem isn't already covered at the troubleshooting page: https://react-tooltip.com/docs/troubleshooting

----

**Bug description**
Seems latest versions of library has bloated 
https://bundlephobia.com/package/react-tooltip@5.25.0

So README lies about bundle size

**Version of Package**
v5.25.0

**To Reproduce**
https://bundlephobia.com/package/react-tooltip@5.25.0

**Expected behavior**
Decrease size of library back to 9KB

**Screenshots**
<img width="1447" alt="image" src="https://github.com/ReactTooltip/react-tooltip/assets/62051/d9364e5c-e009-450b-a903-e81a31c74757">

**Desktop (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Smartphone (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Additional context**

**Comment by gabrieljablonski** [comment]
We've been accumulating deprecated code over time, so the readme is indeed outdated. We'll probably just remove it until we can work on trimming the bundle size back down.

Thanks for pointing it out, it should be addressed soon.

**Comment by JiLiZART** [comment]
For my, I can suggest https://www.npmjs.com/package/bundlesize 
I use this package in my projects to control bundle bloating

**Comment by danielbarion** [comment]
Hi guys, first of all, thanks for the heads-up, we already noticed it and this will be addressed on V6.

We are already using `bundlesize` package:
https://github.com/ReactTooltip/react-tooltip/blob/master/package.json#L15
https://github.com/ReactTooltip/react-tooltip/blob/master/package.json#L67

`size-limit` sounds very interesting too, we will take a look, thanks!
