### ISSUE TITLE
[BUG] Strings are not escaped properly

### ISSUE THREAD

**Issue by devnoot** [ReactTooltip/react-tooltip#1150]
# Check the troubleshooting page before opening an issue!

Make sure your problem isn't already covered at the troubleshooting page: https://react-tooltip.com/docs/troubleshooting

----

**Bug description**
Tooltip does not appear for string with `'` character in it

**Version of Package**
v5.25.1

**To Reproduce**
This works 

```js
<li data-tooltip-id="Hot" data-tooltip-content="Hot" data-tooltip-place="right">
  <a href={"#"}>Hot</a>
  <Tooltip id="Hot"/>
</li>
```

This does not

```js
<li data-tooltip-id="What's Hot" data-tooltip-content="What's Hot" data-tooltip-place="right">
  <a href={"#"}>What's Hot</a>
  <Tooltip id="What's Hot"/>
</li>
```

**Expected behavior**

Both should work

**Comment by gabrieljablonski** [comment]
`id` is used as a regular html id attribute. Per [the docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id):

> Technically, the value for an id attribute may contain any character, **except whitespace characters**.

**Comment by taranga99** [comment]
This is wat I did to run it. As, the data-tooltip-id and the id passed on to the tooltip has to be same and does not take a single quote , I took it out of the string and passed it. And the passed the actual string to be rendered as a children.

![image](https://github.com/ReactTooltip/react-tooltip/assets/72241471/cb862683-944d-447b-bba5-c34c8c228d92)
