### ISSUE TITLE
[BUG] when i zoom out or in the big screen resolutions the tooltip is not in right place

### ISSUE THREAD

**Issue by neutron92** [ReactTooltip/react-tooltip#1152]
# Check the troubleshooting page before opening an issue!

Hello please the tooltip when i zoom out or in the big screen resolutions the tooltip is not in right place
----

**Bug description**
the tooltip when i zoom out or in the big screen resolutions the tooltip is not in right place on the top of the element (icon)
![image](https://github.com/ReactTooltip/react-tooltip/assets/6135555/98a34c92-8f77-4e8e-b7f8-4494b01a8f7c)

**Version of Package**
v5.21.5

**To Reproduce**
```
<ReactTooltip
        id={id || 'my-tooltip'}
        border={'gray'}
        className="tooltip"
        delayShow={500}
        variant="dark"
        place={'top'}
        style={{ zIndex: 9999 }}
      />
```

**Expected behavior**
in the right place on the top of the element (icon)

**Screenshots**
<img width="356" alt="image001" src="https://github.com/ReactTooltip/react-tooltip/assets/6135555/98e2d873-296a-44a5-9261-10ee3faae657">

**Desktop (please complete the following information if possible or delete this section):**
 - OS: any
 - Browser: any
 - Version any
 - Frameworks  Next.js 13.5

**Comment by gabrieljablonski** [comment]
Can you provide a reproducible example? As you can see in [this example](https://stackblitz.com/edit/stackblitz-starters-33cp35), it doesn't seem to happen in a simple use-case.

Also please try placing the tooltip component inside an element with `position: relative` (as with the second tooltip in the example) and see if that makes a difference.

**Comment by neutron92** [comment]
> Can you provide a reproducible example? As you can see in [this example](https://stackblitz.com/edit/stackblitz-starters-33cp35), it doesn't seem to happen in a simple use-case.
> 
> Also please try placing the tooltip component inside an element with `position: relative` (as with the second tooltip in the example) and see if that makes a difference.

yes but we are using a global Tooltip for whole project i will try to reproduce the bug in codesandbox

**Comment by neutron92** [comment]
> Can you provide a reproducible example? As you can see in [this example](https://stackblitz.com/edit/stackblitz-starters-33cp35), it doesn't seem to happen in a simple use-case.
> 
> Also please try placing the tooltip component inside an element with `position: relative` (as with the second tooltip in the example) and see if that makes a difference.

resolved the problem was max-width in <html> tag
