### ISSUE TITLE
Can't import the named export 'arrow' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by iver003** [ReactTooltip/react-tooltip#1155]
When I want to run the project with "yarn start" I get the following error.

> ./node_modules/react-tooltip/dist/react-tooltip.min.mjs
> Can't import the named export 'arrow' from non EcmaScript module (only default export is available)

Dependencies:
_react 17.0.2
react-tooltip 5.25.2_

**not using webpack**

What should I do?

**Comment by gabrieljablonski** [comment]
I'm guessing you've seen the [troubleshooting section](https://react-tooltip.com/docs/troubleshooting#cant-import-the-named-export-xxx-from-non-ecmascript-module-only-default-export-is-available) on how to fix it with webpack.

We're currently unaware of how to fix with other setups other than with webpack, so you'll have to provide some more info about your environment. Preferably, if you can provide a repo so we can reproduce the issue, it would help a lot.

**Comment by iver003** [comment]
Project:

SSH
git@github.com:iver003/test1-tooltip.git

Https
https://github.com/iver003/test1-tooltip.git

GitHub CLI
gh repo clone iver003/test1-tooltip

**Comment by gabrieljablonski** [comment]
Please set the repo to public. Can't clone it right now.

**Comment by iver003** [comment]
sorry, here I pass again the repo so you can clone it and tell me what to do.

SSH
git@github.com:iver003/testToolTip2.git

Https
https://github.com/iver003/testToolTip2.git

GitHub CLI
gh repo clone iver003/testToolTip2

thanks, @gabrieljablonski

**Comment by iver003** [comment]
> Please set the repo to public. Can't clone it right now.

sorry, here I pass again the repo so you can clone it and tell me what to do.

SSH
[git@github.com](mailto:git@github.com):iver003/testToolTip2.git

Https
https://github.com/iver003/testToolTip2.git

GitHub CLI
gh repo clone iver003/testToolTip2

thanks, @gabrieljablonski

**Comment by gabrieljablonski** [comment]
I'll assume upgrading `react-scripts` worked for you. I've updated the [troubleshooting section](https://react-tooltip.com/docs/troubleshooting#cant-import-the-named-export-xxx-from-non-ecmascript-module-only-default-export-is-available) to include this.

Please reopen with more info if it didn't work.
