### ISSUE TITLE
[BUG] openEvents does not work with "click"

### ISSUE THREAD

**Issue by sbaerviato** [ReactTooltip/react-tooltip#1156]
**Bug description**
I want to open the tooltip on click (for touch devices) and on mouseenter (for desktop devices). Therefore I used the openEvents setting. The tooltip opens on mouseenter as expected, but it does not open on click.

**Version of Package**
v5.26.0

**To Reproduce**
`<Tooltip
			anchorSelect="[data-tooltip='true']"
			variant='dark'
			openEvents={{ click: true, mouseenter: true }}
		/>`

**Comment by gabrieljablonski** [comment]
Have you tried simply not using `openEvents`? Internally the tooltip also watches for `focus` events by default, so it should work fine on both mobile and desktop.

**Comment by sbaerviato** [comment]
> Have you tried simply not using `openEvents`? Internally the tooltip also watches for `focus` events by default (alongside `mouseenter`), so it should work fine on both mobile and desktop.

Yes I did. Unfortunately it also did not work properly in touch mode

**Comment by gabrieljablonski** [comment]
> Unfortunately it also did not work properly in touch mode

Could you please provide a reproducible example and a video of what you mean?

If I try the tooltips on the documentation page, both on my phone, and on the browser with the "device emulation" mode, the tooltip works just fine when I click it (or rather touch it in this case).

https://react-tooltip.com/docs/getting-started
