### ISSUE TITLE
Is is possible to export default middlewares?

### ISSUE THREAD

**Issue by yf-yang** [ReactTooltip/react-tooltip#1157]
I would like to add some constraints to the tooltip and found an issue saying using the middleware would solve that. After that, I found `offset` is no longer working. Then, after read the code, I realize
https://github.com/ReactTooltip/react-tooltip/blob/59bb0e5799bd4e1aea96a92e50ce80945c605cd1/src/utils/compute-positions.ts#L11-L17
The default middleware will be overwritten when the user explicitly uses one, and it is not documented.

I think documentation can be added soon. My question is, is it possible to export all the default middlewares? Alternatively, I am not sure if floating-ui's middleware has some behavior like "the same middleware at the end of an array will override the previous one". If so, would changing the behavior to "extend the default middlewares with user specified middlewares" a good idea?

**Comment by gabrieljablonski** [comment]
> is it possible to export all the default middlewares?

You can just import them from `@floating-ui/dom` directly.

Here's how to setup a tooltip with the default middlewares:

```tsx
import { offset, shift, flip } from '@floating-ui/dom'

<Tooltip
  middlewares=[
    offset(10),
    flip({
      fallbackAxisSideDirection: 'start',
    }),
    shift({ padding: 5 }),
  ]
/>
```

---

> Alternatively, I am not sure if floating-ui's middleware has some behavior like "the same middleware at the end of an array will override the previous one". If so, would changing the behavior to "extend the default middlewares with user specified middlewares" a good idea?

We consider `middlewares` a prop for advanced usage, so we have no plans of extending how we use it with ReactTooltip right now. It is simply a window we provide for customization using the `floating-ui` API.

Depending on what you're trying to achieve, you can find it in detail on the official [`floating-ui` docs](https://floating-ui.com/docs/middleware), or you can post specifics here and we may try to help as much as we can.
