### ISSUE TITLE
The component doesn't show the tooltip when there is a single quote " ' " in the data-tooltip-id and the id passed on the Tooltip component. 

### ISSUE THREAD

**Issue by taranga99** [ReactTooltip/react-tooltip#1166]
I was rendering a list of data in nextjs where there is bunch of titles in a card. I want to show the tooltip when the title of the card is hovered upon. I noticed if the title of the card has a single quote in it Ex: People's Book  the tooltip won't show up. I tried replacing the the string with the single quote with "&quot;" its still the same. Am I being too dumb here idk lol.

**Comment by gabrieljablonski** [comment]
`data-tooltip-id` must be a valid CSS id.

See #1150.

**Comment by taranga99** [comment]
This is wat I did to run it. As, the data-tooltip-id and the id passed on to the tooltip has to be same and does not take a single quote , I took it out of the string and passed it. And the passed the actual string to be rendered as a children.

![image](https://github.com/ReactTooltip/react-tooltip/assets/72241471/cf967a89-75f7-4d64-aeb1-358535b91323)
