### ISSUE TITLE
[BUG] : When ' (single quote) is used any where in the text, the tooltip doesn't open

### ISSUE THREAD

**Issue by parthee11** [ReactTooltip/react-tooltip#1175]
**Bug description**
When ' (single quote) is used any where in the text, the tooltip doesn't open.

**Version of Package**
v5.21.5

**To Reproduce**
- Make sure there is at least one ' added to the content you passing, eg: Animal's Park to reproduce the issue

**Expected behavior**
- This should work similar to other text content

**Screenshots**

- Where we have the text **Hgjvkwlq;'Dlk..** and **Erfdgbqqwerfgjghvkjk'ljhgfchijhgfhchjjilghcjgchvh**, the tooltip is not open  

<img width="249" alt="image" src="https://github.com/ReactTooltip/react-tooltip/assets/55952364/254f36c7-df56-47c9-8674-b53e036b73d1">

**Comment by gabrieljablonski** [comment]
Cannot reproduce this neither on v5.21.5 nor on v5.26.3 (latest version as of writing this).

https://stackblitz.com/edit/vitejs-vite-jblnec?file=src%2FApp.tsx&terminal=dev

What's most likely happening is that you're using the content as the id for the tooltip, which is not allowed on the HTML `id` attribute. Look at the console and you should see a warning message prefixed with `[react-tooltip]`. See #1150 for more details.

If that's the case, you should consider not using a tooltip for each one of your items. See the [Dynamically generated anchor elements](https://react-tooltip.com/docs/troubleshooting#dynamically-generated-anchor-elements) section on the docs for why you shouldn't do it.

Please confirm if it's indeed an issue with the `id`, and we will also add this to the troubleshooting page.

**Comment by parthee11** [comment]
Sure @gabrieljablonski , what you have explained makes sense. Will check once

**Comment by gabrieljablonski** [comment]
Although you should still update your application to use less tooltip elements, as suggested above, there is indeed a bug regarding using `'` in the id (which is allowed according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), only whitespace characters are not allowed)

This is due to how we build the CSS selector string:

```ts
document.querySelectorAll(`[data-tooltip-id='${id}']`)
```

We should escape single quotes from `id`, such that it they're allowed to be used.

**Comment by gabrieljablonski** [comment]
Fixed on [v5.26.4](https://github.com/ReactTooltip/react-tooltip/releases/tag/v5.26.4)
