### ISSUE TITLE
I have set opacity to 1 but I can still see though

### ISSUE THREAD

**Issue by ishandutta2007** [ReactTooltip/react-tooltip#1176]
Just a question, not a bug:

I don't want any transparency at all. 
But my Tooltip text is still mixing with page text in the background making it not properly legible

Following the [docs](https://react-tooltip.com/docs/examples/styling#changing-the-opacity) this is what I did:

```
  <Tooltip id="my-tooltip-opacity" opacity={1.0} />
```

Is there anything more that I have to do ?

PS : 
 - my `react-tooltip` version is `5.26.0`
 - I am on Brave(Chromuim 122)
 - I am on OSX 10.15
 - I tested with lower opacity , it increases transparency for sure, so no issues with prop non-applying or something like that, the issue is why is opacity of 1 not making the background completely opaque.

**Comment by gabrieljablonski** [comment]
Please try a couple things to help narrow it down:

- Does it happen on other browsers? (Firefox, Chrome, Safari, ...)
- Are you able to reproduce it on a fresh project? There might be some extra CSS on your application that's messing with the tooltip. (You can try setting one up really quick on [StackBlitz](https://stackblitz.com/fork/github/vitejs/vite/tree/main/packages/create-vite/template-react-ts?file=index.html&terminal=dev))

If it doesn't happen on a fresh project, we'd need to check out your actual application to give some insight on what might be happening. If it's a private project that you can't share, your best bet would be to try and inspect element on the tooltip and dig through the actual CSS classes on the browser, you might find something there.

Let us know what you find!

**Comment by gabrieljablonski** [comment]
One last thing you could try is overriding the opacity CSS variable directly:

```css
:root {
  --rt-opacity: 1.0;
}
```

Not ideal, but it might work for you.

**Comment by ishandutta2007** [comment]
Thanks @gabrieljablonski  for your quick reply

Actually I managed to debug it myself before I got to see your reply. 
For me `z-index` was the issue:
This solved it:
```
  <Tooltip id="my-tooltip-opacity" opacity={1.0}  style={{ zIndex: "1000" }} />
```
