### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jaysridhar** [ReactTooltip/react-tooltip#1178]
# Check the troubleshooting page before opening an issue!

Issue not mentioned

----

**Bug description**
Attempting to import `TooltipRefProps` gives the message `TooltipRefProps is not exported by ...`

**Version of Package**
5.26.0

**To Reproduce**
import { Tooltip, TooltipRefProps } from 'react-tooltip';

**Expected behavior**
No error messages

**Screenshots**
Not applicable

**Desktop (please complete the following information if possible or delete this section):**
 - OS: Ubuntu
 - Browser Firefox
 - Version Latest (123.0.1)
 - Frameworks react 18.2.0

**Additional context**
None

**Comment by gabrieljablonski** [comment]
Could you please provide a reproducible example?
My guess is that's happening on a non-TypeScript file.

Please try doing this instead:

```js
import { Tooltip } from 'react-tooltip';
import type { TooltipRefProps } from 'react-tooltip';
```

**Comment by jaysridhar** [comment]
This was indeed from using it in a JSX file, not typescript. And I got it working by using just react's `useRef`. In other words, I did not import `TooltipRefProps ` at all.

Thanks for your reply.
