### ISSUE TITLE
[BUG] Element with id 'react-tooltip-base-styles' already exists

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#1185]
### Discussed in https://github.com/ReactTooltip/react-tooltip/discussions/1184

Check the discussion for more info.

**Comment by tonyco97** [comment]
Hi any news?

**Comment by gabrieljablonski** [comment]
Sorry, haven't had the time yet to investigate this further.

**Comment by gabrieljablonski** [comment]
Sorry for the delay on getting back to this.

@AYColumbia I tried reproducing the warning with the repo you [provided here](https://github.com/ReactTooltip/react-tooltip/discussions/1184#discussioncomment-9112178), but it doesn't happen for me, and the tooltip works normally.

![image](https://github.com/ReactTooltip/react-tooltip/assets/21102974/26b45393-5675-4af2-b9e8-690085ceac77)

Could you provide some more info on this? I'll be able to follow up more promptly now.

---

@tonyco97 can you provide some info on how you've experienced this issue? Can you try cloning @AYColumbia's repo and seeing if it happens there for you as well?

Here's the repo: https://github.com/AYColumbia/test-tooltip-app

Running `npm install` followed by `npm run startwp` should get you there.

**Comment by Ti-tanium** [comment]
Any solutions to resolve this?

I'm having the same issue with `react-tooltip@5.27.0`.

My project is using react-tooltip, and I have another package that's also using react-tooltip. And I think both of them are trying to inject the react-tooltip base and core style into the html, which causes this warning in console.

I'm seeing 1000+ of them in my console, which is really annoying. Any suggestions?

**Comment by gabrieljablonski** [comment]
@Ti-tanium try using `disableStyleInjection='core'` (details [here](https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css)) on the tooltip on your main project. Since you have another package using the tooltip, the styles should still be applied applied.

**Comment by Ti-tanium** [comment]
> @Ti-tanium try using `disableStyleInjection='core'` (details [here](https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css)) on the tooltip on your main project. Since you have another package using the tooltip, the styles should still be applied.

Is there a way to disable the injection globally for react-tooltip? Adding the `disableStyleInjection` for every tooltip is very annoying. Since I might have hundreds of them.

**Comment by Ti-tanium** [comment]
<img width="718" alt="Screen Shot 2024-06-28 at 2 25 13 PM" src="https://github.com/ReactTooltip/react-tooltip/assets/23275363/ad0dc4f2-c021-4a6a-ab70-6365b5580a08">

Why do we need this warning? If the style is already injected, why not just skip the injection without giving any warning? Also the check for production if statement is not really working for me (we are probably using `prod` as the env variable), I'm seeing thousands of warnings in production as well

**Comment by gabrieljablonski** [comment]
>Is there a way to disable the injection globally for react-tooltip?

There's a way described on [the docs](https://react-tooltip.com/docs/examples/styling#environment-variables) with environment variables, but that's deprecated. I suggest writing a simple wrapper that sets `disableStyleInjection`, and just passes through all other tooltip props. Then, you just update the imports from `react-tooltip` to use your wrapper instead.

>Why do we need this warning? If the style is already injected, why not just skip the injection without giving any warning?

We use that as a warning we might be doing something wrong with style injection. We might need to revise the logic, since we hadn't considered your use case, in which you use a package that also uses the tooltip internally.

>Also the check for production if statement is not really working for me (we are probably using `prod` as the env variable)

As you can see on the code, we only check for the `production` value.

**Comment by AYColumbia** [comment]
> Sorry for the delay on getting back to this.
> 
> @AYColumbia I tried reproducing the warning with the repo you [provided here](https://github.com/ReactTooltip/react-tooltip/discussions/1184#discussioncomment-9112178), but it doesn't happen for me, and the tooltip works normally.
...
> Could you provide some more info on this? I'll be able to follow up more promptly now.
Hi, I tried some different adjustments the test project but have been unable to reproduce as well.  It does still happen with my actual project though so will have to read through the new posts and see if there's anything else I can try.  The only thing I can think of is that I may have missed a package that's also loading tooltip that is in my actual project but NOT in the test project.  I tried to run that down but haven't found anything yet.

**Comment by tonyco97** [comment]
> Sorry for the delay on getting back to this.
> 
> @AYColumbia I tried reproducing the warning with the repo you [provided here](https://github.com/ReactTooltip/react-tooltip/discussions/1184#discussioncomment-9112178), but it doesn't happen for me, and the tooltip works normally.
> 
> ![image](https://private-user-images.githubusercontent.com/21102974/342509097-26b45393-5675-4af2-b9e8-690085ceac77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTkxNTYsIm5iZiI6MTcxOTgxODg1NiwicGF0aCI6Ii8yMTEwMjk3NC8zNDI1MDkwOTctMjZiNDUzOTMtNTY3NS00YWYyLWI5ZTgtNjkwMDg1Y2VhYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjNjNDdlNTY0MmIwZDZlYmI0MDhiMGUzYTAwZTFkODE4NTNjZTFhMDJmN2FmM2JjNjY1ZjUwYjZjMjlmNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aacmcEWKk_Vuy5CTbVQUq13ttj8BsBruG3Vcpb1UwoE)
> 
> Could you provide some more info on this? I'll be able to follow up more promptly now.
> 
> @tonyco97 can you provide some info on how you've experienced this issue? Can you try cloning @AYColumbia's repo and seeing if it happens there for you as well?
> 
> Here's the repo: https://github.com/AYColumbia/test-tooltip-app
> 
> Running `npm install` followed by `npm run startwp` should get you there.

I' ve tried test-tooltip-app and the error does not appear here. In my case, i've a page with react-tooltip which imports a component also containing react tooltip

**Comment by AYColumbia** [comment]
I updated my project with multiple components that use react-tooltip and still can't duplicate the issue.  It's bewildering.

**Comment by tonyco97** [comment]
> I updated my project with multiple components that use react-tooltip and still can't duplicate the issue. It's bewildering.

Try to apply some style to both tooltip in both project, one in your project and the in other one in the component that you import in the first one

**Comment by gabrieljablonski** [comment]
We might just remove the warning, since it doesn't seem to help much here.

@tonyco97 please try the beta release `react-tooltip@5.27.0-beta.1203.rc.0`

The warning should be completely gone with that version.

If we merge it, I'll let you know when we push an official release, and close this issue.

**Comment by AYColumbia** [comment]
> > I updated my project with multiple components that use react-tooltip and still can't duplicate the issue. It's bewildering.
> 
> Try to apply some style to both tooltip in both project, one in your project and the in other one in the component that you import in the first one
Thanks for the tip.  I tried what you recommend but still no warnings.  I pushed all the changes to the repo so feel free to grab it with those changes and see if I missed anything you would and try it and let us know.  It may be moot at this point since it looks like the warnings are to be removed.

**Comment by AYColumbia** [comment]
> We might just remove the warning, since it doesn't seem to help much here.
> 
> @tonyco97 please try the beta release `react-tooltip@5.27.0-beta.1203.rc.0`
> 
> The warning should be completely gone with that version.
> 
> If we merge it, I'll let you know when we push an official release, and close this issue.

I applied the beta release to my actual project to test it and the warnings are gone.  I'll just revert back until you do an official release.  Thanks much.

**Comment by gabrieljablonski** [comment]
Official release with the fix `react-tooltip@5.27.1`
