### ISSUE TITLE
The tooltip is hidden by the parent tag using overflow-auto

### ISSUE THREAD

**Issue by Cudtad** [ReactTooltip/react-tooltip#1188]
I want to tooltip the child tag, but the parent tag is using overflow-auto, causing the phenomenon below. What do I need to do to fix this problem? (This issue only appears on websites accessed by mobile)

![IMG_1069](https://github.com/ReactTooltip/react-tooltip/assets/119325164/0c907ae3-e7b3-4936-8f9a-efc28ffcc007)

**Comment by gabrieljablonski** [comment]
Sorry for the late response. Missed the notification for this issue.

You have two options:

1. Use the [`posititionStrategy`](https://react-tooltip.com/docs/options#:~:text=for%20more%20customization-,positionStrategy,-string) prop on the tooltip.

```jsx
<Tooltip positionStrategy="fixed" />
```

2. Move the tooltip component outside of your `overflow` parent. This shouldn't affect the tooltip positioning.

**Comment by gabrieljablonski** [comment]
Feel free to reopen with more information.

**Comment by nibin-quintet** [comment]
Hi, @gabrieljablonski  can we please reopen this issue?

Right now, the tooltip only works properly with the direct parent element. If any outer div has overflow: hidden, the tooltip gets cut off and the position doesn’t work correctly.

It would be great if the tooltip could render outside the parent or have an option to handle this case.

Thanks!

**Comment by danielbarion** [comment]
@nibin-quintet can you please provide a reproducible example?

You can use CodeSandbox for that, example: https://codesandbox.io/p/sandbox/gallant-leftpad-8kvtn7
