### ISSUE TITLE
After changing the arrow position, there are already resolutions where the arrow does not appear in the right position (Any workaround handle this problem?)

### ISSUE THREAD

**Issue by Gellipapa** [ReactTooltip/react-tooltip#1191]
Hi! I'm using this really cool tooltip and since I'm using a custom style the default arrow position wasn't right because it would hang in the box if I didn't have the background color set, so I thought I'd rewrite it in CSS and it worked, but there are some resolutions where it slips a few pixels. 

Could this be fixed somehow in the current tooltip, I assume it slips because of the internal calculation, but I can't override that. 

I made a stackblitz where you can test it, in the picture above you can see that the arrow is out of alignment, in the second picture you can see the correct expected look. 

However, this only occurs at uncertain resolutions, so it is interesting. 

https://stackblitz.com/edit/vitejs-vite-bdqp7e?file=src%2FApp.tsx

![image](https://github.com/ReactTooltip/react-tooltip/assets/22717950/eaff33c2-dbef-4e93-aa9d-4e787149282a)
![image](https://github.com/ReactTooltip/react-tooltip/assets/22717950/1c3f0078-eeb1-42c2-a3fa-dfe78f72d267)

Thanks for your reply in advance.

**Comment by gabrieljablonski** [comment]
The issue you're experiencing is due to setting a `border` attribute directly through the CSS. This breaks the position calculations.

You should use the [`border` prop](https://react-tooltip.com/docs/examples/styling#changing-the-border) on the `Tooltip` component:

```jsx
<Tooltip border="1px solid black" />
```

---

Btw, not sure if you're doing the same thing on your project as you've done on the sandbox you've linked, but copying the `tooltip.css` from the `dist/` folder is not recommended, since those auto-generated class names are likely to change on another version.

If you really need to disable the style injection, follow [the steps here](https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css)(mainly about importing the correct CSS file).

But from what I can tell, you could probably achieve your custom style by simply overriding the existing styles. You can probably do that with just the `className` and `classNameArrow` tooltip props (but remember not to change `border` or `opacity` there, use the component props for those).

**Comment by Gellipapa** [comment]
> The issue you're experiencing is due to setting a `border` attribute directly through the CSS. This breaks the position calculations.
> 
> You should use the [`border` prop](https://react-tooltip.com/docs/examples/styling#changing-the-border) on the `Tooltip` component:
> 
> ```js
> <Tooltip border="1px solid black" />
> ```
> 
> Btw, not sure if you're doing the same thing on your project as you've done on the sandbox you've linked, but copying the `tooltip.css` from the `dist/` folder is not recommended, since those auto-generated class names are likely to change on another version.
> 
> If you really need to disable the style injection, follow [the steps here](https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css) (mainly about importing the correct CSS file).
> 
> But from what I can tell, you could probably achieve your custom style by simply overriding the existing styles. You can probably do that with just the `className` and `classNameArrow` tooltip props (but remember not to change `border` or `opacity` there, use the component props for those).

Hi! Thank you for the detailed reply, it is now clear why it was wrongly positioned. 

I still don't understand the classNameArrow part, is this an internal prop to get the style of the arrow? I searched the documentation and couldn't find such a part.

Thanks for the reply in advance, I appreciate this react-tooltip package.

**Comment by gabrieljablonski** [comment]
> I still don't understand the classNameArrow part, is this an internal prop to get the style of the arrow?

It's on the ["options" page on the docs](https://react-tooltip.com/docs/options#available-props) (third one from the top on the "Available props" section).

Usually library components expose a `className` prop for each "sub-component" (HTML elements) so you have more control over the styling. In this case, the tooltip has two "sub-components", the tooltip itself, and the arrow.

That way, you can do something like this:

### JSX

```jsx
<Tooltip className="my-tooltip-styles" classNameArrow="my-tooltip-arrow-styles" />
```

### CSS

```css
.my-tooltip-styles {
  background-color: ...;
  border-radius: ...;
}

.my-tooltip-arrow-styles {
  background-color: ...;
}
```

---

That said, you don't need to use `className` and `classNameArrow`. You can use the default selectors `.react-tooltip` and `.react-tooltip-arrow`, which we already set on the correct elements internally.

```css
.react-tooltip {
  background-color: ...;
  border-radius: ...;
}

.react-tooltip-arrow {
  background-color: ...;
}
```

**Comment by Gellipapa** [comment]
@gabrieljablonski Ohh nice, thanks for your help.

**Comment by Gellipapa** [comment]
@gabrieljablonski Hi! 

It works as you wrote in my example, but in the actual place where I use it, the arrow position is still wrong.

I deleted the entire cache, rebuilt, installed the latest version, turned off all custom styles and the default style still has this problem.

Do you have any more tips I should try, it's strange because it works at some point, so it's not permanent and if it's wrong and then I hover over it again it'll fix it at some point.

I deleted all the custom css so I actually use the original version, what I noticed after each build is that the class you wrote will still regenerate. 

Could this be related? 

Thanks for your reply in advance, I just can't figure out what the problem could be because I couldn't reproduce stackblitzen, but maybe you have some idea what the problem could be.

Bad
![image](https://github.com/ReactTooltip/react-tooltip/assets/22717950/2825762b-637d-4dbb-9b35-8337e37ff00b)

Good
![image](https://github.com/ReactTooltip/react-tooltip/assets/22717950/56732bf0-fa57-4952-b24c-cb8fcba96980)

**Comment by gabrieljablonski** [comment]
> I deleted all the custom css so I actually use the original version, what I noticed after each build is that the class you wrote will still regenerate.

I don't understand what you mean by this. Where is the class "regenerating"?

From your screenshots, you're clearly applying some custom styles. How are you doing that?

Please provide a snippet of your `.css` file and of your JSX where you're using the Tooltip component. Event better if you can provide a sample git repo with the issue reproducible.

**Comment by Gellipapa** [comment]
@gabrieljablonski Hi! https://stackblitz.com/edit/vitejs-vite-bdqp7e?file=src%2FApp.tsx 

This is specifically how the prod code is written, but for some reason the arrow positioning is wrong. I have not been able to reproduce the problem in stackblitz, but as I test I see that when I resize the page it is sometimes right and sometimes wrong, so it still seems to me that something is messing up the positioning of the arrows, although unfortunately I have not been able to reproduce the problem in stackblitz, BUT maybe you can tell me something about this that I have experienced. 

Really all where I deleted the css from. I don't use the border property anywhere in the css and it's completely random when the arrow appears on the right and when it doesn't. 

Thanks for your reply in advance.

**Comment by gabrieljablonski** [comment]
Sorry for the delayed response. From the sample code you've sent, I technically can reproduce it, but only if I zoom out a lot.

![image](https://github.com/ReactTooltip/react-tooltip/assets/21102974/557868f7-822e-4ca4-949b-7adece5711b6)

Unfortunately, I don't think there's much that can be improved here. When you're working with zoomed in/zoomed out pages, the browser has to round some numbers when calculating how to render the elements.

Especially when zooming out, sometimes the calculation rounds up, when it should've rounded down, for better "visual fidelity".

We *could* add a "correction factor" to the arrow position based on the level of zoom on the page (for instance, moving the arrow 1 extra pixel down at 50% page zoom fixes it for me), but that doesn't seem worth it to me.

This is something we just kinda have to live with for the sake of simplicity: some styles look weird when zooming in/out. And that's ok, >99% of your users will never notice this.

---

Feel free to comment with anything else you'd like to add, but I don't think there's much we can improve here.

**Comment by Gellipapa** [comment]
@gabrieljablonski Hi!
Thanks, I waited for your answer, but I didn't close it, but we decided to use it this way, thank you very much for your research to solve the problem. 

It will be absolutely fine for us, thanks again for your help and for making this library.
