### ISSUE TITLE
Tooltip not working properly adding CSP 

### ISSUE THREAD

**Issue by z-akashGupta** [ReactTooltip/react-tooltip#1192]
All the styling got lost after adding strict Content Security policy to the project. Is there any prop to fix that 

My package version is **react-tooltip@3.11.1** and cannot update it

**Comment by danielbarion** [comment]
Hi @z-akashGupta, we only maintain the versions >=5.

Version below 5 was built but other maintainers that are not active anymore. Also I strongly recommend you to upgrade the package as we did a lot of improvements on v5.

Thanks!
