### ISSUE TITLE
ReactTooltip.hide() not working after upgrade, what is the alternative in latest version?

### ISSUE THREAD

**Issue by jackvik** [ReactTooltip/react-tooltip#1197]
I am upgrading react-tooltip library and earlier we are using ReactTooltip.hide(), but not able to find alternative in latest version.

**Comment by gabrieljablonski** [comment]
The closest to `ReactTooltip.hide()` we have on v5 is the "imperative mode". See the docs for examples.

https://react-tooltip.com/docs/examples/imperative-mode

**Comment by gabrieljablonski** [comment]
Feel free to open a new issue with more info about your use case if you have any trouble getting the "imperative mode" to work.
