### ISSUE TITLE
[BUG] Anchor tooltip to support content of varying size

### ISSUE THREAD

**Issue by joqim** [ReactTooltip/react-tooltip#1208]
# Check the troubleshooting page before opening an issue!

Make sure your problem isn't already covered at the troubleshooting page: https://react-tooltip.com/docs/troubleshooting

----

**Bug description**
Tooltip is being offset when content is dynamically being updated. Tooltip itself is not being anchored.

**Version of Package**
vX.X.X

**To Reproduce**
Update content dynamically using React state and observe that tooltip is being repositioned.

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/e7cf7f9a-8e44-40f7-b5be-15b2d98f661c

**Desktop (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Smartphone (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Additional context**

**Comment by danielbarion** [comment]
Reproducible link: https://codesandbox.io/s/sharp-glitter-w9vn2x?file=/src/App.js

**Comment by danielbarion** [comment]
@joqim the fix: https://codesandbox.io/p/sandbox/sharp-glitter-w9vn2x

![image](https://github.com/user-attachments/assets/3eff5831-ebb1-4f52-9ce7-251238e673f4)
![image](https://github.com/user-attachments/assets/b24cbbf4-1d3c-4231-91a5-eeed420af3cc)
![image](https://github.com/user-attachments/assets/4af7483e-9dcd-459d-bbb7-9c218b52dd49)
