### ISSUE TITLE
[BUG] Logo colors not appropriate for dark mode.

### ISSUE THREAD

**Issue by rahulharpal1603** [ReactTooltip/react-tooltip#1209]
# GitHub and Algolia Logo blend into the dark background.

----

**Bug description**

When we switch to dark mode, the GitHub and Algolia logos retain their previous colours only. That is why, it makes it difficult to see them on the webpage.

**To Reproduce**

Visit the home page: https://react-tooltip.com/ and change the theme to dark mode.

**Expected behaviour**

GitHub and Algolia's logos should change to a lighter version when switched to dark mode.

**Screenshots**

![image](https://github.com/user-attachments/assets/47a378e5-93fa-4acb-b4bc-7169d2a5c1b3)
![image](https://github.com/user-attachments/assets/7bd8978d-4913-4c61-8722-cf8e66910497)

**Comment by rahulharpal1603** [comment]
@gabrieljablonski, can I take up this issue and fix it?

**Comment by gabrieljablonski** [comment]
@rahulharpal1603 go for it
