### ISSUE TITLE
[DOCS] Improve docs footer layout

### ISSUE THREAD

**Issue by ashiii1** [ReactTooltip/react-tooltip#1216]
There is empty space at right side of footer, making the layout unbalanced.

![Screenshot 2024-07-27 135015](https://github.com/user-attachments/assets/5613d06a-39d8-4025-b977-4e3aa536af04)

Keep the "Get Started" section on the left side.
Move the "More GitHub" section to the right side to balance the layout.

**Comment by gabrieljablonski** [comment]
This is not a big deal IMO. Ideally, we should have more sections on the footer (3 or 4) so it would naturally look better, without messing with alignments.

Feel free to give suggestions.
