### ISSUE TITLE
TreeMap - Hover state based on depth

### ISSUE THREAD

**Issue by efitzkiwi** [ReactTooltip/react-tooltip#1217]
I would like to know if it is possible to set a hover state based on depth. For example, I would like the categories in an official demo to have a stroke hover effect when hovered:
https://www.amcharts.com/demos/simple-treemap/
Something like: when hovering the blue container, you can see the top left category has a stroke effect
![image](https://github.com/user-attachments/assets/fbe765dc-3865-4997-bbf6-497d27f2e044)

I have tried to implement depth rules based on 
```
        seriesRef.bullets.push(function (root, _, dataItem) {
            var depth = dataItem.get("depth");

            if (depth == 1) {
                  // todo set stroke for this container?? how
                  // dataItem.component.states.create("hover", {})
            }
        });
```
But I am unsure/unable to get the sprite/container associated at this depth.

**Comment by gabrieljablonski** [comment]
Unless I'm misunderstanding what you're asking, your question is not related to ReactTooltip.

You might be looking for https://github.com/amcharts/amcharts5

If your question is actually about ReactTooltip, please elaborate, since it is unclear how it relates to this project.

**Comment by efitzkiwi** [comment]
> Unless I'm misunderstanding what you're asking, your question is not related to ReactTooltip.
> 
> You might be looking for https://github.com/amcharts/amcharts5
> 
> If your question is actually about ReactTooltip, please elaborate, since it is unclear how it relates to this project.

My apologies, I had too many tabs open and posted on the wrong github.
