### ISSUE TITLE
Tooltip is not shown once it is deployed to Vercel

### ISSUE THREAD

**Issue by tech02223** [ReactTooltip/react-tooltip#1221]
Hello.
Currently I'm working on Next.js, and built my website.
I used react-tooltip module to display a tooltip, and it works well on localhost.
But I noticed that tooltip is not shown after the website is deployed.
I'm not sure what I did incorrectly.

**Comment by gabrieljablonski** [comment]
We have two sections on our troubleshooting page about possible issues with Next.js:

1. [Next.js `TypeError: f is not a function`](https://react-tooltip.com/docs/troubleshooting#nextjs-typeerror-f-is-not-a-function)
2. [Next.js `"use client"` error](https://react-tooltip.com/docs/troubleshooting#nextjs-use-client-error)


If your issue does not relate to either of these situations, please try to give us some more information on what's exactly happening there.

**Comment by tech02223** [comment]
I don't think my issue is not related to above issues. It works correctly on localhost. I can see the tooltips.
But I cannot see those tooltips if I deploy my website to Vercel. It is hosted in static mode.

**Comment by gabrieljablonski** [comment]
Is your deployed project publicly available? If yes, please share so I can take a look.

If not, you'll need to do some investigation and see if you can find out anything to help us figure out the issue.

Best I can think of right now is to check the browser console in production and see if anything shows up there. Also check the console on localhost to see if there's anything that might get suppressed on production.

**Comment by danielbarion** [comment]
@tech02223 is the tooltip working on your project on both commands? `yarn dev`, `yarn build && yarn start`

I'm asking because of the behavior of Next.js + React on development mode is different from production build.

**Comment by berejznoy** [comment]
I have same problem. It works well wher yarn dev but not working after yarn build
Uncaught (in promise) TypeError: w is not a function

**Comment by danielbarion** [comment]
@berejznoy @tech02223 can you guys please create a reproducible example with a fresh Next.js project? I'll take a look when you guys share it

**Comment by Emroni** [comment]
I had the same problem. Tried disabling webpack optimization minimizing in `next.config.js` to see the error, but that actually _fixed_ the issue. What solved it was upgrading next package to 13.3.0 as shown in the first [link](https://react-tooltip.com/docs/troubleshooting#nextjs-typeerror-f-is-not-a-function) commented by @gabrieljablonski.
