### ISSUE TITLE
[BUG] combination of openOnClick & globalCloseEvents with clickOutsideAnchor does not close on click outside anchor

### ISSUE THREAD

**Issue by JMLexLExter** [ReactTooltip/react-tooltip#1228]
**Bug description**
I have a Tooltip component that looks like this:

![image](https://github.com/user-attachments/assets/fcc4ad0c-1bed-4591-891d-210109729365)

Tooltip component that has both the `openOnClick` (or `openEvents={{ click: true }}` ) and `globalCloseEvents={{ clickOutsideAnchor: true }}` props, does not combine their behavior. 

**Version of Package**
v5.28.0

**To Reproduce**
Create a Tooltip with both `openOnClick `& `globalCloseEvents`.

**Expected behavior**
I expect the the tooltip to be shown on click on the #anchorSelect anchor and to be closed on another click. I also expect to close the tooltip on click outside the Tooltip. Instead the `clickOutsideAnchor` doesn't work and clicking outside the #anchorSelect does not work

**Screenshots**

**Additional context**
    "react": "^18.2.0",
    "styled-components": "^5.3.6",
    "typescript": "^5.5.4"

**Comment by richhapal** [comment]
Hi @JMLexLExter you can use setIsOpen function that will trigger during clickOutsideAnchor.
