### ISSUE TITLE
[BUG] Tooltip fails to hide in certain scenarios

### ISSUE THREAD

**Issue by jack3898** [ReactTooltip/react-tooltip#1230]
**Bug description**
In specific scenarios, hard to reproduce, the tooltip persists on the screen and does not hide. I have been able to replicate this issue in the provided CodeSandbox in the readme. See below for a video of reproduction.

**Version of Package**
Any v4 or v5. I reproduced in the CodeSandbox running 5.18.1.

**To Reproduce**
Move the mouse cursor very fast in an out. In uncommon situations, the tooltip persists.
While this may seem like it's infrequent enough, on slower machines this becomes more common to reproduce with normal use and sometimes catches one by surprise.

**Expected behavior**
100% of the time, when the mouse cursor moves away from the element the tooltip should disappear.

**Desktop (please complete the following information if possible or delete this section):**
 - OS: All platforms (tested on Windows and Mac with Apple Silicon)
 - Browser: Tested on Firefox, Edge and Chrome
 - Version Chrome 129 and Firefox 131
 - Frameworks: Vanilla React 18 with Webpack

**Additional context**
Here is a video, to reproduce in the CodeSandbox, I move my mouse cursor very fast.

My hunch is this has something to do with the event capturing for when the mouse leaves the element that has the tooltip.

https://github.com/user-attachments/assets/3e99fd73-1e82-4f28-8a59-0cb0de456406

**Comment by gabrieljablonski** [comment]
We've fixed many issues since 5.18

Please upgrade and check again.

**Comment by jack3898** [comment]
Ah I just tested it, and it works like a charm. Thanks a lot, I will close this then as it is no longer an issue!
