### ISSUE TITLE
Compiling Production Mode Using Webpack 5

### ISSUE THREAD

**Issue by AYColumbia** [ReactTooltip/react-tooltip#1232]
Are you able to compile successfully in production mode? I have no issues in development mode, but once I switch to production, my project emits a parse error.  I've spent hours narrowing it down to react-tooltip.  I basically commented out my code in my components and returning just a basic div element and then uncommented the imports one by one until the compilation failed.

My normal import: `import { Tooltip } from 'react-tooltip';` produces the error
```
ERROR in ./src/index.js + 42 modules
Unexpected end of JSON input
```
I tried to import directly from the .cjs file, i.e., `import { Tooltip } from '../node_modules/react-tooltip/dist/react-tooltip.cjs';` which produces the error
```
ERROR in ./node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js + 3 modules
Unexpected end of JSON input
```
Versions:
+-- react-tooltip@5.28.0
+-- webpack-cli@5.1.4
+-- webpack-dev-server@5.1.0
+-- webpack-merge@6.0.1
+-- webpack@5.96.1

Let me know if there's other info needed.  Thanks.

**Comment by AYColumbia** [comment]
I was able to reproduce the issue with a simple react app.  I created a repo for it to see if the same happens to anyone who wants to try it out please.  The development build should succeed and production should fail with the "Unexpected..." error.

[react-test-app](https://github.com/AYColumbia/react-test-app)

**Comment by AYColumbia** [comment]
Am closing this issue as it looks like it's not specific react-tooltip.  I found an issue that points to node 23.2 as the culprit.

[Node 23.2 breaks webpack build (date-fns) Unexpected end of JSON input](https://github.com/webpack/webpack/issues/18963#issue-2652078145)

**Comment by danielbarion** [comment]
Thanks for the information @AYColumbia
