### ISSUE TITLE
Is there a way to position the tooltip's x-axis at the mouse's x-axis?

### ISSUE THREAD

**Issue by amh6281** [ReactTooltip/react-tooltip#1234]
I want to position the tooltip below the cursor on the x-axis, but using the position property requires a value for the y-axis as well, which is causing an issue. Is there a way to keep the existing y-value and only specify the x-axis position as desired?

Here is the functionality I want.
![스크린샷 2024-11-20 오후 5 10 33](https://github.com/user-attachments/assets/418c4b65-209a-4199-9ffe-0603155c6f3f)

When using the position property, the y-axis must also be calculated, but due to the nature of the project, the y-axis cannot be considered. This is because the y-axis has a variable characteristic that extends below the scroll, rather than a fixed height as in the example above. I have tried to implement it using the left property without using the position property, but when moving to the edge of the monitor, the placement remains bottom-start instead of bottom-end. Is there a solution for this?

For example, I need a way to do something like position={...position, x: customX}.

**Comment by gabrieljablonski** [comment]
Unfortunately, right now the `position` prop is "all or nothing". That is, you must provide `x` AND `y`.

If you're willing and have the time to do it, you can submit a PR to update the internal [`updateTooltipPosition()`](https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/Tooltip/Tooltip.tsx#L402-L457) function, and merge the `position` prop with the result from the `computeTooltipPosition()` function.

---

That being said, I'm not sure it solves your problem, since you've said this:

> but when moving to the edge of the monitor, the placement remains bottom-start instead of bottom-end. Is there a solution for this?

Could you elaborate on what you're seeing? From your description, this seems like an issue with the default tooltip behavior of avoiding overflowing the page.

To test is that's the case, try overriding the `middlewares` prop.

The sample code below shows the default configuration, but with `shift()` and `flip()` commented out, which I believe are the middlewares causing this last issue you've described. Try putting them back in one at a time and see what happens.

```tsx
import { offset, shift, flip } from '@floating-ui/dom'

<Tooltip
  middlewares={[
    offset(10),
    // flip({ fallbackAxisSideDirection: 'start' }),
    // shift({ padding: 5 }),
  ]}
/>
```

You can read more about this in the [`floating-ui` docs](https://floating-ui.com/docs/middleware). Our tooltip component uses it internally.

**Comment by amh6281** [comment]
@gabrieljablonski
![스크린샷 2024-11-21 오후 1 08 18](https://github.com/user-attachments/assets/6ed4c7fe-3c38-4dfa-8d1b-308fed02cc8b)
```
<Tooltip
	id="event-tooltip"
	positionStrategy="fixed"
	clickable
	border="1px solid #c7c7c7"
	setIsOpen={() => {}}
	style={{ transform: `translateX(${mouseX - 19}px)` }}
/>
```
Currently, I am calculating the x-position of an element when the mouse hovers over it and using this to move the tooltip along the x-axis with the translateX property (the left property does not apply). In this case, is there a way to ensure the tooltip does not go off the screen but instead aligns to the bottom-end? The flip and shift properties from floating-ui are not being applied.

**Comment by amh6281** [comment]
> Unfortunately, right now the `position` prop is "all or nothing". That is, you must provide `x` AND `y`.
> 
> If you're willing and have the time to do it, you can submit a PR to update the internal [`updateTooltipPosition()`](https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/Tooltip/Tooltip.tsx#L402-L457) function, and merge the `position` prop with the result from the `computeTooltipPosition()` function.
> 
> That being said, I'm not sure it solves your problem, since you've said this:
> 
> > but when moving to the edge of the monitor, the placement remains bottom-start instead of bottom-end. Is there a solution for this?
> 
> Could you elaborate on what you're seeing? From your description, this seems like an issue with the default tooltip behavior of avoiding overflowing the page.
> 
> To test is that's the case, try overriding the `middlewares` prop.
> 
> The sample code below shows the default configuration, but with `shift()` and `flip()` commented out, which I believe are the middlewares causing this last issue you've described. Try removing them one at a time and see what happens.
> 
> ```tsx
> import { offset, shift, flip } from '@floating-ui/dom'
> 
> <Tooltip
>   middlewares={[
>     offset(10),
>     // flip({ fallbackAxisSideDirection: 'start' }),
>     // shift({ padding: 5 }),
>   ]}
> />
> ```
> 
> You can read more about this in the [`floating-ui` docs](https://floating-ui.com/docs/middleware). Our tooltip component uses it internally.



> Unfortunately, right now the `position` prop is "all or nothing". That is, you must provide `x` AND `y`.
> 
> If you're willing and have the time to do it, you can submit a PR to update the internal [`updateTooltipPosition()`](https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/Tooltip/Tooltip.tsx#L402-L457) function, and merge the `position` prop with the result from the `computeTooltipPosition()` function.
> 
> That being said, I'm not sure it solves your problem, since you've said this:
> 
> > but when moving to the edge of the monitor, the placement remains bottom-start instead of bottom-end. Is there a solution for this?
> 
> Could you elaborate on what you're seeing? From your description, this seems like an issue with the default tooltip behavior of avoiding overflowing the page.
> 
> To test is that's the case, try overriding the `middlewares` prop.
> 
> The sample code below shows the default configuration, but with `shift()` and `flip()` commented out, which I believe are the middlewares causing this last issue you've described. Try removing them one at a time and see what happens.
> 
> ```tsx
> import { offset, shift, flip } from '@floating-ui/dom'
> 
> <Tooltip
>   middlewares={[
>     offset(10),
>     // flip({ fallbackAxisSideDirection: 'start' }),
>     // shift({ padding: 5 }),
>   ]}
> />
> ```
> 
> You can read more about this in the [`floating-ui` docs](https://floating-ui.com/docs/middleware). Our tooltip component uses it internally.

@gabrieljablonski 
![스크린샷 2024-11-21 오후 1 08 18](https://github.com/user-attachments/assets/6ed4c7fe-3c38-4dfa-8d1b-308fed02cc8b)
```
<Tooltip
	id="event-tooltip"
	positionStrategy="fixed"
	clickable
	border="1px solid #c7c7c7"
	setIsOpen={() => {}}
	style={{ transform: `translateX(${mouseX - 19}px)` }}
/>
```
Currently, I am calculating the x-position of an element when the mouse hovers over it and using this to move the tooltip along the x-axis with the translateX property (the left property does not apply). In this case, is there a way to ensure the tooltip does not go off the screen but instead aligns to the bottom-end? The flip and shift properties from floating-ui are not being applied.
