### ISSUE TITLE
Tooltip tip spaces out sometimes

### ISSUE THREAD

**Issue by abologna-r7** [ReactTooltip/react-tooltip#196]
Using the latest release(v3.1.8), I noticed that when moving the cursor on a data-tip enabled element, there's a small gap between the tip and the content box.

<img width="91" alt="screen shot 2016-09-22 at 2 29 03 pm" src="https://cloud.githubusercontent.com/assets/8812471/18763060/521a36f0-80d1-11e6-81fa-0b63f45e42f2.png">

Update:
The element I'm using the tooltip on is a `<span>` DOM element, with text inside it.

**Comment by abologna-r7** [comment]
Adding gif:

![bug](https://cloud.githubusercontent.com/assets/8812471/18763195/d79ab28c-80d1-11e6-90d0-ac673032d8ba.gif)

**Comment by ViniciusTavares** [comment]
Is there any solution for this issue?   

I'm getting the same problem using react-tooltips on table heads.

**Comment by szabolcsx** [comment]
I am getting the same behavior. 

This is the relevant code snippet:
``` JSX
<span data-tip={cell.element.shortDescription}>{cell.element.label}</span>
<ReactTooltip effect="float" place="right" type="dark" />
```

Sometimes it's aligning correctly, based on the cursor position. I'm using the 3.2.7 version.

**Comment by DanielVertlib** [comment]
any solutions for this issue?

**Comment by szabolcsx** [comment]
I eventually had to use another library because I wasn't able to fix the issue.

**Comment by DanielVertlib** [comment]
cool. could i ask which library you used, unless the owner replies with a fix?

**Comment by Rogger794** [comment]
Hi guys, could someone tried the last release? I guess this issue is gone.

**Comment by oliviervanbulck** [comment]
> 
> 
> Hi guys, could someone tried the last release? I guess this issue is gone.

I had the same problem and with the latest version the problem was fixed without changing code. Thanks!

**Comment by danielbarion** [comment]
Hi guys, closing due to age, we did some publishes recently, please try the latest one and if necessary, open a new issue, thanks!
