### ISSUE TITLE
Bound tooltip to container?

### ISSUE THREAD

**Issue by sebastientromp** [ReactTooltip/react-tooltip#241]
Hello,

Is there an option to make sure that the tooltip doesn't overflow out of the screen / container, and is instead moved around to make sure everything fits in the screen?

On this example: http://codepen.io/anon/pen/XNvzWK I would expect the tooltip to be displayed to the right instead, for instance.

Thanks!

**Comment by sebastientromp** [comment]
It looks like a duplicate of https://github.com/wwayne/react-tooltip/issues/7, but it looks like the issue still persists at least in some cases. Or am I missing something?

**Comment by Ardhimas** [comment]
You're correct, there was a commit 5aae0235d46dd97310237808ad2432813cff1a44 to fix the problem but it doesn't appear to be working - at least not in my case.

**Comment by huumanoid** [comment]
@Ardhimas please, tell more about your case.

**Comment by evansantos** [comment]
@Ardhimas it has moved to utils/getPosition... also you need to use as float not solid, to work the updatePosition() method, which call getPosition

**Comment by mobilutz** [comment]
Hi, is there any news on this subject?
I just added the `react-tooltipt` to my app, and run into this issue now.

**Comment by aronhelser** [comment]
The original codepen uses react bootstrap tooltip, which is not the same as this project. It might be using this, but an older version.

If you can reproduce a problem with the current version, please provide some details.
