### ISSUE TITLE
Stateless tooltips

### ISSUE THREAD

**Issue by oyeanuj** [ReactTooltip/react-tooltip#267]
Hi @wwayne! I've been running into some issues when I have multiple tooltips on a page, or when tooltips need to show up conditionally. 

I was wondering if you've thoughts around maybe releasing a stateless tooltip that has `open/close` prop which determines when the tooltip is open or not?

This way, the user can control the opening and closing and the library can provide them with some useful defaults. This might also simplify the props that you have today, and allow for more complex use-cases like #144 .

Thoughts?

Thank you!

**Comment by Kronenberg** [comment]
https://jsfiddle.net/ux2e356r/ Maybe its will be helpful for you.
I got almost the same problem in my application and you can only create your custom events if your want onMouseMove onMouseEnter other case >
![screen shot 2017-02-28 at 10 55 42 am](https://cloud.githubusercontent.com/assets/13053374/23398257/83b95a42-fda4-11e6-84de-d1e1229d51f9.png)

**Comment by oyeanuj** [comment]
@wwayne @huumanoid Checking to see if you guys had any thoughts on this one as well?

**Comment by danieleleoni** [comment]
Same issue here.
I'm debugging right now my application, since I did not realise that we need a <Tooltip /> for every tooltip. With a long list (~500) there are big performance issue

**Comment by AlexNisnevich** [comment]
Agreed that this would be a great feature.

@oyeanuj Have you managed to figure out a workaround?

**Comment by oyeanuj** [comment]
@AlexNisnevich I ended up moving to https://github.com/littlebits/react-popover until this issue is resolved, as had made the fine-grained control of the tooltip much harder.

**Comment by noobG** [comment]
Running into the same problem; have to use something else :(

I feel like being controllable is a pretty essential feature for any react component

**Comment by reginavlee** [comment]
I had an issue where I wanted to close one tooltip when another one was open instead of overlapping. I ended up writing a function to set state in my component and wrote a conditional in the "data-tip" property where when I wanted it "off", I set the data-tip to an empty string. Works for now but would also like to see open/close props.

**Comment by pswaroopk** [comment]
@reginavlee do you have the source code for this change, I can take a look at the implementation. (I am new to front end).

**Comment by danielbarion** [comment]
Hi guys, this will be handled on V5, thanks!

https://github.com/ReactTooltip/react-tooltip/discussions/812

**Comment by danielbarion** [comment]
Hi, closing this issue due to: https://react-tooltip.com/docs/examples/state

Please feel free to create a new one if needed. Thanks!
