### ISSUE TITLE
Tooltip positioning doesn't work on iOS with open keyboard.

### ISSUE THREAD

**Issue by alex-mironov** [ReactTooltip/react-tooltip#269]
When the user focuses on the text input element and the virtual keyboard appears tooltip is not positioned correctly anymore. 
This is happening because `fixed`positioning (which is used for tooltip) is not working on iOS devices with opened keyboard. I just wondering if you have a workaround for this or plans to fix it.

**Comment by huumanoid** [comment]
Hello @alex-mironov! Sorry for the long reply!
Have you tried `position: absolute` instead? If your `ReactTooltip` component is placed at the top level of DOM, I don't thing that `position: absolute` is inappropriate for you.

**Comment by sanorama** [comment]
any solution for this issue?

**Comment by alex-mironov** [comment]
we were trying dynamically display error tooltip when user focused input. we didn't find any better solution than place tiny icon next to input and make tooltip show when user taps on this icon. when user taps on icon input loses focus and fixed positioning starts working again

**Comment by essaji** [comment]
+1
We are also having the same issue. Any alternatives to this so far?

**Comment by sashabur** [comment]
https://github.com/wwayne/react-tooltip/issues/218#issuecomment-260597272
