### ISSUE TITLE
Tooltips always show when no mousemovement

### ISSUE THREAD

**Issue by ping-liu-sirca** [ReactTooltip/react-tooltip#271]
It would nice to optionally hide the tooltips after a delay (user defined delay) if no mouse activity after the tooltip is showing. Currently it stays on all the time.

**Comment by ping-liu-sirca** [comment]
This can be easily done by adding a timeout to the tooltip when visible and reset the timeout after update

**Comment by huumanoid** [comment]
Hello, @ping-liu-sirca! Thank you for this proposition! 
Yes, the basic implementation seems to be easy, thanks for the explanation.

Please, provide us some examples where this feature is used. I have an feeling that this feature is widely spread, but I can't find examples myself.

**Comment by Sideness** [comment]
Is there any news about this issue? I would like to do this aswell.
