### ISSUE TITLE
for tooltip being passed input fields, no way to differentiate clicks inside rendered tooltip vs outside

### ISSUE THREAD

**Issue by deconstructionalism** [ReactTooltip/react-tooltip#275]
I am passing children to some of my tooltips so they can be used to say quickly edit a value for the element the tooltip is bound to. For example  I am using a tooltip on a slider component (ion range slider) that should allow you to double click on the max value on the slider ruler in order to pop open a tooltip that allows the max to be adjusted. 

I am able to pass an input to the tooltips just fine, with `event='dblclick'` and `eventOff='click'`. However, when you click on any of the contents of the tooltip, it fires a click event detected by `eventOff` and closes. 

My workaround for this is to append an `id=this.props.id` attribute to the render function of your **index.js** script, which allows me to specifically identify the rendered tooltip wrapper using a `componentDidMount` for the parent, and then bind an event emitter for an 'anywhere else click' so that `eventOff='anywhere else click'`.

Unless there is an easier way to do this, I'd recommend adding an id=this.props.id to the render function. I can fire off a pull request in the case where I've not horribly mangles the useage of this package and this is indeed a real issue.

**edits in index.js (440:453)**

``` js
    if (html) {
      return (
        <wrapper className={`${tooltipClass} ${extraClass}`}
          {...ariaProps}
          data-id='tooltip',
          id=this.props.id,  // inserted
          dangerouslySetInnerHTML={{__html: placeholder}}></wrapper>
      )
    } else {
      return (
        <wrapper className={`${tooltipClass} ${extraClass}`}
          {...ariaProps}
          data-id='tooltip',
          id=this.props.id // inserted
          >{placeholder}</wrapper>
      )
    }
```

**Comment by deconstructionalism** [comment]
oh, and of course, I've set `pointer-events:auto` in **style.js**

**Comment by huumanoid** [comment]
Hello @deconstructionalism! Sorry for the long reply!
Your use case seems reasonable. 

Have you tried to use `ReactTooltip.hide` instead?
```js
import {findDOMNode} from 'react-dom'
import ReactTooltip from 'react-tooltip'

<p ref='foo' data-tip='tooltip'></p>
<button onClick={() => { ReactTooltip.hide(findDOMNode(this.refs.foo)) }}>Hide</button>
<ReactTooltip />
```

I don't mind including this in the library, but is it really required?
If `ReactTooltip.hide` doesn't fit your requirements, could you fetch `ReactTooltip` element using something like `document.querySelectorAll('.${extraClass}')`? Is there performance issues?

**Comment by RobertGary1** [comment]
I believe I'm having the same issue. If I click on a button within the tooltip the tooltip goes away. It seems that if someone clicks on something within the tooltip container that should not cause it to close. It should stay open.

**Comment by aronhelser** [comment]
Can you fix this by preventing event propagation? I'm not sure whether it would work, but you might be able to stop the event from bubbling in the button click handler.
