### ISSUE TITLE
Custom location

### ISSUE THREAD

**Issue by manuelnas** [ReactTooltip/react-tooltip#288]
Hey there,

I'm looking to set the location of the tooltip (what it's supposed to point at) programmatically. So basically give it an x and y location on the screen and it'll show there without there being a span or other html object.

Thanks in advance!

Manny

**Comment by AyWa** [comment]
Hey @manuelnas,
I see 2 options (but quite similar):
a span position fixed/absolute left: 0, top: 0
```
<span data-tip='yolo' data-for='test'></span> 
<ReactTooltip id='test' data-offset="{'top': yourX, 'left': yourY}"></ReactTooltip>
```
or 
a span position fixed/absolute left: YourX, top: yourY
```
<span data-tip='yolo' data-for='test'></span> 
<ReactTooltip id='test'></ReactTooltip>
```
