### ISSUE TITLE
Hide Tooltip after button click

### ISSUE THREAD

**Issue by quicklikerabbit** [ReactTooltip/react-tooltip#295]
I want to show a 'Copied!' tool-tip adjacent to a "Copy URL" button. I can get the tool tip to show on click with the code below, but it will only hide after a delay if I click the button again.

    <CopyToClipboard text={viewState.copyUrl}>
        <RaisedButton
            label="Copy URL"
            primary={true}
            data-tip
            data-event='click'
            data-for='copyToClipboard'
            onClick={viewState.copyClick}
            style={{ width: '150px' }} />
    </CopyToClipboard>
    <ReactTooltip id='copyToClipboard' delayHide={1000}>
        <p>Copied!</p>
    </ReactTooltip>

Any thoughts on how I can get this to hide?

**Comment by vivcogit** [comment]
Try use ref on ReactTooltip and hideTooltip function:

```
<CopyToClipboard text={viewState.copyUrl}>
    <RaisedButton
        label="Copy URL"
        primary={true}
        data-tip
        data-event='click'
        data-for='copyToClipboard'
        onClick={() => {this.tooltip.hideTooltip(); viewState.copyClick();}}
        style={{ width: '150px' }} />
</CopyToClipboard>
<ReactTooltip ref={(node) => this.tooltip = node} id='copyToClipboard' delayHide={1000}>
    <p>Copied!</p>
</ReactTooltip>
```

**Comment by carlobernardini** [comment]
Is there a way to prevent the tooltip from showing up when `data-delay-show` is defined and you clicked before the tooltip is actually shown? It seems that when I hide the tooltip programmatically (e.g. using `Tooltip.hide(ref)`) on click, it still shows up after that given delay.

**Comment by steveabouem** [comment]
Same issue here. I used the tooltip as a confirmation prompt. 
`<Flex row nowrap>
              <a data-tip data-for='confirmation' data-event='click' >
                <Button />
              </a>
              <ReactTooltip id='confirmation' data-html={true} data-effect='solid' class='confirm-buttons' multiline={true} >
                <span>
                  Permanently delete? <br />
                  <buttonOne onClick={() => this.deleteItems(arguments)}>Yes</buttonOne>
                  <buttonTwo onClick={() => ReactTooltip.hide()}>No</buttonTwo>
                </span>
              </ReactTooltip>
            </Flex>`
(Flex component imported from styled-flex-components library). 

My deleteItems function works just fine, but the ReactTooltip.hide() only takes effect if i move the mouse away from the tooltip. If I don't call ReactTooltip.hide(), the tooltip stays on screen indefinitely so something is happening.Just not when I want it to. Any thoughts?

**Comment by qboot** [comment]
I was able to manage this with a function that handle `click` :
```js
handleTooltip = () => {
    ReactTooltip.show(findDOMNode(this.refs.clippedText));
    setTimeout(() => {
        ReactTooltip.hide(findDOMNode(this.refs.clippedText));
    }, 750);
};
```

Then I add this to my component:
```js
<Component
    ...
    onClick={() => {
         this.copyToClipboard();
         this.handleTooltip();
    }}
    data-tip="Text copied!"
    ref="clippedText"
/>
```

Finally, the "trick" is to add an unknown event to `event` prop so hover will not trigger `show` function of tooltip:
```js
<ReactTooltip place="bottom" effect="solid" event="no-event" />
```

It should maybe also work specifically with the `data-event` prop.

**Comment by windinging** [comment]
> Same issue here.
> `<Flex row nowrap> <br> <a data-tip data-for='confirmation' data-event='click' > <Button /> </a> <ReactTooltip id='confirmation' data-html={true} data-effect='solid' class='confirm-buttons' multiline={true} > <span> Permanently delete? <br /> <buttonOne onClick={() => this.deleteItems(arguments)}>Yes</buttonOne> <buttonTwo onClick={() => ReactTooltip.hide()}>No</buttonTwo> </span> </ReactTooltip> ```
> (Flex component imported from styled-flex-components library).
> 
> My deleteItems function works just fine, but the ReactTooltip.hide() only takes effect if i move the mouse away from the tooltip. If I don't call ReactTooltip.hide(), the tooltip stays on screen indefinitely so something is happening.Just not when I want it to. Any thoughts?

i have the same problem.do u solve the problem

**Comment by rimsila** [comment]
`  <CopyToClipboard text={value} onCopy={this.onCopyData}>
                  <a
                    className={css["btn-circle-social"]}
                    onClick={() => {
                      ReactTooltip.show(this.fooRef);
                    }}
                  >
                    <img src={Icons.LinkIconBlack} alt="copy to clipbord" />
                  </a>
                </CopyToClipboard>
                <p
                  ref={ref => (this.fooRef = ref)}
                  data-tip={copied ? "URL COPIED!" : "URL NOT COPYIED"}
                />
                <ReactTooltip
                  afterShow={() => setTimeout(ReactTooltip.hide, 1200)}
                  place="left"
                />`

**Comment by rimsila** [comment]
<copytoclipboard text="{value}" oncopy="{this.onCopyData}"><a classname="{css[&quot;btn-circle-social&quot;]}" onclick="{()" =="">{ ReactTooltip.show(this.fooRef); }} > ![copy to clipbord]({Icons.LinkIconBlack}) </a></copytoclipboard> 

(this.fooRef = ref)} data-tip={copied ? "URL COPIED!" : "URL NOT COPYIED"} /> <reacttooltip aftershow="{()" =="">setTimeout(ReactTooltip.hide, 1200)} place="left" /></reacttooltip>

**Comment by grascioni** [comment]
I just used the afterShow function, like

`
afterShow={() => {
navigator.clipboard.writeText(someTextToCopy);
setTimeout(() => ReactTooltip.hide(), 1000);
}}
`

**Comment by nerdyman** [comment]
For anyone using hooks, this will ensure the timer gets reset if the user repeatedly clicks on the tooltip trigger after the timer has started.

```tsx
const MyComponent: React.FC = (props) => {
	  const buttonRef = useRef<HTMLButtonElement>(null);
	  const timer = useRef<NodeJS.Timer|null>(null);
	  
	  const handleClick = useCallback(() => {
		    if (timer.current) clearTimeout(timer.current);
		    
		    const button = buttonRef.current as HTMLButtonElement;
		    
		    ReactTooltip.show(button);
		    
		    timer.current = setTimeout(() => {
		      ReactTooltip.hide(button);
		    }, 3000);
	  }, []);
	  
	  return (
	      <button {...props} ref={buttonRef} onClick={handleClick} data-event="no-event">
			  Do something
		  </button>
	  );
}
```
