### ISSUE TITLE
Firefox: tooltip doesn't show up when attached to a child of Button

### ISSUE THREAD

**Issue by msarilar** [ReactTooltip/react-tooltip#296]
I have a component that renders a `button` and within that button I would like to have an `img` with `react-tooltip` attached:

        return (
            <button>
                <img data-tip data-for="iconTooltip" height={30} width={30}
                     src="foo.png" />

                <ReactTooltip id="iconTooltip" className="test-icon">
                    <span>foo</span>
                </ReactTooltip>
            </button>
        );

The tooltip shows up in Chrome (58.0.3029.96 64-bit), but doesn't with Firefox (v53.0 32-bit). If the `data-tip` is specified at the button level directly (rather than on the image), it shows up:

        return (
            <button data-tip data-for="iconTooltip">
                <img height={30} width={30}
                     src="foo.png" />

                <ReactTooltip id="iconTooltip" className="test-icon">
                    <span>foo</span>
                </ReactTooltip>
            </button>
        );

**Comment by ibrahimilu** [comment]
@msarilar i have the same issue as i am tooltip inside the button. The only fix i have is to change the button into a <div> or anything. Did you get the actual fix?

**Comment by benmccormick** [comment]
I'm seeing this as well, appears to be a browser level bug, nothing library specific: https://bugzilla.mozilla.org/show_bug.cgi?id=1084196
