### ISSUE TITLE
`undefined is not a function` on Chrome 38

### ISSUE THREAD

**Issue by danieleleoni** [ReactTooltip/react-tooltip#297]
Hi,
I was updating react-tooltip from 3.2.9 to 3.3.0, but I realised there is an error on trackRemoval.js on this row, even if tooltip is working fine
```
for (var _iterator2 = mutation.removedNodes[Symbol.iterator](), _step2; !(_iteratorNormalCompletion2 = (_step2 = _iterator2.next()).done); _iteratorNormalCompletion2 = true) {
```
<img width="1280" alt="screen shot 2017-05-05 at 17 37 16" src="https://cloud.githubusercontent.com/assets/20039309/25752757/8520db6e-31b9-11e7-8d56-f2b35995b467.png">

Problem is not present at all on 3.2.9 or into a recent version of Chrome

Thanks!

**Comment by OriR** [comment]
@huumanoid 
This error appears in Edge as well, could you please take a look at this?

**Comment by Alfafc** [comment]
Same here, last update throw those errors

**Comment by icodeforyou** [comment]
Safari 9 throws this error aswell.

**Comment by avivshafir** [comment]
+1

**Comment by nik-lampe** [comment]
+1

**Comment by Rogger794** [comment]
Can someone check if the error already exist?
