### ISSUE TITLE
Tooltip anchor rendering strangely

### ISSUE THREAD

**Issue by caiges** [ReactTooltip/react-tooltip#299]
Any idea why the anchor would be jagged? I haven't modified the styles in any way. This doesn't happen on every page:

![screenshot](http://i.imgur.com/qRpEiLr.png)

**Comment by Olliebaba** [comment]
Could you increase delayHide to a big number then inspect the tooltip? It might be inheriting styles from something.

**Comment by sashadixie** [comment]
i had the same issue in project, it was caused by same id-s of elements, there were 228 and more divs with the same id. check your id-s
