### ISSUE TITLE
Disabled element won't show tooltip

### ISSUE THREAD

**Issue by stefensuhat** [ReactTooltip/react-tooltip#304]
```
 <button
	onClick={onCheckoutPress}
     className="button primary font-14 font-400 full"
     disabled={true}
     data-tip="Disabled"
     data-for="checkout-button"
 >
     Save
 </button>

 <ReactToolTip
       id="checkout-button"
/>
```

The tooltip won't show if button is disabled.

**Comment by bost-h** [comment]
Same issue here, but it only occurs with (disabled) buttons, not all elements.
As a workaround, I wrapped my disabled button inside a span element :
```
<span data-tip="Lorem ipsum" data-tip-disable={false}>
    <button disabled={true}>Click</button>
</span>
```

**Comment by WickyNilliams** [comment]
I was bit by the same issue. Good idea on the workaround

**Comment by kellyrmilligan** [comment]
+1, guess i'm doing the workaround 🤕

**Comment by strongui** [comment]
Hm, don't really like the wrapping workaround, as it can mess up things like menu items etc, that rely on a certain DOM structure. I think a very common scenario is to want to show a tool-tip if a button is disabled, to explain to the  user why it's disabled.

**Comment by NandySahukar** [comment]
Keep the button inside the `<span>` tags then you can get the tooltip for disabled buttons. This is the best you can do instead of using **warning**

`<span>
        <button disabled> Save </button>
</span>`

**Comment by YuriScarbaci** [comment]
> Hm, don't really like the wrapping workaround, as it can mess up things like menu items etc, that rely on a certain DOM structure. I think a very common scenario is to want to show a tool-tip if a button is disabled, to explain to the user why it's disabled.

can't stress this more.

**Comment by jonauz** [comment]
I haven't full tested it yet, but I have a situation where wrapping in <span> ... </span> it makes tooltip appear, but don't disappear.

**Comment by rahul-desai3** [comment]
+1

**Comment by tsrul** [comment]
If you have another tag in disabled button you can set tooltip on it as well.
<button disabled={true}>
<i data-tip="your tip"></i>
</button>

**Comment by benlieb** [comment]
The workaround that worked best for me is to put the span inside the button:

```html
<button disabled={true}>
  <span data-tip="Lorem ipsum" data-tip-disable={false}>
    Click
  </span>
</button>
```

**Comment by evgenyfadeev** [comment]
^ you have to style the span though to be full height of the button, otherwise the tip will trigger only over the text.

**Comment by eliranmal** [comment]
this is probably gonna be hard to solve without introducing some higher-level code (which, i'm not sure is desired for this library); the issue stems from the native behavior of disabled elements (see [this demo][1] for an illustration of this behavior).

_details:_

the way that react-tooltip responds to user interaction relies on binding native dom events to the button (namely, `mouseenter` and `focus`), as seen in the [source code, on the main file][2].
these events are not triggered by the user agent, if the element is marked as disabled. [W3C's recommendation][3] on this states that engines should prevent dispatching `click` events, but apparently vendor implementations have broadened this definition (or probably there's a spec in place that i'm not aware of).





[1]: https://jsfiddle.net/kf213Lxg/
[2]: https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L296-L297
[3]: https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#concept-fe-disabled

**Comment by eliranmal** [comment]
also, here's my current take for a workaround:

    export default const FormControl = ({
      tag: FormControlType,
      ...props
    }) => {
      const tooltipAttributes = Object.entries(props)
        .filter(([key, value]) => key.startsWith('data-'))
        .reduce((accum, [key, value]) => {
          accum[key] = value
          return accum
        }, {})
    
      return props.disabled && tooltipAttributes['data-tip'] ? (
        <span {...tooltipAttributes}>
          <FormControlType {...props} />
        </span>
      ) : (
        <FormControlType {...props} {...tooltipAttributes} />
      )
    }

this implementation has an obvious limitation; it assumes all `data-*` attributes belong to react-tooltip, but other then that, it's just a convenient way to encapsulate all that wrapper shenanigans into a nice package.

example usage:

    const Button = ({className = '', ...props}) => (
      <FormControl
        {...props}
        tag="button"
        className={`drifter-button ${className}`}
      />
    )


it can also be used for its declarative abstraction-level of form-control components, that is - we can include CSS rules that are common to buttons, inputs, selects etc. (ever found yourself constantly repeating stuff like `outline: 0` across form control components? i know i did..).

**Comment by sztadii** [comment]
> The workaround that worked best for me is to put the span inside the button:
> 
> ```
> <button disabled={true}>
>   <span data-tip="Lorem ipsum" data-tip-disable={false}>
>     Click
>   </span>
> </button>
> ```

Works great, thanks :)

**Comment by avital-ubeya** [comment]
updating rc-tooltip to latest version made it work
