### ISSUE TITLE
Keep tooltip open?

### ISSUE THREAD

**Issue by Drecula** [ReactTooltip/react-tooltip#319]
Hi,

Nice component!

I'm using react-tooltip in a parent list, with each list item having an icon that, on mouseover, shows it's respective tooltip. The tooltip contains a component that receives data from the list item and shows a list of items. Users need to be able to scroll the list of items in the component shown in the tooltip.

That all works fine, except:
1. The positioning and sizing of the tooltip is not consistent
2. I can't figure out how to stop the tooltip from closing when moused away from the icon.

I'm currently making an instance of the tooltip for each item in the parent list, versus at the top level of the parent component, because I could not get the tooltip to render otherwise.

Please let me know if you've any suggestions.

Thanks.

**Comment by aronhelser** [comment]
Did you make any progress with this?

**Comment by dmikester1** [comment]
I also would like to figure out how to keep the tooltip open, so text from the tooltip could be copied by the user.

**Comment by lancejpollard** [comment]
@danielbarion how do you do this, did you mean to close the issue? Did you implement this feature somehow?

**Comment by gabrieljablonski** [comment]
@lancejpollard please open a new issue detailing the problem.
