### ISSUE TITLE
How to update position of toolltip after scroll?

### ISSUE THREAD

**Issue by devpaulson** [ReactTooltip/react-tooltip#325]
How to update position of toolltip after scroll if scroll hide is false? Right now, if scroll hide is false, after the scroll, the tooltip remains in the same old position. Is it possible to update the position? I tried rebuild but there was no changes.

**Comment by wateryoma** [comment]
you can update position with ReactTooltip.show(target)

**Comment by cneeson** [comment]
@wateryoma would you mind expanding on this answer a bit more? In the same situation, but not 100% sure where that call would be

**Comment by gost402** [comment]
Add custom styles: `position: absolute` instead of `position: fixed`. That will fix this behavior

**Comment by LinAlSara** [comment]
Any updates on this?

**Comment by kennylbj** [comment]
Any updates on this?

**Comment by aronhelser** [comment]
The maintainers of this project will gladly accept pull requests to fix any
issues you encounter and can provide a fix for!

**Comment by kennylbj** [comment]
Here is a workaround:
1. change position to absolute
```css
.tooltip {
  position: absolute !important;
  width: fit-content !important;
}
```

2. set ``overridePosition`` to the desired position
```js
overridePosition={({curLeft, curTop}) => ({ left: xx, top: xx })}
```

```js
<ReactTooltip
  className='tooltip'
  overridePosition={({curLeft, curTop}) => ({ left: xx, top: xx })}
 />
```

**Comment by nguyenhoaidanh** [comment]
if this lib has `ReactTooltip.updatePosition()` will be good
🙏
