### ISSUE TITLE
`import ReactTooltip from 'react-tooltip'` doesn't work.

### ISSUE THREAD

**Issue by ashok-sc** [ReactTooltip/react-tooltip#351]
When importing this way, I get the following runtime error:
`
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

Changing the import to this fixes it:

`import * as ReactTooltip from 'react-tooltip';`

**Comment by torioLuz** [comment]
I faced the same issue, and just realized the type declaration file defined it that way s.t. you have to use import *

**Comment by isabellachen** [comment]
It's exported as default.. `import ReactTooltip from 'react-tooltip'`

**Comment by jacekk** [comment]
FTR:

`import ReactTooltipDefaultExport from 'react-tooltip';` --> only `default` export
`import * as ReactTooltipWholeModule from 'react-tooltip';` --> the whole module, which is `default` + all named exports
`import ReactTooltipDefaultExport, { TooltipProps } from 'react-tooltip';` --> `default` + a specific named export

**What is the issue?** As the above seems to be working as expected. Tested on:
- typescript @ 3.9.7
- webpack @ 4.44.1

**Comment by codewisersahil** [comment]
export 'default' (imported as 'ReactTooltip') was not found in 'react-tooltip' (possible exports: Tooltip, TooltipProvider, TooltipWrapper).
If you are facing this problem then try this ====>
import { Tooltip as ReactTooltip } from 'react-tooltip'
and run this .

**Comment by aryanarora29** [comment]
> import { Tooltip as ReactTooltip } from 'react-tooltip'

tysm sir it workedddd

**Comment by HristoYonkov** [comment]
Worked thanks!
