### ISSUE TITLE
Tooltip doesn't show on late mounted elements

### ISSUE THREAD

**Issue by amitzur** [ReactTooltip/react-tooltip#354]
Since `bindListeners` is called only on `componentDidMount`, there is no listening on `mouseenter` for any element that shows up in the DOM after `ReactTooltip` was mounted.

Is this supposed to be supported?

Thanks!

**Comment by tyler1314371** [comment]
@amitzur I believe there was a PR opened for this https://github.com/wwayne/react-tooltip/pull/273

However I don't think it has been merged yet. I am also very interested in this feature.

**Comment by Wrangl** [comment]
I believe you can call ReactTooltip.rebuild() after the new components are rendered? 
And if you're using react state, make sure to put it in the callback, e.g. 
     this.setState({newComponentsAdded: true}, () => ReactTooltip.rebuild() )

**Comment by amitzur** [comment]
This would account for a very unrealistic API, since I would need to manage state of added components. Essentially reimplement the reconciler :)

I am in favor of the approach proposed in #273 (actually I see no other way). Currently I've just implemented something similar with less features for my app.
