### ISSUE TITLE
Tooltip crops if renders in `Overflow: hidden` element

### ISSUE THREAD

**Issue by wamujlb** [ReactTooltip/react-tooltip#358]
Hi. This is too big problem if you render tooltip inside an element which has prop - `overflow: hidden`. 
[
![image](https://user-images.githubusercontent.com/14905044/33985094-0285bf3e-e0d3-11e7-8804-156151545263.png)
](url)

**Comment by uxtx** [comment]
ran up against this as well - has anyone come up with a work around for this?

**Comment by wamujlb** [comment]
@uxtx , do you have some ideas to fix it?

**Comment by Tarpsvo** [comment]
That's what `overflow: hidden` does. Either make the overflow visible or put the tooltip in a parent view.

**Comment by Craftnet** [comment]
You can always use **createPortal**

Something like that:
```javascript
ReactDOM.createPortal(
    <Tooltip id={corresponds_id_for_data-ref} />,
    document.getElementsByTagName('body')[0]
)
```

**Comment by tonix-tuft** [comment]
You can also use this useful HOC which appends a React component to the `body` element:

https://github.com/jpgorman/react-append-to-body

**Comment by nmartinezb3** [comment]
You can fix this by placing an empty `div` in your body and use portals:
```js
const domElement = document.getElementById("tooltip-container")
```
```jsx
<div>
  <a data-tip data-for="my-tooltip">
    <Icon />
  </a>
  {ReactDOM.createPortal(
    <ReactTooltip
      id="my-tooltip"
      {...props}
    >
      Some tooltip content
    </ReactTooltip>,
    domElement
  )}
</div>
```
