### ISSUE TITLE
True string appears in empty tooltip

### ISSUE THREAD

**Issue by ChCosmin** [ReactTooltip/react-tooltip#362]
```
<div className="form-item-50 form-item-question right-form-item">                  
    <div data-for="tooltip-cvc" data-tip data-event="click" style={{ backgroundImage: "url(" + questionMarkImage + ")" }} className="cvc-explanation" />                
    <ReactTooltip id="tooltip-cvc" className="cvc-popover-image tooltip-cvc" place="top" effect="solid" />             
</div>    
```

any idea why this adds a text of " true "  inside the tooltip?
there is no :after { content: "true" "} or anything that would spawn it, it just apeared on its own

**Comment by combizs** [comment]
> Note:
> 1. data-tip is necessary, because <ReactTooltip /> finds the tooltip via this attribute

By default, if nothing is given to **data-tip**, it will render _true_
