### ISSUE TITLE
Place bottom, left

### ISSUE THREAD

**Issue by s-dezign** [ReactTooltip/react-tooltip#381]
Is it any way how set placement as bottom, left? like at the bottom and start of element, or the bottom and end of the element? 

Because right now if I have an element close the window border I can't set up bottom ... it's showing tooltip on the side no matter what.

Thanks

**Comment by aronhelser** [comment]
Yes, react-tooltip doesn't have option for bottom+left, like some of the other tooltips I've seen. It'd be a great contribution....
