### ISSUE TITLE
Changing browser size for tooltip placement.

### ISSUE THREAD

**Issue by DECAlum** [ReactTooltip/react-tooltip#382]
I have an app that divides the browser window into different areas.  There is a list of items on the left side and content on the right.  I would like tooltips to be kept within the right side and not spill over into the left side.  I noticed in the code that window.innerHeight and window.innerWidth are being used for the placement calculations.  Is there any way to override this?  If not, would it be possible to add props to set the max height and width?

**Comment by vsc-github** [comment]
Having the same issue. Would like to contain the tooltips within a container, inside a map component actually. Did you find a workaround to this?

**Comment by DECAlum** [comment]
Unfortunately no.  The product went a different direction without tooltips so the issue was not pursued.
