### ISSUE TITLE
The contents of the list looped by 'map' or the contents in conditional statements ,the highest ReactTooltip doesn't work.

### ISSUE THREAD

**Issue by TokeyJerry** [ReactTooltip/react-tooltip#392]
Q1:
    `
    <ul>
        { listData.map((item, index) => 
            (
                <li data-for="tooltip-list" data-tip="item.name">
                    item.value
                </li>
            )
        )}
    <ul>
    <ReactTooltip id="tooltip-list" place="right" type="dark" effect="float"/> 
    `

The above code ReactTooltip does not work, and I look at the Chrome's Elements, ReactTooltip's contents is null.But when I code as follows, it works.
    `
    <ul>
        { listData.map((item, index) => 
            (
                <li data-for={`tooltip-list-${index}`} data-tip="item.name">
                    item.value
                </li>
                <ReactTooltip id={`tooltip-list-${index}`} place="right" type="dark" effect="float"/> 
            )
        )}
    <ul>
    `

Q2:

`
<div>
  {
     conditions == ture ? (<p data-for="test" data-tip="test tooltips"></p>) : null
  }
</div>
<ReactTooltip id="test" place="right" type="dark" effect="float"/> 
`

This question is I must put the ReactTooltip label in condition,because when this conditino is false and the next condition is true,tooltip doesn't work when the condition is true,just like fallows code.

`
<div>
  {
     conditions == ture ? (<p data-for="test" data-tip="test tooltips"></p><ReactTooltip id="test" place="right" type="dark" effect="float"/> ) : null
  }
</div>
`

**Comment by aronhelser** [comment]
In your sample code, I would expect you to always get a tooltip with the string "item.name" inside it. But you say that the tooltip doesn't show at all? It's contents are`null`?

I'm sorry, but I don't understand what you are asking with Q2?

**Comment by TokeyJerry** [comment]
I'm so sorry that my statement is not clear.
Q1:
```
export class test extends Component {
    render () {
        const list = [{key: 0, name: 'first'}, {key: 1, name: 'second'}, {key: 2, name: 'third'}];
        return (
            <div>
                <ul>
                    list.map(item => (
                        <li key={item.key}>
                            <p data-for="tooltip-info" data-tip={item.name}>{item.name}</p>
                        </li>
                    ))
                </ul>

                <ReactTooltip id="tooltip-info" place="top" type="dark" effect="float"/>
            </div>
        )
    }
}
```

As the code above,when I mouse over the li tag, tooltip doesn't show at all. I rewrote my code as follows:

```
export class aa extends Component {
    render () {
        const list = [{key: 0, name: 'first'}, {key: 1, name: 'second'}, {key: 2, name: 'third'}];
        return (
            <div>
                <ul>
                    list.map(item => (
                        <li key={item.key}>
                            <p data-for={`tooltip-info${item.key}`} data-tip={item.name}>{item.name}</p>
                            <ReactTooltip id={`tooltip-info${item.key}`} place="top" type="dark" effect="float"/>
                        </li>
                    ))
                </ul>
            </div>
        )
    }
}
```

Now,it works.But in this way,in this 'div' tag,there will be many 'ReactTooltip' tags.

**Comment by nantan** [comment]
@TokeyJerry You may be happy using the `ReactTooltip.rebuild()` .

**Comment by sepuckett86** [comment]
I have the same issue with using conditional (ternary) operators inside of `render(){return()}` like this:
`{ this.props.id === this.props.id2 ?
        <div><button data-tip="Message here" onClick={this.handleClick}>Click Me</button></div> : null }`
The tooltip doesn't show up on hover, while other tooltips do. 
Would `ReactTooltip.rebuild()` help with that and if so, where do I use it?
