### ISSUE TITLE
On hover show multiple tool tips? 

### ISSUE THREAD

**Issue by joyguy55** [ReactTooltip/react-tooltip#397]
At first I assumed you could possibly have data-for correspond to multiple ids to make this work? I don't know if there is a quick work around for something likes this?

**Comment by aronhelser** [comment]
I don't think there is support for this - I assume you're putting them in different positions (top, bottom)?
I think you'd probably have to go manual, and use mouseover/mouseout events to call .show() and .hide() on the multiple tooltips. 

Possibly you could use the event callbacks on one tooltip to show the other one(s)?

**Comment by wmertens** [comment]
@aronhelser if you have 2 elements with tooltips that are overlapping, shouldn't the tooltip only show for the top-most element?
