### ISSUE TITLE
How use tooltip when hover one options of select input

### ISSUE THREAD

**Issue by hieuandree** [ReactTooltip/react-tooltip#404]

**Comment by hipopotamas** [comment]
Hey! I am having this same issue. When hovering over an option element the .__react_component_tooltip element associated doesn't seem to add the .show class.

I tried coding all the data- tags on each option element, as well as just storing the data-tip and data-for in each and the rest on the corresponding ReactTooltip element; also tried to use different ReactTooltip elements for different option elements, as well as using the same for all: whenever it's linked to an option element it never gets the ".show" class, nor does the position update, but the same tooltip works just fine hovering over any other element I have tried. I also tried to use the "overridePosition" prop but it just won't get triggered when hovering over an option element. Using the event prop with "mouseover" would not do de trick either.

Would love to get some help fixing this, this component is awesome.

**Comment by aronhelser** [comment]
So if the select element is not open, the option elements don't exist in
the DOM yet, so react-tooltip won't know about them, I think.
You could try to do a `ReactTooltip.rebuild()` when the options are shown,
so the tooltip can traverse them.

**Comment by hipopotamas** [comment]
Thanks! It won't work with option elements since they do not seem to ever exist on the dom (or at least Shift + Ctrl + C won't show anything in the code when hovering over them), but avoiding the option tags by creating a custom select element that triggers ReactTooltip.rebuild() on opening did the trick :)
