### ISSUE TITLE
afterShow and afterHide should not swallow the trigger event

### ISSUE THREAD

**Issue by cjzcpsyx** [ReactTooltip/react-tooltip#406]
for the event callbacks: afterShow and afterHide
should pass the original `event` in the callback
https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L344
https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L378
Into
`afterShow(e)` and `afterHide(e)`

I can create PR if people think this is valid

**Comment by bluestreek18** [comment]
Would be nice if this didn't happen as its currently difficult to know which exact tooltip triggered the event.

**Comment by cjzcpsyx** [comment]
https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L388
what is the event here in the context, do it indicate any thing on the current trigger
event.target should gives the trigger element?

**Comment by bluestreek18** [comment]
I'm going to go ahead and submit a pull request unless you feel like I'm stepping on your toes here. I need this asap.

**Comment by cjzcpsyx** [comment]
https://github.com/wwayne/react-tooltip/pull/444
@bluestreek18

**Comment by theocerutti** [comment]
Why did PR hasn't been merged?
My issue is that i cannot stopPropagation of the event when we click outside the tooltip.
for example if i open my tooltip and then i click outside on a button outside the tooltip then it should click on the button it should just close the tooltip

**Comment by danielbarion** [comment]
@theocerutti because the creator of the PR closed it as fixed
