### ISSUE TITLE
Moving mouse from target into tooltip should have a delay if you cross another target accidently

### ISSUE THREAD

**Issue by RobertGary1** [ReactTooltip/react-tooltip#411]
I have a tooltip that contains a menu. So the user slides the mouse up into the tooltip. However, if they accidently touch another target getContent gets called and the content is immediatly changed, even though we have  delayShow. I'd like to check in a change that if the tooltip is currently active and the user sets a parameter such as "delayNewContent" then we apply a delay before calling getContent. As usually once they enter the tooltip the timer will be cleared and the desired tooltip is still shown.

**Comment by aronhelser** [comment]
That sounds like a useful feature, especially if you can provide a PR. It would be great to have an example showing this functionality - we've had several comments asking about how to get a button/menu/scrolling to work inside a tooltip.

**Comment by RobertGary1** [comment]
PR https://github.com/wwayne/react-tooltip/pull/416

**Comment by volodymyr-tsaryk** [comment]
That PR has broken another functionality
We have buttons in the tooltip http://take.ms/qfw0G and after the button is clicked tooltip should become hidden, however after that update it remains on screen and is hidden only after we remove the mouse cursor from it.

We were hiding them using ReactTooltip.hide();

Could you please advise if there is a workaround?

**Comment by RobertGary1** [comment]
Ah, I see. I'm surprised you were ever able to get the mouse to enter the
tooltip without it dismissing but it looks like perhaps your target area is
large enough that the mouse doesn't have to leave it. I wonder if setting
delayHide to a small value would help. Are you getting any console errors
when you try to hide the tooltip?

**Comment by volodymyr-tsaryk** [comment]
@RobertGary1 
No, there are no console errors
The issue is happening due to this line http://take.ms/OPRZz
