### ISSUE TITLE
Positioning is not correct in IE 10 and Edge older versions

### ISSUE THREAD

**Issue by avi-jain-pepcus** [ReactTooltip/react-tooltip#418]
I am facing cross-compatibility issues while using a tooltip. Left and top positions are not as expected.
It is working fine in IE 11 and IE edge for updated versions but having issues in IE 10 and Edge for older versions.

`<ReactTooltip id={toolTipId} className="FormTooltip__Message" place={position}>
          <span>{message}</span>
        </ReactTooltip>`

**Comment by hamed-farag** [comment]
am facing now this issue with IE11

**Comment by kdhallu** [comment]
I'm facing the same issue, Did anyone fix this ?

**Comment by aronhelser** [comment]
Is this true on any of the examples from the example page? If so, can you
give exact steps to reproduce?
If anyone has suggestions about what might be wrong, please speak up!

**Comment by kdhallu** [comment]
![image](https://user-images.githubusercontent.com/1831385/65304416-33176e00-db9e-11e9-8390-a9f5baba76fb.png)


This is reproducible in demo page the first icon on left

**Comment by aviranmz** [comment]
any solution for this issue?

**Comment by tonthanhhung** [comment]
Does anyone know there's an alternative option which works nicely with IE11 ?
