### ISSUE TITLE
How to trigger only on .show()?

### ISSUE THREAD

**Issue by robbanp** [ReactTooltip/react-tooltip#423]
I'd like to trigger the tooltip only on a .show() call, and not by interacting with the object, in this case a INPUT field.

How can I do this? For example in a validation scenario.

**Comment by aronhelser** [comment]
I think you can do it by not setting the 'data-for' and 'data-tip' elements, then using the .show() and .hide() calls. If you wanted to submit an example, that'd be great!

**Comment by robbanp** [comment]
Thanks, but it doesn't show now when I do:

this.CCNumber = React.createRef();
...
ReactTooltip.show(this.CCNumber.current);

...
<input data-for="cardNotSupported" ref={this.CCNumber} data-tip-disable="false" id="card_number" name="card_number" placeholder="xxxx xxxx xxxx xxxx" autoComplete="cc-number" required="" autoFocus="" />

...

<ReactTooltip id="cardNotSupported" place="bottom" type="success" effect="solid">
Card is not supported
</ReactTooltip>

**Comment by aronhelser** [comment]
I'm not sure how to resolve it.  Hopefully someone else may have an idea.

**Comment by anking** [comment]
I also need it to be controlled manually only. I cant figure out a way to do it.
