### ISSUE TITLE
How to make ReactTooltip's getContent detect and reflect changes to data-tip immediately?

### ISSUE THREAD

**Issue by PabloMessina** [ReactTooltip/react-tooltip#431]
I have a single global ReactTooltip and multiple Buttons feeding this tooltip with content through their data-tip props.

For example:
` render() {
        return (<div>
             {this._renderButtons()}
            <ReactTooltip
                id="global"
                type="info"
                effect="solid"
                getContent={dataTip => dataTip}
            />
        </div>);
 }
`

And some buttons look like this:
`
<button
                                    data-tip="hide explanation"
                                    data-for="global"
                                    onClick={this._getToggleCallback(itemId)}
                                >
                                    <FontAwesomeIcon icon="minus-circle" size="3x" />
                                </button>
`

And the other buttons like this:
`
<button
                                    data-tip="show explanation"
                                    data-for="global"
                                    onClick={this._getToggleCallback(itemId)}
                                >
                                    <FontAwesomeIcon icon="question-circle" size="3x" />
                                </button>
`

The problem is that each button click triggers a GUI re-render that toggles the clicked button's mode between "show" and "hide", but the tooltip's content does not reflect that change immediately. In order for the new data-tip to be reflected I need to move the cursor out of the button and back into it. Let me show you what I mean with some screenshots:

1) First, I place the cursor over the question mark button and it says "show explanation". So far so good.
![imagen](https://user-images.githubusercontent.com/6187545/45600839-a90c5680-b9d9-11e8-95c8-b68a4026156a.png)

2) I click on the button, the explanation is shown, and the button's icon changes into a "minus". The button's data-tip prop also changes to "hide explanation". However, the tooltip still keeps saying "show explanation".
![imagen](https://user-images.githubusercontent.com/6187545/45600852-043e4900-b9da-11e8-8ed0-61ddb58643c3.png)

3) But, if I move the cursor out of the button and back into it, then the tooltip catches up and starts saying "hide explanation" as expected.
![imagen](https://user-images.githubusercontent.com/6187545/45600894-9c3c3280-b9da-11e8-8d61-8ab093ec2eca.png)

Any ideas on how to make the data-tip changes be reflected immediately in the tooltip?

**Comment by Delboyeire** [comment]
I would really like this feature too! we have dynamically generated data-tip content and the changes are not reflected.

I have solved it by rebuilding the tooltip when those components update by calling ReactTooltip.rebuild(), but this means passing the rebuild function down many levels which is undesirable

**Comment by DTX-92** [comment]
Vote for this.
It would be enough if ReactTooltip.rebuild() worked.

**Comment by aronhelser** [comment]
Does the technique shown on the example page not work? The random number/ cropped phrase example?

**Comment by DTX-92** [comment]
This one?
![image](https://user-images.githubusercontent.com/20479161/80532396-c0c50280-89a4-11ea-9137-03753f930c86.png)

No, it doesn't. If you don't move mouse, tooltip doesn't update.

**Comment by aronhelser** [comment]
That one. The one on the right has a `1000` timer argument. If you shorten that to `33`, you should recalculate the content at 30 fps.

**Comment by benlieb** [comment]
I had a similar issue, but solved it with `mouseEnter`, `setState`, and `getContent`

```js
export default class SimilarChars extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
    }
  }

  similar = () => (
    getSimilar(this.props.entry.simp) 
  )

  lookup = (char) => {
    if (this.state[char]) return
    
    utils.lookup(char, 
     (results) => {
        console.log(results)

        this.setState({
          [char] : results
        })
     }
    )
  }

  dataTip = (char) => (
    this.state[char] ?
      this.state[char][0]?.pinyin.join(', ')
    :
      char
  )
  
  render() {
    if (this.props.entry.simp.length != 1) return null //only for single chars
    const similar = this.similar()
    if (!similar) return null

    return (
      <div className='data_row'>
        <div className='data_label'>sim</div>
        <div className='data'>
          { 
            similar.split('').map(
              (char , i) => {
                const tipId = uuid()
                return (
                  <span key={char}>
                    <span
                      className='char_md mr-1 clickable'
                      onClick={() => utils.lookup(char, this.props.setLookupResult) }
                      onMouseEnter={() => this.lookup(char)}
                      data-tip={''}
                      data-for={tipId}
                    >{char}</span><ListSpacer i={i} array={similar} mr={2} comma={false} />
                    
                    <ReactTooltip 
                      id={tipId}
                      type='light'
                      getContent={ () => this.dataTip(char) }
                    />
                  </span>
                )
              }
            )
          }
        </div>
      </div>
    )
  }
}
```

**Comment by filipealonso** [comment]
+1

**Comment by Husainwow** [comment]
any solutions on this yet?

**Comment by Husainwow** [comment]
> @aronhelser, this one? ![image](https://user-images.githubusercontent.com/20479161/80532396-c0c50280-89a4-11ea-9137-03753f930c86.png)
> 
> No, it doesn't. If you don't move mouse, tooltip doesn't update.

hey guys this works for dynamic tooltip generation, thanks @DTX-92 .
