### ISSUE TITLE
Tooltip with expandable content? 

### ISSUE THREAD

**Issue by DiagoSmith** [ReactTooltip/react-tooltip#432]
Hey there,

I have a component in my tooltip that when clicked on, expands changing height. This unfortunately leads to a tooltip, or rather the triangular section, being in the wrong place. 

I've tried numerous things to re-render this open tooltip including `ReactTooltip.rebuild()` (this did nothing at all :( )  and hiding and showing the tooltip programmatically (via `show()` and `hide()` but unfortunately show() does not seem to work either for some reason.

I'm at my wits end here, was wondering if there any other suggestions on how to achieve something like this?

**Comment by proful** [comment]
Same issue!
