### ISSUE TITLE
How to force the tooltip to stay within the screen bounds on mobile devices?

### ISSUE THREAD

**Issue by SokolskyNikita** [ReactTooltip/react-tooltip#447]
On mobile, the tooltip gets hidden if it's spawned too close to the edge of the screen. Is it possible to force the tooltip to stay within the screen bounds?

**Comment by RicardoDeity** [comment]
Hi SokolskyNikita, 

I managed to do this by setting a class on the tooltip element, and add a CSS rule for this class that has: max-width: 70vw (so that it will have a max width of 70% viewport width).
Hope this helps!
