### ISSUE TITLE
Infinite loop generated

### ISSUE THREAD

**Issue by rothwelljeff** [ReactTooltip/react-tooltip#453]
I'm getting the following error message:
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

and the stack trace shows the react-tooltip module is probably responsible (or react-dom, but since a `setState` call is likely the source of the error, I'm thinking it is react-tooltip):
```
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:13 in Error
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:14 in ca
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:201 in w
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:131 in If
webpack:///./node_modules/react/cjs/react.production.min.js:13 in enqueueSetState
webpack:///./node_modules/react-tooltip/dist/index.js:585 in setState
webpack:///./node_modules/react-tooltip/dist/index.js:586 in updatePosition
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:126 in call
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:126 in mf
webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:215 in lf
```

I am running the latest version of react-tooltip (3.8.4).

**Comment by kidkkr** [comment]
This happens sometime in my case, maybe this is because of mechanism of this library?

**Comment by Junbong** [comment]
> This happens sometime in my case, maybe this is because of mechanism of this library?

Probably happened by mechanism, I thinks so too.

**Comment by beeeku** [comment]
Any Updates on this? I am using react-tooltip with react-window but getting above mentioned error.
