### ISSUE TITLE
why tooltip shows overlay

### ISSUE THREAD

**Issue by jiehan1029** [ReactTooltip/react-tooltip#458]
Somehow in my page, when tooltip is triggered, it looks as if there're two tooltip windows been triggered with same content, overlapping each other. 
Multiple tooltip components are mounted in the page but only trigger one at a time.
My tooltip component is like this: the tooltip id is generated by uuid

>             <div data-for={thisTooltipID} data-tip={this.props.dataTip} data-html={true}> 
>                 <ReactTooltip id={thisTooltipID} place={this.props.place} html={true}/>
>                 {this.props.children}
>             </div>

Could anyone give me a hint why this is happening?

**Comment by gabrieldonadel** [comment]
This also happens to me with overlaying shadows

**Comment by pswaroopk** [comment]
I have resolved this issue by setting <div data-for={uniqueId}.... in line one and <ReactTooltip id={uniqueId} in line two.
