### ISSUE TITLE
initial render is messy in server/static render

### ISSUE THREAD

**Issue by jsphweid** [ReactTooltip/react-tooltip#463]
I made this gif that explains what is going on: https://gyazo.com/c43c410aa9cb93bfdfaf4c2da8559019

Basically when you go to a page for the first time, the tool-tip popup contents display then go away once javascript executes.

In my case, the tooltip is configured to only popup on click. And as a fix, I plan on simply making that component only display tool tip once componentDidMount, but it's kind of a hack and that info won't be on page source / seo-friendly.

I guess I imagined that the contents of the popup would at least be hidden on the initial rendered, not just splattered on the screen in some place as to cause a flicker for server-side / static rendered apps.

Am I missing some config or could this be improved in the code?

**Comment by jspencersharpe** [comment]
Dealing with this issue as well.

**Comment by jacobgranberry** [comment]
Same...

**Comment by th0th** [comment]
If a custom wrapper component is used, checking if `window` is defined or `process.browser` for next.js before rendering would be another workaround, but still, it won't solve SEO issue. I am not sure how it can be solved SEO-friendly though.

**Comment by asifrahman01** [comment]
Same issue here
