### ISSUE TITLE
Tooltip goes away even while currently hovering over tooltip trigger

### ISSUE THREAD

**Issue by tylergaugler16** [ReactTooltip/react-tooltip#482]
At one point react-tooltips were working as expected, but only recently did we find that even while hovering on the tooltip trigger, the tooltip would open initially, and then precede to close even if the cursor never leaves the tooltip trigger. 

After some inspecting, one of the things I was noticing is that sometimes the  hideTooltip method is receiving an undefined event. Any reason for this to happen?

Adding this bit of code fixed the problem for now, but i am wondering what could have caused that to happen.
`  if(e == undefined){  return;   }` 

Any ideas?

(Something to note is that I can see the react state change of the react-tooltip-component, and have completely removed my styles,  and can still reproduce this issue, so i am fairly certain custom styles/animations are not effecting this. )

**Comment by aronhelser** [comment]
That's really strange - you could change that `return` to `debugger` and try to figure out what the undefined event means....

**Comment by tylergaugler16** [comment]
If anyone else is having this issue, I found that adding this line to the hideTooltip function worked:
`if (e === undefined) return`

For some reason an undefined event was triggering the close of the tooltip.

**Comment by aorsten** [comment]
I am experiencing the same. I use react-tooltip in a next-js page to show footnotes. They used to work great, but now I get the same thing as @tylergaugler16 . 
However, if I move the mouse onto the area, and manage to hold it perfectly still, I get the good old behavior.

This is my code:
```
class Footnote extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <React.Fragment>
                <a data-tip 
                    data-for={'global_' + this.props.footnote_id}
                    data-event="touchstart focus mouseover"
                    data-event-off="mouseout">
                    <sup>{this.props.footnote_number}</sup>
                </a>
                <Portal selector='#tooltip-root'>
                    <ReactTooltip id={'global_' + this.props.footnote_id} 
                        aria-haspopup='true'
                        delayHide={500}
                        delayUpdate={500}
                        effect='solid'
                        globalEventOff='touchstart'
                        className='footnote'>
                        {this.props.children}
                    </ReactTooltip>
                </Portal>
                <style jsx>{`
                    a {
                        cursor: pointer;
                    }
                    sup {
                        color: #060;
                        border: 1px solid #000;
                        padding: 0 1px;
                        margin: 0 3px;
                    }
                    :global(.footnote) {
                        max-width: 50vw;
                    }
                `}</style>
            </React.Fragment>
        );
    }
}
```
The Portal element is a ReactDOM.createPortal portal, and places the tooltip in a div called tooltip-root in the very beginning of the <body> element. I think I recall that this was done to make the tooltip work in e.g. modals.

Regardless - I thought I would add my code, perhaps my case is similar to the Tyler's. As I said, it used to work, but does not anymore. Am I using it correctly?

I have not yet tried the fix Tyler proposed.
