### ISSUE TITLE
How can I dynamically increase the height of the tooltip based on the content

### ISSUE THREAD

**Issue by alex6633** [ReactTooltip/react-tooltip#484]

**Comment by aronhelser** [comment]
Can you please be more specific about what content you are trying to display, using what method, and what is not working?

**Comment by pswaroopk** [comment]
I have a similar issue, where the the text is just overflowing out of the toopTip container. Instead, I want the tool tip with fixed width and the height to increase based on content instead of single line text.

**Comment by icymoonicy** [comment]
Same as above, currently the tooltip only accept <br /> to start a newline, however it could introduce issues for user who uses smaller screen resolution. 
I think maybe it's better to implement a "maxwidth" props so we can control the style easier.
Thanks.
