### ISSUE TITLE
Tooltip rendering always at the border of the canvas

### ISSUE THREAD

**Issue by samisofttech** [ReactTooltip/react-tooltip#486]
<img width="576" alt="tooltipissue" src="https://user-images.githubusercontent.com/5120017/55869813-e407ee80-5ba4-11e9-9143-f7bdf3175eaa.png">

![image](https://user-images.githubusercontent.com/5120017/55869947-2a5d4d80-5ba5-11e9-9753-1aeb94ce658f.png)

my tooltip is always rendering at the top border of the canvas window even if i change the place of it.

my code snippet -:
<React.Fragment>
           <span class="ds-icon-help ds-icon-button-dark" data-tip='' data-for={id+'_tooltip'} tabindex="0" role="text" aria-label="help"></span>
             <ReactTooltip id={id+'_tooltip'} place="bottom" type="dark" effect="solid">
                <span>{title}</span>
             </ReactTooltip>
        </React.Fragment>

**Comment by PeterMK85** [comment]
Facing the same issue:
![image](https://user-images.githubusercontent.com/3931377/55879831-cbe1a080-5b9f-11e9-88a5-3b5c93584346.png)

Basically the position of the tooltip is placed outside the current viewport.

**Comment by hemavidal** [comment]
This issue was not in the version 3 I will need to downgrade from v4 to v3. :(
