### ISSUE TITLE
Postioning fails when the target is positioned with absolute

### ISSUE THREAD

**Issue by developdeez** [ReactTooltip/react-tooltip#497]
I want a simple '?' tot he top right of all of my fields like many apps. But when I tried this the tool tips always shows in the top left.

How can I either position it according to the target or at least control when it shows?

**Comment by gilnoiman** [comment]
same problem for me

**Comment by Anshr** [comment]
same here

**Comment by Aarbel** [comment]
same here

**Comment by Aarbel** [comment]
I switched to https://github.com/atomiks/tippyjs-react, it works well with absolute elements.

**Comment by codercodingthecode** [comment]
@Aarbel , thanks for the *tip :) 
this lib straight out of the box allows me to do bottom start, which is the feature I need.
