### ISSUE TITLE
How to manage tooltip's position

### ISSUE THREAD

**Issue by ghost** [ReactTooltip/react-tooltip#510]
I use React Calendar heatmap library with React Tooltip and SrollView
When I hover mouse through this square, obviously it's correct. 
<img width="494" alt="Screen Shot 2019-09-03 at 10 23 12" src="https://user-images.githubusercontent.com/37132564/64142185-1efd0e00-ce35-11e9-8eed-9d16c97929ad.png">
But when I scroll with horizontal scroll, the position of the tooltip is not correct with the image below:
<img width="493" alt="Screen Shot 2019-09-03 at 10 23 34" src="https://user-images.githubusercontent.com/37132564/64142241-62f01300-ce35-11e9-9b38-96ff76718cc0.png">

Could anyone help me with this problem, please? How can I fix this?

**Comment by AlexeySafronov** [comment]
Just use scrollHide prop.
