### ISSUE TITLE
Can i render the tooltip on root container scope, not in the component where the tooltip eventable element located?

### ISSUE THREAD

**Issue by jiskreq** [ReactTooltip/react-tooltip#511]
I need the tooltip to be over  some neightbors divs (sidebars headers, or other components from other scope, that for some reasons has another z-index, fixed positions or something).
I there the way to force the tooltip component be appended to most parent html scope , so the tooltip will overlap other components? 
And allow keep the tooltip event caller element in deep child components as usual.

**Comment by jameschetwood** [comment]
@jiskreq did you ever find a workout for this?

**Comment by globad** [comment]
We still need this feature! Or has that already been implemented?

**Comment by danielbarion** [comment]
@globad this is an issue from 2019, related to v4 or less.

Please take a look at our docs related to v5.

Thanks!
