### ISSUE TITLE
Wrong tooltip position in Firefox/Safari when assigned to element not wholly visible.

### ISSUE THREAD

**Issue by drzamich** [ReactTooltip/react-tooltip#512]
I was testing the tooltip assigned to a text cropped with ellipsis. On Chrome it is positioned nicely. On Firefox and Safari however, its position is calculated wrong. This when `effect="solid"` and `placement="top|bottom"`

**Correct position (Chrome)**
![image](https://user-images.githubusercontent.com/26330688/64795375-47e07a00-d57e-11e9-8a0d-50959834258c.png)

**Wrong position (Firefox, Safari)**
![image](https://user-images.githubusercontent.com/26330688/64795350-3dbe7b80-d57e-11e9-9bc0-896bd6b5401d.png)

I have discovered that the reason for that is how browsers understand the `Element.getBoundingClientRect().width`. In Chrome is is the portion of `width` visible to the user. In Firefox / Safari is the total `width`, including the hidden part.

**Chrome**
![image](https://user-images.githubusercontent.com/26330688/64795798-f84e7e00-d57e-11e9-8070-40aae8e190a4.png)

**Firefox / Safari**
![image](https://user-images.githubusercontent.com/26330688/64795846-08665d80-d57f-11e9-9bea-48dc2770dcc8.png)

**Comment by ptaberg** [comment]
Obviously this is a purely browser problem. It should to be fixed based on the HTML tag I guess.

**Comment by exsesx** [comment]
We're targeting Safari (many people are), so we must fix this. 

Does anybody have plans to work on this, or will it not work in Safari? If so, why?
