### ISSUE TITLE
tooltip overridePosition arguments are inconsistent

### ISSUE THREAD

**Issue by gagandeepgill** [ReactTooltip/react-tooltip#516]
I'm trying to get the `offsetWidth` of the element to properly adjust the position of the tooltip depending on the length of the text. But the `overridePosition` call happens twice for `showTooltip` and `updatePosition`. Where it gives me the incorrect offsetWidth the second time.

https://github.com/wwayne/react-tooltip/blob/ccb8b58a6762f3393f7d71c157c64ae24a81674c/src/index.js#L313-L314

https://github.com/wwayne/react-tooltip/blob/ccb8b58a6762f3393f7d71c157c64ae24a81674c/src/index.js#L489-L490

---

This is what it gives me using `currentTarget.offsetWidth` in `overridePosition` callback.

```ts
overridePosition={({ left, top }, _currentEvent, currentTarget) => {
	console.log('currentTarget', currentTarget.offsetWidth);
	if (position === 'left') {
		left = left + currentTarget.offsetWidth * 0.25;
	}
	if (position === 'right') {
		left = left - currentTarget.offsetWidth * 0.25;
	}
    return { top, left };
}}

```
<img width="433" alt="Screen Shot 2019-10-11 at 11 43 32 AM" src="https://user-images.githubusercontent.com/8551508/66665354-5fae2b00-ec1c-11e9-978e-9620cb88b46f.png">

---

The workaround I did to get the correct offsetWidth.
```ts
overridePosition={({ left, top }) => {
	// Gets the element's width to be used to adjust the positioning of
	// the tooltip dependent on the Popover position prop
	const element = document.getElementById(id || uid);
    const tooltipWidth = element ? element.offsetWidth : 0;

	if (position === 'left') {
		left = left + tooltipWidth * 0.25;
	}
    if (position === 'right') {
		left = left - tooltipWidth * 0.25;
    }
    return { top, left };
}}
```

**Comment by Rogger794** [comment]
Hi @gagandeepgill could you please try the last release?
