### ISSUE TITLE
Ternary renders prevent tooltip from opening. 

### ISSUE THREAD

**Issue by mazer-rakham** [ReactTooltip/react-tooltip#517]
` {auth.user && auth.user[0].privilege_level < 5 ? (
        <Menu.Item
          name="Pending Tickets"
          data-tip="Pending Data Ops"
          as={Link}
          to="/pending-data-ops"
        >
          <Icon name="address card" />
        </Menu.Item>
      ) : null}`

The above code renders the menu item based on the user level. The Ternary wrapper stops the tooltip from rendering.
This can be avoided by adding the data-tip prop to a wrapper above the ternary, maybe not a bad issue, might want to put in docs? I dunno take this info and do with it what you need lol.

This works:
`<div data-tip="Pending Data Ops">
        {auth.user && auth.user[0].privilege_level < 5 ? (
          <Menu.Item name="Pending Tickets" as={Link} to="/pending-data-ops">
            <Icon name="address card" />
          </Menu.Item>
        ) : null}
      </div>`

**Comment by liskoX** [comment]
Hello, you have to rebuild the tooltip component with ReactTooltip.rebuild() (i did this after setState)

I did and worked for me, i can't do your solution with my code because of the structure is a quit different. hope it will help you

**Comment by mazer-rakham** [comment]
Awesome, I will try that out. Thank you!

**Comment by dimitrisraptis96** [comment]
It worked for me too. Adding it to the docs would have saved me a lot of time.

**Comment by aronhelser** [comment]
Pull request welcome! Add it where you think it's helpful and I'll get it
in.

**Comment by dimitrisraptis96** [comment]
Sure. Once I find some time, I'll open a PR
