### ISSUE TITLE
Bug: Maximum update depth exceeded

### ISSUE THREAD

**Issue by kukchanka** [ReactTooltip/react-tooltip#527]
I believe there is an issue with `getPosition` fucntion which is used to update tooltip position when it's outside the client widnow.

There are situations with floating tooltip (e.g. when we move cursor to the bottom of the page) when it cannot be displayed, so it tries to calculate a new `desiredPlace` and rerenders the component, but after rerendering `getPosition` finds out, that a previously calculated `desiredPlace` doesn't allow to render tooltip inside the client window, so it calculates a new one, which turns out to be the one we started with. It starts switching back and forth and "maximum update depth exceeded" error occurs.

To demostrate this, I added a pair `console.log`s inside `getPosition` and moved the cursor over tooltiped element:
![image](https://user-images.githubusercontent.com/26742796/71765305-f466b300-2f03-11ea-85e5-ced590e2dead.png)
This is what I got in my console just right before "Maximum update depth exceeded" error:
![image](https://user-images.githubusercontent.com/26742796/71765322-2c6df600-2f04-11ea-886c-198acd904847.png)

**Comment by kukchanka** [comment]
Created a pull-request fixing this issue: https://github.com/wwayne/react-tooltip/pull/528

**Comment by Zemelia** [comment]
Issue still exists, it was returned after fix in https://github.com/wwayne/react-tooltip/issues/574

**Comment by pankajgandhi1010** [comment]
UpdatePosition() shows Error : Maximum update depth exceeded.
