### ISSUE TITLE
3.11.3 breaks CommonJS require

### ISSUE THREAD

**Issue by tylerthegrove** [ReactTooltip/react-tooltip#543]
We use this in an older component that still uses syntax var ReactTooltip = require("react-tooltip"); 3.11.3 broke this component for all of our library users.

Looks like the module.exports was changed to export default though the comment above says "/* export default not fit for standalone, it will exports {default:...} */"

https://github.com/wwayne/react-tooltip/commit/08289a8de72598f0c1e5ef8c972ea67e85dc178a#diff-1fdf421c05c1140f6d71444ea2b27638R615

And the .babelrc explicitly says "modules:false". Was there a reason for this change? @Rogger794 

https://github.com/wwayne/react-tooltip/commit/08289a8de72598f0c1e5ef8c972ea67e85dc178a#diff-e56633f72ecc521128b3db6586074d2cR7

**Comment by tylerthegrove** [comment]
In my opinion this change should not have been made in a patch version.

**Comment by Rogger794** [comment]
Hi @tylerthegrove, the change was thought to replace the standalone with the new version using rollup by using export default for name your variable reference as you want.

**Comment by tylerthegrove** [comment]
@Rogger794 A breaking change like that should probably wait for a major version, but **never** be part of a patch version.

We automatically pull patch versions with the expectation that they only contain bug fixes and are backwards compatible. This broke for all projects using our shared library. I'd suggest adding `{modules: true}` to the .babelrc and waiting for 4.0.0 for a breaking change.

**Comment by Rogger794** [comment]
@tylerthegrove, would you make a PR with the changes that fit your issue? Later I will upgrade the release to 4.0.0 with the original new configuration. Seems that after the merge for the rollup build, versioning automatically upgrade as a patch version for the semantic release package.

**Comment by gersongams** [comment]
@tylerthegrove maybe this [link](https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6) can help you .

**Comment by tylerthegrove** [comment]
Thanks @gersongams but I know what the issue is. My point is just that there shouldn't be breaking changes like this in patch versions.

Likely we will move away from this package to prevent breaks in the future.
