### ISSUE TITLE
React Tooltip Positions wrong

### ISSUE THREAD

**Issue by dineshit8** [ReactTooltip/react-tooltip#547]
Hi,

I have implemented react tooltip in my react project. When I am hovering the dom the tooltip left and top positions calculations are irrespective of the target dom. It positions somewhere in the bottom of the page which is not visible on the screen,(say, the left position is something like 1400px and the top position is like 1200px).

Someone please help me to resolve this issue.

My code:

 ```
<div className="logoutContainer" data-tip='tooltip'>
        <div className="logoutIcon" title="Logout" onClick={logoutAction} >
        </div>
        <ReactTooltip place={"right"} multiline={true} />
      </div>
```

**Comment by Rogger794** [comment]
Hi @dineshit8, could you please try the last release?
