### ISSUE TITLE
avoid using window for SSR

### ISSUE THREAD

**Issue by BjoernRave** [ReactTooltip/react-tooltip#554]
When using this lib with next.js I get the following error:

```
 /Users/bjoern/projects/compendium2/node_modules/react-tooltip/dist/index.js:1072
[1]   if (typeof window.CustomEvent === "function") {
[1]   ^
[1] 
[1] ReferenceError: window is not defined
[1]     at dispatchGlobalEvent (/Users/bjoern/projects/compendium2/node_modules/react-tooltip/dist/index.js:1072:3)
[1]     at Function.target.rebuild (/Users/bjoern/projects/compendium2/node_modules/react-tooltip/dist/index.js:1102:5)
[1]     at Timeout._onTimeout (/Users/bjoern/projects/compendium2/frontend/.next/server/static/development/pages/compendium/[slug].js:6594:60)
[1]     at listOnTimeout (internal/timers.js:531:17)
[1]     at processTimers (internal/timers.js:475:7)
error Command failed with exit code 1.
```

The problem exists, because on the server side window is undefined

**Comment by pierregee** [comment]
This error is not being thrown when I tried it with ` "react-tooltip": "4.0.3"` with `"next": "9.1.7"` 
Although, one problem I'm having is the tooltip being rendered on the server as a div outside (see screenshot) and only works properly once it finishes rendering at the client side. I'm curious if react-tooltip actually supports SSR? 
![image](https://user-images.githubusercontent.com/13292662/75750281-d4fed180-5d5e-11ea-978a-e02f2e73bd7b.png)

**Comment by Rogger794** [comment]
Hi @pierregee, actually it's not supported yet, because of the use of window variable that doesn't exist un server side.

**Comment by aronhelser** [comment]
Can we just switch `window` for `global` ? IDK anything about SSR.

**Comment by Rogger794** [comment]
Yeah, I saw before that it could be implemented as a util. I would check it.

**Comment by ndom91** [comment]
Normally you can check if `typeof window !== 'undefined'` if its currenlty running in the server or Browser. So, for example:

```jsx
{typeof window !== 'undefined ? (
  <ReactTooltip />
) : (
  <Loader />
)}
```

**Comment by LauraBeatris** [comment]
I have been tried to use it with SSG/SSR render frameworks and the way that I handling this is by returning null if ``window`` is ``undefined``

**Comment by LauraBeatris** [comment]
I'm not having problems with ``window`` but instead, with the ``document`` refer to #618
