### ISSUE TITLE
targetWidth smaller than tipWidth produces invalid position

### ISSUE THREAD

**Issue by TotallWAR** [ReactTooltip/react-tooltip#561]
When targets DOM element's width is smaller than tip's width - tooltip is placed incorrect. Its position is negative.

`overridePosition` function's parameters `currentEvent` `currentTarget` are equal nodes in this case.

My data-for DOM element is dinamically changed, and when this DOM element changed to smaller size (data-for is changing too) for the same tooltip - position is incorrect.

Rebuild doesn't help.

**Comment by Rogger794** [comment]
Hi @TotallWAR, could you plea put an example or use [codesandbox](https://codesandbox.io/) and share what is happening.
