### ISSUE TITLE
Tooltip does not show up again after hide on ios when virtual keyboard closes

### ISSUE THREAD

**Issue by itmart** [ReactTooltip/react-tooltip#589]
When the virtual keyboard disappears, the tooltip appears on top of the page for a second and disappears . After that, clicking on the span to show the tooltip does not show it anymore. I'd have to click somewhere else first before clicking on the span again for the tooltip to show.

Is there a way around this?

EDIT: I tried adding `position: absolute` to the tooltip and it doesn't show on the top of the page anymore. However, it still disappears when the virtual keyboard closes and won't open again until I tap somewhere else first then tap on the icon for the tooltip again.

**Comment by sashabur** [comment]
@itmart have you found a solution?
