### ISSUE TITLE
Closing existing tooltips when opening a new tooltip

### ISSUE THREAD

**Issue by aspdev91** [ReactTooltip/react-tooltip#590]
Hi, I'm running into an issue where if you already have a tooltip open and click on another button that activates a tooltip, you will have two tooltips open. If you click outside the tooltips, all open tooltips close which works as intended. How do I close existing tooltips when a user clicks on the button that opens a new tooltip?

I tried running this code within the onClick behavior on the buttons and surrounding divs as suggested by the docs, but it wouldn't close existing tooltips:

`ReactTooltip.hide();`

`ReactTooltip.hide(target)
Hide the tooltip manually, the target is optional, if no target passed in, all existing tooltips will be hidden`

**Comment by SParmentier** [comment]
Hi @aspdev91, I'm running into the same problem. Did you find the solution ?

Thank

**Comment by ronmara** [comment]
try to add   
componentDidUpdate() {
    ReactTooltip.rebuild();
  }

**Comment by SParmentier** [comment]
It didn't help for me.
In my case, when I click on another tooltip, the 'click' event isn't popping up. So the ReactTooltip.hide function is never called (Mostly explaining why nothing is closed in that case).
Is that possible that the event is catch in react-tooltip and its propagation is stopped ?

**Comment by ministerface** [comment]
Hi. I solved this problem by simply adding a property isCapture={true}

**Comment by EdgarKisman** [comment]
> Hi. I solved this problem by simply adding a property isCapture={true}

Thanks, worked for me.
