### ISSUE TITLE
Tooltip does not show on Safari-IOS browser when set the effect prop to solid

### ISSUE THREAD

**Issue by hoangnm** [ReactTooltip/react-tooltip#591]
I tested on Safari-IOS, it won't show the tooltip if I set the `effect` prop to `solid`.

**Comment by msjh80311** [comment]
+1
Can anyone help with this?

---

## How to reproduce
1. More than 1 tooltips on a page
2. On iPad/iPhone
3. Set the `effect` prop to `solid`
4. Click on the tips, everything looks fine at first.
5. Click on the tips again. The tooltip contents become invisible.


## Expectation
Showing solid tooltips correctly every time when clicking on the tips.


## More information
1. **The first tooltip** on a page behaves correctly.


## Version
- react-tooltip@4.2.21
