### ISSUE TITLE
assing props textColor or backgroudColor to the <ReactTooltip /> is not working

### ISSUE THREAD

**Issue by riteshbathwal** [ReactTooltip/react-tooltip#594]
Below is my code where I am using ReactTooltip. When trying to customise it by passing props textColor and backgroundColor , both are not appllied, instead default background-color of black and textColor of white is only getting applied. Please help.

<NavLink style={{textDecoration:'none'}} 
                                to={CONSTANTS.PREVIEW_CONFING_PATH}
                                onClick={this.handlePreviewClick}
                            >
                                {/* <CustomTooltip title="Preview" aria-label="preview extraction configuration"> */}
                                    <CustomIconButton 
                                        data-tip 
                                        data-for="previewGroupId" 
                                        disabledRipple={true} size={'small'}>

                                        <NPreviewIcon 
                                            className={[isPreviewDisabled ? 
                                            Styles.disabledPreview : ''].join(' ')} 
                                            fill= {isPreviewDisabled ? '#888' : '#333'} 
                                        />
                                    </CustomIconButton>

                                    <ReactTooltip id="previewGroupId"
                                        backgroundColor="yellow"
                                        textColor="white"
                                    >
                                        <span>Click to preview</span>
                                    </ReactTooltip>

                                {/* </CustomTooltip> */}

                            </NavLink>

**Comment by gabibianconi** [comment]
Still happening!

**Comment by NisanAyash** [comment]
any solution for this issue?
