### ISSUE TITLE
Window Event Listeners causing performance problems when many tooltips are rendered

### ISSUE THREAD

**Issue by jonmajorc** [ReactTooltip/react-tooltip#596]
"resize" is showing 149
![image](https://user-images.githubusercontent.com/7799266/81852820-3a223080-9521-11ea-8ada-c5b21ab1ddb5.png)

When I set `resizeScroll={false}`  `resizeHide={false}` it helps a bit with rendering... but still have issues with having all those listeners `__react_tooltip_*` listeners.

After turning off props "resize" looks better, but the `__react_tooltip_*` listeners are still at a high number.
![image](https://user-images.githubusercontent.com/7799266/81852741-1d85f880-9521-11ea-95d3-c64467a83acd.png)

**Comment by klinskyc** [comment]
I ran into this same issue, and ended up using https://www.npmjs.com/package/rc-tooltip as an alternative.
