### ISSUE TITLE
Can't make it work onClick

### ISSUE THREAD

**Issue by JorgeSivil** [ReactTooltip/react-tooltip#600]
I might be very stupid but I can't make it work... it's been like an hour yet the tooltip keeps showing.

I have a button, and the tooltip.
```
  const tooltipRef = useRef(null);

<button
        className={styles.actionButton}
        onClick={() => {
          ReactTooltip.show(tooltipRef);
        }}
        data-tip=""
        data-event="click"
      >

<ReactTooltip type="error" ref={tooltipRef}>
        <span>Show happy face</span>
      </ReactTooltip>
```
I want to control when the tooltip displays or not, and I am not being able to control it. It automatically displays. What am I doing wrong?

**Comment by oran1248** [comment]
Can't make it work either. I think the ref should be on the button and not on ReactTooltip.

**Comment by JorgeSivil** [comment]
Yeah tried that also, but either 1 of two, it was showing automatically, or it wasn't working

**Comment by oran1248** [comment]
After few hours of struggling with this lib, I came to a conclusion that the best solution is to write a tooltip component my self :)

**Comment by JorgeSivil** [comment]
Yeah that's what actually happened to me. https://www.cssportal.com/css-tooltip-generator/ and that's it haha

The problem is that I only found this library, or other bigger libraries that have a lot of things that I don't need now, like Reactstrap or material UI

**Comment by oran1248** [comment]
You dont have to use a library, just create your own simple component.

**Comment by talesdsp** [comment]
I believe your showcase isn't working because you passed the entire `ref`, instead of `ref.current`.

The following worked for me!

```
const idRef = useRef(null);

 <button
            ref={idRef}
            data-tip="Copied!"
            onClick={() => ReactTooltip.show(idRef.current)}
          >
            
          </button>
          <ReactTooltip
            type="success"
            event="click"
            eventOff="blur"
            delayShow={100}
            delayHide={500}
            place="bottom"
          />```
