### ISSUE TITLE
[Feature Request] Option to not display tooltip on mobile/touch devices

### ISSUE THREAD

**Issue by andrewchmr** [ReactTooltip/react-tooltip#605]
Hi, first of all thank you for react-tooltip!

I think it would be nice to have an option to not render tooltip on mobile/touch devices (eg. `hideOnMobile` prop), so users don't have to implement it manualy (eg. `if(isMobile()) return null`).

**Comment by gap777** [comment]
In the meantime, we're doing this in our render methods:

```
const isMobile = /Mobi|Android/i.test(navigator.userAgent)
return <ReactTooltip id={tipId} place={place} delayShow={1000} className='button-tooltip' effect='solid' globalEventOff={isMobile ? 'click' : undefined}>
```

**Comment by danielbarion** [comment]
Hi guys, this will be handled on V5, thanks!
https://github.com/ReactTooltip/react-tooltip/discussions/812

**Comment by danielbarion** [comment]
Hi guys, I think about this and I realized this should be a project logic and not logic inside the tooltip, so, with this controlled state you guys can handle that in V5: https://react-tooltip.com/docs/examples/state

I'll close the issue, please create a new one if necessary.

Thanks!
