### ISSUE TITLE
React tooltip showing Inside in Model

### ISSUE THREAD

**Issue by mdmusaib** [ReactTooltip/react-tooltip#607]
Hi, 
I have a Model in which I have specifically given position:fixed, and overflow:'hidden", if I try to show the tooltip in that model it is showing inside because the model is overflow:hidden , I want to view the tooltip outside like normal, how to fix this issue......

**Comment by ShanikaEdiriweera** [comment]
@mdmusaib Refer #130 Tooltip not placed properly if in modal. (Assuming you are talking about a Modal)
