### ISSUE TITLE
Tooltip remains on screen after link clicked to a new URL

### ISSUE THREAD

**Issue by scalarmapedia** [ReactTooltip/react-tooltip#608]
In our App, we have Tooltips used on both icons and text labels that are links to other pages in the same app. When hovered overthe Tooltip appears as expected. But when you click the link, the page/url changes, but the Tooltip remains visible, and remains visible until the page app is browser refreshed.

**Comment by xrendan** [comment]
This is super hacky, but it worked for me: 

```
// This is necessary to prevent tooltips from hanging on clicks 
// See: https://github.com/wwayne/react-tooltip/issues/608
let hideTooltips = () => {
    ReactTooltip.hide()
    setTimeout(
        () => {
            ReactTooltip.rebuild();
            ReactTooltip.show();

        },
        100
    )
}


   <NavLink to="/" className="nav-link collapsed text-black-50" onClick={hideTooltips}>
```
