### ISSUE TITLE
How to hide the tool tip after some delay

### ISSUE THREAD

**Issue by vishalDenzil26** [ReactTooltip/react-tooltip#616]
When am clicking the button am able to show tool tip. after some time i gave delayHide = 1000 still its not dispapearing .

**Comment by aronhelser** [comment]
Have you looked at the code on the example page? Is your code the same or
different?

**Comment by OCmilo** [comment]
That's how I managed to do it after some trial and error:
```
<ReactTooltip
          id="copy-tooltip"
          place="right"
          effect="solid"
          event="click"
          delayHide={2000}
          afterShow={() => ReactTooltip.hide()}
        />
```

You need to set the `afterShow` prop to () => `ReactTooltip.hide()`. It will close after the given delay
