### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by LauraBeatris** [ReactTooltip/react-tooltip#618]
I'm not able to use the tooltip component with SSR libraries lib such as ``react-static``

Because it relies on a document that is not available during build.

![Screen Shot 2020-07-18 at 19 42 59](https://user-images.githubusercontent.com/48022589/87863182-e96af180-c92e-11ea-8bc6-51bb0eb80e2d.png)

**Comment by patrickjsmirnov** [comment]
Same problem
