### ISSUE TITLE
Hide tool-tip after x milliseconds

### ISSUE THREAD

**Issue by itamardavidyan** [ReactTooltip/react-tooltip#630]
There is an option to add an attribute 'hideAfter' that get number of milliseconds that after them the tool-tip disappear?

**Comment by proful** [comment]
`import debounce from 'lodash/debounce'  

const hideTooltip = debounce(() => {
    ReactTooltip.hide(tooltipSourceRef.current)
  }, 4000)`

**Comment by proful** [comment]
```
import debounce from 'lodash/debounce'  

const hideTooltip = debounce(() => {
    ReactTooltip.hide(tooltipSourceRef.current)
  }, 4000)
```
