### ISSUE TITLE
Certain conditions relating to window size VS tooltip placement, result in a duplicate tooltip being shown in 2 positions

### ISSUE THREAD

**Issue by iaremarkus** [ReactTooltip/react-tooltip#640]
It seems that there's an overlap in placement logic, that results in a tooltip being shown twice, in 2 positions. 

See the gif below that highlights what happens when you scroll and the tooltip becomes confused if `top` or `right` is the better placement, so it just does both :P 

![tooltip](https://user-images.githubusercontent.com/936966/97405289-18b2d680-1900-11eb-9a46-46e253664ef3.gif)

Perhaps related to [521](https://github.com/wwayne/react-tooltip/issues/521)

**Comment by boly38** [comment]
duplicate tooltip related another issue: #645
