### ISSUE TITLE
Tooltip not appearing when using ReactTooltip.show

### ISSUE THREAD

**Issue by aspdev91** [ReactTooltip/react-tooltip#641]
I'm trying to open or make a tooltip visible manually based off the value of a React prop. I'm not able to make it to appear even with ReactTooltip.show(this.viewToolTip). Does anyone have any tips or sample code on getting this to work?

**Comment by linxux** [comment]
Just fork someone's code snippet and add the `manually` show/hide tooltips.
Hope this can help you.

[![Edit reverent-beaver-2vc5s](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-beaver-2vc5s?fontsize=14&hidenavigation=1&theme=dark)
