### ISSUE TITLE
No style on tooltip when rendered in React Fragment

### ISSUE THREAD

**Issue by mawilmouth** [ReactTooltip/react-tooltip#643]
When rendering a tooltip next to the target element in a React Fragment, the tooltip is not styled. Upon hovering, the tooltip does appear but does not have any styles applied to it. When I wrapped them in a div, it worked fine. I understand that this may not be a huge issue but I do think that a Fragment wrapper should be handled. 

# This does not work
```
<React.Fragment>
   <div
     data-tip
     data-for="githubTest"
     data-testid="ownershipIconContainer"
   >
        <p>hover me</p>
   </div>
   <ReactTooltip
     type="dark"
     effect="solid"
     place="top"
     id="githubTest"
   >
        <p data-testid="ownershipTipText">{ownershipText}</p>
   </ReactTooltip>
</React.Fragment>
```

# This works
```
<div>
   <div
     data-tip
     data-for="githubTest"
     data-testid="ownershipIconContainer"
   >
        <p>hover me</p>
   </div>
   <ReactTooltip
     type="dark"
     effect="solid"
     place="top"
     id="githubTest"
   >
        <p data-testid="ownershipTipText">{ownershipText}</p>
   </ReactTooltip>
</div>
```

**Comment by lordvcs** [comment]
Same issue here too

**Comment by lordvcs** [comment]
https://github.com/wwayne/react-tooltip/issues/610#issuecomment-654349371
this solved the issue for me <ReactTooltip uuid="<some-uuid-here>" />
