### ISSUE TITLE
When scrolling after putting mouse pointer to tooltip, tooltip is not hidden.

### ISSUE THREAD

**Issue by efkandurakli** [ReactTooltip/react-tooltip#646]
![tooltip](https://user-images.githubusercontent.com/23101629/99661294-af446480-2a74-11eb-8206-f91f4eb36ef2.gif)

**Comment by rocioDEV** [comment]
Same here :(

**Comment by rickyzhangca** [comment]
`isCapture` fixed it for me

**Comment by p-arth** [comment]
`isCapture` didn't work for me, already made a lot of research regarding that, nothing seems to override this behavior.

**Comment by DzianisPazharytskiTR** [comment]
@p-arth hi! Did you find the solution? Just faced with the same problem...

**Comment by DzianisPazharytskiTR** [comment]
Btw this helped me guys - https://github.com/ReactTooltip/react-tooltip/issues/449
