### ISSUE TITLE
Html option (data-html) is not working

### ISSUE THREAD

**Issue by AlexandreMouyen** [ReactTooltip/react-tooltip#649]
Hello there,

I am trying to render an html content for my tooltip using _html_ prop but it is rendering an "object [Object]".

Even with the commented line.

With a simple text as _data-tip_ it is working correctly.

```jsx
const Popover = ({ children, content, title, trigger }) => {
  return (
    <>
      {React.cloneElement(children, {
        'data-tip': <p>This is a test</p>,
        'data-for': 'foo',
        // 'data-html': true,
      })}
      <ReactTooltip id="foo" html />
    </>
  );
};
```

Can anyone help me? Did I miss something?

Thanks.

**Comment by LeoLetourneur** [comment]
Hello,

I have a problem using html=true and <br>. If I use <br>, it displays "[Object, object], [Object, object]".
If I remove it, it's fine.

**Comment by kennybecerra** [comment]
@AlexandreMouyen I think your HTML needs to be a string. 

@LeoLetourneur I am having the same issue. Tooltip displays "[Object, object], [Object, object]"  if I have a <br /> tag  inside my HTML

**Comment by hellofanny** [comment]
helloo, maybe you can try using an alias 🤔:

```
const test = '<p>This is a test</p>'

return (
    <>
      {React.cloneElement(children, {
        'data-tip': <p>This is a test</p>,
        'data-for': 'foo',
        // 'data-html': true,
      })}
      <ReactTooltip id="foo" html />
    </>
 );
```

**Comment by jasur-n** [comment]
@LeoLetourneur @UnumIDAdmin Have you tried to add a `multiline` prop? In **[Options](https://github.com/wwayne/react-tooltip#options)** list there is a prop's definition: 

![image](https://user-images.githubusercontent.com/66470467/119473067-3cd67900-bd64-11eb-807f-79652a814e8b.png)

I hope it will solve yout problem!

**Comment by nimeetshah0** [comment]
Worked around this issue by putting my strings in the `<p>` tag. One tag per line.

**Comment by sarah-lancaster-springload** [comment]
It's not super obvious from the docs but even if you are wanting HTML to be rendered inside the tooltip, it still needs to be in a string (wrap your HTML in backticks). Setting the html prop on the tooltip under the hood sets dangerouslySetInnerHtml on the string you pass in.

```
const inner = `<p>I'm html in a string</p><p>Same</p>`

```
and your tooltip:

```
 <ReactTooltip
    html={true}
    id={"tooltip"}
    place="right"
    type="dark"
    effect="solid"
  >
    {inner}
  </ReactTooltip>
  ```
