### ISSUE TITLE
question: multiple tooltips for different types of data events

### ISSUE THREAD

**Issue by bolducp** [ReactTooltip/react-tooltip#654]
Thanks so much for your work on this great library!

I haven't been able to find anything in the docs or to get this to work locally on my own, so perhaps it isn't possible, but I thought I'd ask just to be sure.

Is there anyway to have an element that corresponds to two different tooltips? Specifically, I would like for one message to appear in a tooltip when I `hover` over the element, and I would like for different content to appear when I `click` on the element.

Thanks!

**Comment by IGOLz** [comment]
Up

**Comment by danielbarion** [comment]
Hi, can you guys take a look at V5 PR, please? https://github.com/ReactTooltip/react-tooltip/pull/820

Also, in V5, you guys can use this doc for this case, in the example we are changing the anchor, but if we change the anchor or the content, the tooltip will be updated, so, you can manage the content as you want.

https://react-tooltip.com/docs/examples/state
