### ISSUE TITLE
Tooltip doesn't close when another is displayed

### ISSUE THREAD

**Issue by Gus-2** [ReactTooltip/react-tooltip#655]
I have a <td> balise that contains the data-event="click" that trigger the Tooltip when clicked. 

Inside this td, I have a the Tooltip component balise that has the attribute globalEventOff="click" and work only if I click outside anything that trigger a tooltip. But when I click on another <td>, it opens another tooltip but doesn't close the tooltip opened before.

I saw on a stack post that I can use the {'focusout'} but didn't work.

How can I fix that ?

`<TableContentTdBoldClickable key={week} data-for={i} data-event="click" data-tip>{datas[key][week]}
                                                    <ReactTooltip id={i} globalEventOff='click' place="right" clickable={true}>
                                                        <ExpandViewDetailClient week={week} title={INTAKES} />
                                                    </ReactTooltip>
                                                </TableContentTdBoldClickable>`

**Comment by amittras-pal** [comment]
Is there an update on this issue. 
We require a similar functionality hwere there should be only one tooltip instance displayed on the screen. 
However, I can open multiple tooltips simultaneously. 

A workaround would also be appreciated.

**Comment by DvoeglazovIlya** [comment]
The same problem. 
Any ideas how to hide another toolpips or maybe add z-index higher then other toolpips?

**Comment by DvoeglazovIlya** [comment]
Maybe it help, add  isCapture={true} to your tooltip
https://github.com/wwayne/react-tooltip/issues/590

**Comment by danielbarion** [comment]
Hi,

Closing this issue due to: https://react-tooltip.com/docs/examples/state

You guys can handle the state of the tooltip in V5 or higher and show which tooltip you want, please open a new issue if necessary.

Thanks!
