### ISSUE TITLE
Nested elements with tooltip

### ISSUE THREAD

**Issue by eugenest** [ReactTooltip/react-tooltip#680]
Hi!

I have 2 divs with tooltips

```
<div data-tip={tooltipContent1}>
    <div data-tip={tooltipContent2}/>
</div>

```

but when I move cursor from child div to parent div tooltip data doesn't change

this is how it looks: https://prnt.sc/10h83bt

reproducible demo: https://codesandbox.io/s/react-tooltip-example-3116-forked-kh0oy

is there a way to solve this?

**Comment by dmikester1** [comment]
I am encountering basically the exact same issue.  The only difference is that I am using the solid effect to keep the tooltip stationary.  So I when I move back to the parent element, the tooltip doesn't show up at all.

**Comment by dmikester1** [comment]
Just thinking aloud here.  I feel like I need to add a 'onMouseLeave' event to the child component. Because there is no trigger to show the tooltip again because the mouse is still in the parent and is not re-entering the parent to trigger the tooltip to show again.  But I don't know what I would put in that 'onMouseLeave' event.

**Comment by XDSeverussnape** [comment]
How i can use `ReactTooltip.show(productRef.current);` and `ReactTooltip.hide(productRef.current);` in "react-tooltip": "^5.26.4", Because my nested div element doesn't work.

**Comment by gabrieljablonski** [comment]
> How i can use `ReactTooltip.show(productRef.current);` and `ReactTooltip.hide(productRef.current);` in "react-tooltip": "^5.26.4", Because my nested div element doesn't work correctly.

@XDSeverussnape please open a new issue with some more details, and possibly with sample code to reproduce your problem.
