### ISSUE TITLE
className not overriding

### ISSUE THREAD

**Issue by A-F-V** [ReactTooltip/react-tooltip#684]
```javascript
import ReactTooltip from "react-tooltip";
import { renderMarkdownText } from "../render";

import styles from "../../styles/RefJot.module.scss";

export default function RefJot(props: {
  text: string;
  def: string;
  id: string;
}) {

  return (
    <>
      <a data-tip data-event="click focus" data-for={props.text}>
        {props.text}
      </a>
      <ReactTooltip
        place="top"
        effect="solid"
        className={styles.wrapper}
        globalEventOff="click"
        id={props.text}
        backgroundColor="#00000000"
      >
        <div className={styles.ref}>
          <p>{renderMarkdownText(props.def)}</p>
        </div>
      </ReactTooltip>
    </>
  );
}
```

I am using Next.JS and it the tooltip does not seem to be overriden by my class
The div inside with class="styles.ref" does work, but not the overall tooltip 
(I am trying to increase border radius)

**Comment by A-F-V** [comment]
I may have solved this.
You need to add !important after every css property

**Comment by danielbarion** [comment]
Hi, this will be handled on V5, thanks for the report!

https://github.com/ReactTooltip/react-tooltip/discussions/812

**Comment by danielbarion** [comment]
Hi, closing this one due to: https://react-tooltip.com/docs/examples/styling

Please open a new issue if necessary. Thanks!
