### ISSUE TITLE
Placement is not working

### ISSUE THREAD

**Issue by michaelpelagio9830** [ReactTooltip/react-tooltip#692]
Hi I'm new to react-tooltip and I'm having a hard time why placement is not working 
currently I'm using bootstrap classes.  I set place="bottom" yet in my app the tooltip still on the right side. is there something I'm missing out? I would appreciate any help.

![image](https://user-images.githubusercontent.com/48999538/113528188-73103b80-95f2-11eb-8938-c14488916d41.png)

this is the output

![image](https://user-images.githubusercontent.com/48999538/113528237-9935db80-95f2-11eb-867d-b563feca9501.png)

**Comment by aljorgevi** [comment]
same issue here

**Comment by throttlehead** [comment]
I'm seeing the exact same issue. It seems if the element is snug to a left or right edge, the placement puts it on the opposite side instead of the top.

There must be some sort of dynamic calculation going on here that would need to be overridden.

**Comment by cirex-web** [comment]
For people who are having issues with this: try using `bottom-start` or `bottom-end` instead
