### ISSUE TITLE
Request: Add option to change border radius

### ISSUE THREAD

**Issue by michaelzhu23** [ReactTooltip/react-tooltip#694]
I think it'd be useful to have a prop to customize the border radius of the tooltip.

**Comment by targumon** [comment]
Anti-Request: dear library maintainers, please don't add props unless absolutely necessary.
And in this case it's not.

@michaelzhu23 Just use the existing `className` prop 🙂
JSX:
```jsx
<ReactTooltip className='customTooltip'/>
```

CSS:
```css
.customTooltip {
  border-radius: 0;
}
```

**Comment by sgehrman** [comment]
doesn't work

**Comment by danielbarion** [comment]
hi, guys can you let me know your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074
