### ISSUE TITLE
React tooltip - text padding

### ISSUE THREAD

**Issue by Sajanrav01** [ReactTooltip/react-tooltip#697]
Hi,

Thanks for wonderful library. I am trying to change the padding of  'data-tip' but I cannot able to make it .As we can see in the screen shot i am trying to change the padding of 'Begin search' to little bit left..Please help me out of this. 

 I tried following way:

Added  below code in main.css

.customTooltipclass .__react_component_tooltip{
  padding: 8px 8px !important;
  }

and added below code in Compontent.js

<ReactTooltip id = 'mapController-tip' className="customTooltipclass"

But no luck..

**Comment by sometimescasey** [comment]
I did this by passing a function to `getContent` and the styling the div wrapping my content:

```
<ReactTooltip globalEventOff='click' 
                                        getContent={() => {
                                            return (
                                                <div className="tooltip-content">
                                                    blah blah
                                                </div>
                                            );
   }
}
                                        ...
```

and then in CSS:

```
.tooltip-content {
   padding: 1rem;
}

```

**Comment by danielbarion** [comment]
hi, guys can you let me know your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074

**Comment by danielbarion** [comment]
Hi, closing this issue due to: https://react-tooltip.com/docs/examples/styling#adding-more-padding

Please, create a new one if needed. Thanks!
