### ISSUE TITLE
The Insecure option does not work

### ISSUE THREAD

**Issue by eltoro** [ReactTooltip/react-tooltip#701]
The readme says:

> Whether to inject the style header into the page dynamically (violates CSP style-src but is a convenient default)

But looking at the code it appears to be unused. Is this correct? Is there any way to not inject the styles?

**Comment by rahulsinghk** [comment]
I am facing the same issue. ?

**Comment by simonantony12** [comment]
Insecure option is not working for me too

**Comment by shye0000** [comment]
not work for me either

**Comment by simonantony12** [comment]
I switched to  OverlayTrigger, Tooltip from react-bootstrap. It works fine with strict csp

**Comment by alexlouden** [comment]
Yeah, it's unused:

https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L149-L155

**Comment by a1sey** [comment]
If someone is still using v4, `disableInternalStyle` prop prevents styles from being injected.

**Comment by fabiolmorato** [comment]
If anyone has issues with this and cannot enable the `style-src 'unsafe-inline'` CSP rule, do this:

```jsx
import { Tooltip } from "react-tooltip";

import "react-tooltip/dist/react-tooltip.css";

export function Test () {
  return (
    <Tooltip
      // ...
      disableStyleInjection="core"
    />
  );
}
```
