### ISSUE TITLE
i hope If the mouse hovers during content update, it is optional  to update

### ISSUE THREAD

**Issue by zoe-jqq** [ReactTooltip/react-tooltip#710]
My content is a form. Every item has a delete button. After deleting, the tooltip does not automatically update the position. It is correct only when I quickly move out of the mouse position.  i have set   
```
useEffect(() => {
   ReactTooltip.rebuild();
   ReactTooltip.show(document.querySelector('.add-attendance'));
  }, [formItems]);
```
and 
`delayUpdate={200}`

In another case, there is a cancel button in the form, and it doesn't work if you click to close the tool, because the mouse thover over the tool

So I hope that the function mouseOntooltip is optional when determining whether to update the tooltip

Or is there any way to skip mouseOntooltip check?

Thanks

**Comment by zoe-jqq** [comment]
aslo  When I have a scroll bar in my form, I don't need to listenForTooltipExit

**Comment by yasin-vibely** [comment]
@wwayne  yea. sometimes we want hide directly but it waiting with `listenForTooltipExit`.
