### ISSUE TITLE
The tooltip shows underneath another component

### ISSUE THREAD

**Issue by huy1912** [ReactTooltip/react-tooltip#712]
I've used the `@devexpress/dx-react-scheduler` for the calendar and tried to show the tooltip on each schedule. But the tooltip is shown underneath  (see the below screenshot). Do you know how to fix this issue?

<img width="358" alt="Screenshot 2021-07-10 at 11 56 56 PM" src="https://user-images.githubusercontent.com/2849751/125169006-d655cf00-e1da-11eb-913f-311f45aeea94.png">

Thanks & regards,
Huy

**Comment by Sir-hennihau** [comment]
@huy1912 did you fix it already? It's also happening to me

**Comment by huy1912** [comment]
@Sir-hennihau, still haven't got the issue yet. Will share if I found the workaround for it.

**Comment by Sir-hennihau** [comment]
@huy1912 I had to fix z-index property on the div that my tooltip was hidden below. i removed it's z-index property.

if you want to keep using z-indexes keep that in mind:

Note: z-index only works on positioned elements (position: absolute, position: relative, position: fixed, or position: sticky) and flex items (elements that are direct children of display:flex elements).

**Comment by ShawnCockburn** [comment]
@huy1912 

I also had this issue, however I figured out that I was using the component incorrectly.
you haven't provided your code so I don't know if you're having the same issue, but this is what fixed it for me.

do this:
```js
    <>
      <BiInfoSquare
      size={22}
      // place the text you want to display in the 'data-tip' 
      data-tip={text}
      // make sure 'data-for' is the same as the react tip 'id'
      data-for={key}
      />
      <ReactTooltip id={key} place="top" type="dark" effect="solid" />
    </>
```

don't do this:
```js
    <>
      <BiInfoSquare
      size={22}
      data-tip
      // make sure 'data-for' is the same as the react tip 'id'
      data-for={key}
      />
      <ReactTooltip id={key} place="top" type="dark" effect="solid">
       {text}
      </ReactTooltip>
    </>
```

Hope this helps

**Comment by huy1912** [comment]
> @huy1912
> 
> I also had this issue, however I figured out that I was using the component incorrectly.
> you haven't provided your code so I don't know if you're having the same issue, but this is what fixed it for me.
> 
> do this:
> 
> ```js
>     <>
>       <BiInfoSquare
>       size={22}
>       // place the text you want to display in the 'data-tip' 
>       data-tip={text}
>       // make sure 'data-for' is the same as the react tip 'id'
>       data-for={key}
>       />
>       <ReactTooltip id={key} place="top" type="dark" effect="solid" />
>     </>
> ```
> 
> don't do this:
> 
> ```js
>     <>
>       <BiInfoSquare
>       size={22}
>       data-tip
>       // make sure 'data-for' is the same as the react tip 'id'
>       data-for={key}
>       />
>       <ReactTooltip id={key} place="top" type="dark" effect="solid">
>        {text}
>       </ReactTooltip>
>     </>
> ```
> 
> Hope this helps

Thanks @ ShawnCockburn, I've tried with your solution. The issue still hasn't been resolved. Not sure due to some other reason.

**Comment by huy1912** [comment]
> @huy1912 I had to fix z-index property on the div that my tooltip was hidden below. i removed it's z-index property.
> 
> if you want to keep using z-indexes keep that in mind:
> 
> Note: z-index only works on positioned elements (position: absolute, position: relative, position: fixed, or position: sticky) and flex items (elements that are direct children of display:flex elements).

Thanks @Sir-hennihau, I've checked the calendar item whose position is absolute but it doesn't have any z-index.
Even though I forced the tooltip's z-index to 999. The issue is still the same.

**Comment by ngotrongphuc** [comment]
any update? i got the same issue, i tried to change z-index of react-tooltip to _999999 !important_ but it doesn't work
![Untitled1](https://user-images.githubusercontent.com/72039796/151490562-208425d0-c420-4a15-b597-3c3d4e04d899.png)

**Comment by prideaux** [comment]
> ```js
> data-tip
> ```

This is the solution, example on an icon:

`<FaRegUser
                        data-tip="Account"
                        data-for={"account"}
                      />`

Then before the last DIV on the page add:

`      <ReactTooltip id={"account"} place="top" type="dark" effect="solid" />
`

**Comment by farhaakram94** [comment]
> You'll probably need to render the tooltips LAST and as siblings to the relevant components. This seemed to solve the issue for me...

I faced the same issue and this solution works perfectly :) Thank you

**Comment by leomiranda** [comment]
This fixes for me:

`<Tooltip anchorSelect={`#element`} style={{ zIndex: 99 }}>`
