### ISSUE TITLE
ReactTooltip.show does not work in Functional Components

### ISSUE THREAD

**Issue by caffeinatedHuman** [ReactTooltip/react-tooltip#713]
**Description:**

I want to show the tooltip based on some logic, which means I'll execute `ReactTooltip.show` to show the Tooltip manually.

As of now, the example in the docs mention passing the reference of the target to the function, which is not working in my case.

Here is a link to the code sandbox I created, showing a sample structure of my code: https://codesandbox.io/s/reacttooltip-sandbox-ovzfe

The click of `Show tooltip 3` is not showing the tooltip on the below p tag.

**Comment by penfold45** [comment]
Any luck on resolving this as I am having the same problem

**Comment by maniac-tech** [comment]
> Any luck on resolving this as I am having the same problem

Yes, I was able to achieve the desired result with the help of `useRef`
