### ISSUE TITLE
There will be a border line after clicking while applying to SVG element

### ISSUE THREAD

**Issue by liubq7** [ReactTooltip/react-tooltip#717]
It will show a black and white border line of the svg after clicking
![image](https://user-images.githubusercontent.com/55693386/130595156-903398ce-75ac-4e04-9d02-d107dbf63cb7.png)

**Comment by maheshmaf** [comment]
add to the svg / inner element, for which you have used data-tip
outline: none !important;

**Comment by trebor** [comment]
would love to see this fixed, rather than adding random css to my project.
