### ISSUE TITLE
Why `!important` is required?

### ISSUE THREAD

**Issue by seiyab** [ReactTooltip/react-tooltip#719]
MDN says 

>   Always look for a way to use specificity before even considering !important
    Only use !important on page-specific CSS that overrides foreign CSS (from external libraries, like Bootstrap or normalize.css).
    Never use !important when you're writing a plugin/mashup.
    Never use !important on site-wide CSS.

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception

related: https://github.com/wwayne/react-tooltip/issues/684

**Comment by Johnrobmiller** [comment]
!important should not be necessary.  This is very awkard and clunky design.  It also makes it impossible to use css libraries like Tailwind with React-Tooltip.

**Comment by aronhelser** [comment]
I agree. Please submit a PR if you are able to fix it!

**Comment by seiyab** [comment]
Oops I misunderstood the cause.
I considered `!important` is required because react-tooltip uses `!important`.
Actually, it doesn't use `!important` and higher specificity works well.
On the other hand, requiring `!important` or higher specificity is inconvenient as mentioned https://github.com/wwayne/react-tooltip/issues/719#issuecomment-919620221 and I think this issue is still meaningful.

**Comment by seiyab** [comment]
The cause seems to be rendering `style` tag inside the `body`.
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#multiple_style_elements) says:
> later <style> element override those in the earlier one, if they have equal specificity.

Usual libraries add `style` tag inside the `head`. So our style will be overriden.
react-tooltip seems to violate:
> The <style> element must be included inside the <head> of the document.

written in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)

https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L808-L811

I myself would not submit PR because the implementation of react-tooltip is highly complicated and it seems to be easier to re-implement from scratch...

**Comment by danielbarion** [comment]
Hi guys, this will be handled on V5, thanks for the report!

https://github.com/ReactTooltip/react-tooltip/discussions/812

**Comment by danielbarion** [comment]
Closing due to: https://react-tooltip.com/docs/examples/styling
