### ISSUE TITLE
Add `tooltip` to every `data-` attribute

### ISSUE THREAD

**Issue by FreePhoenix888** [ReactTooltip/react-tooltip#723]
`data-type` and such type of attributes can be reserved for app. It would be great to separate attributes for this library from other libraries' attributes. Of course, it is better to not use `data-type` at all and name it like more describing why it is used `data-modal-type`, `data-smth-type` and so on. Reason: 

> `data-type` on button? 🤔 Why is it used? Is it a type of a button? Is it a...

So I offer to rename attributes this way:
* `data-type` -> `data-tooltip-type`
* `data-effect` -> `data-tooltip-effect`

**Comment by danielbarion** [comment]
This will probably be handled on V5, thanks for the suggestion!

**Comment by danielbarion** [comment]
Closing due to https://react-tooltip.com/docs/examples/basic-examples#data-attributes
