### ISSUE TITLE
ReactToolTip Prop Place

### ISSUE THREAD

**Issue by oqnunes** [ReactTooltip/react-tooltip#727]
### Is it possible to place the Box on the right side of the icon as expected?

<img width="486" alt="Screenshot 2021-10-07 at 11 19 55" src="https://user-images.githubusercontent.com/45077154/136366257-50d0a6e0-fab1-46e4-aaa0-ce005ed43f58.png">

(Notice by the triangle in the black box).

I know the green box is bigger than the rest of the space on the right side, however, is there any way to resolve the situation?

Note: The icon has a scrollable superior parent.

Thanks!!

**Comment by stevenKirill** [comment]
There are too many icons on this picture, which one you are hover on to open tooltip? By this picture it seems that you are hovering on turquoise block.
