### ISSUE TITLE
Accessibility issues due to "aria-hidden" attribute

### ISSUE THREAD

**Issue by sanjaykc** [ReactTooltip/react-tooltip#728]
Getting below accessibility issue due to "aria-hidden" attribute
> The ARIA attribute 'aria-hidden' is not valid for the element <style> with ARIA role 'none'
**Violation**:
ARIA attributes must be valid for the element and ARIA role to which they are assigned
![image](https://user-images.githubusercontent.com/3944650/136433918-77b4ce4e-34b4-4a2e-80a2-4781807a2426.png)
![image](https://user-images.githubusercontent.com/3944650/136434232-f6e89183-c0e0-4516-9080-ac4d82268c0a.png)

**Comment by danielbarion** [comment]
Hi @sanjaykc, we got some PR's related to the aria attributes, can you check again and let us know, please?

I'll close due to the age of that issue, please feel free to open a new one if needed.

Thanks!
