### ISSUE TITLE
Minified React error #185

### ISSUE THREAD

**Issue by dana2208** [ReactTooltip/react-tooltip#734]
Hello,

![image](https://user-images.githubusercontent.com/10193337/142754770-0ea25057-26a4-467b-b4e5-aa2ed71f0fd0.png)

It is a bug that I have when I run the automation test (not on regular test) and it is related to the ReactToolitp that I had added. Without ReactTooltip, there is no error. Moreover it is written in the error 'ReactTooltip'.

Can you help me in figuring out what it is?

Thanks!

**Comment by danielbarion** [comment]
Hi can you try the latest release, please?

I'll close that issue due to the age, please feel free to open a new one if needed.

Thank you!
