### ISSUE TITLE
Setting z-index with className

### ISSUE THREAD

**Issue by mdodge-ecgrow** [ReactTooltip/react-tooltip#740]
Not sure why, but I cannot figure out how to set the z-index with the className.  I tried it with a number an a string and neither did anything.  I am using it in a modal and following the troubleshooting steps on the mian page.
`If your modal's z-index happens to be higher than the tooltip's, use the attribute className to custom your tooltip's z-index`

This is my code:
```
<ReactTooltip
	id={'view-hash'}
	effect={'solid'}
	place={'top'}
	backgroundColor={'#212529'}
	delayHide={2000}
	clickable={true}
	className={'2000'}
/>
```

**Comment by rickyzhangca** [comment]
> Not sure why, but I cannot figure out how to set the z-index with the className. I tried it with a number an a string and neither did anything. I am using it in a modal and following the troubleshooting steps on the mian page. `If your modal's z-index happens to be higher than the tooltip's, use the attribute className to custom your tooltip's z-index`
> 
> This is my code:
> 
> ```
> <ReactTooltip
> 	id={'view-hash'}
> 	effect={'solid'}
> 	place={'top'}
> 	backgroundColor={'#212529'}
> 	delayHide={2000}
> 	clickable={true}
> 	className={'2000'}
> />
> ```

add a class in your css called `abc` and use `abc` as your `className`. Then inside `abc`, do `z-index: 9999 !important;`.
