### ISSUE TITLE
Dependency uuid latest makes react-tooltip not IE9-11 friendly

### ISSUE THREAD

**Issue by jxxp9** [ReactTooltip/react-tooltip#744]
The `uuid` dependency uses a random number generator that has problems with missing Web API in IE9-11.
Options are:
- use an older version of the lib?
- use `v1` or` v2` as imports of the uuid library and specify a basic custom random number generator function

The latter is preferable, since we don't really need our UUIDs to be cryptographically secure, we just need some pseudorandom uuid with reasonable randomness, so even `Math.random()` would work well for us

**Comment by jafin** [comment]
Do you have opportunities to migrate users to Edge?  Many libraries are dropping IE support due to the low percentage of users globally running IE now.

**Comment by msavel2i** [comment]
Unfortunately many customers use Win 7 and even Vista and moving away from IE would also break some Active Directory/ActiveX compatibility. Hard times

**Comment by danielbarion** [comment]
Hi @jxxp9, that was a great suggestion, but not only `uuid` package dropping the support for IE, but there also are other dependencies that are doing the same and we are upgrading our code and dependency.

If we add the `uuid` as optional, probably something else will break the application into the IE.

I'll close that issue, thanks and I'm sorry.
