### ISSUE TITLE
"place" prop not working

### ISSUE THREAD

**Issue by jesuslencina** [ReactTooltip/react-tooltip#747]
I noticed that the tooltip seems to stick to the `left` position no matter what. According to the docs, placement by default is `top` (which is the one that'd work best in my project), however it sticks to `left`.

And even if I pass the props as `place="top"`, it will save the value to `desiredPlace`, but the tooltip will keep displaying to the left.

Here's a screenshot from the react dev tools:
![image](https://user-images.githubusercontent.com/36510164/159708286-9b902b4e-99dd-4c52-90dd-fba4523913f7.png)

Could this be a bug? 

Thanks

**Comment by alimoli** [comment]
Any PR closed for this? I still experience this issue in the latest version (`5.26.4`).
@danielbarion

**Comment by gabrieljablonski** [comment]
@alimoli This is most likely not a bug, just the default tooltip behavior. You're probably trying to place the tooltip inside an element that can't fit the tooltip at the top, so it automatically moves somewhere it fits (this behavior is from [`floating-ui`](https://floating-ui.com/docs/middleware), which we use under the hood).

If you'd like, please open a new issue with a `question` tag with a sample code from where you're experiencing this problem, and we might be able to help work around it.

But you can try moving the tooltip component outside of where it currently is placed ("up the DOM"). Simple example:

From this:
```jsx
<OuterContainer>
  <InnerContainer> // This container is not big enough to fit the tooltip
    <MyContent />
    <Tooltip />
  </InnerContainer>
</OuterContainer>
```

To this:
```jsx
<OuterContainer>
  <InnerContainer>
    <MyContent />
  </InnerContainer>
  <Tooltip />
</OuterContainer>
```

Let us know if this works for you.
