### ISSUE TITLE
padding is not an option

### ISSUE THREAD

**Issue by ItsTarik** [ReactTooltip/react-tooltip#752]
Hello and thanks for the effort, i don't know why the docs mentions a padding prop perhaps its not proposed as an option in the component ? I'm trying to customize the padding of the rendered popup ?

**Comment by jafin** [comment]
@ItsTarik, padding is not in the current published version looking at the commit date.  If you compile the code you'll get the padding prop.

**Comment by ItsTarik** [comment]
Thanks, I've handled it with global style, it's not worth it to compile it locally, I've opened this issue because the docs describes the padding prop and it could be so confusing for people ..

**Comment by danielbarion** [comment]
Closing this one, if you guys need, open a new issue, thanks!
