### ISSUE TITLE
[Feature request] make arrow size customizable

### ISSUE THREAD

**Issue by FedeTommi** [ReactTooltip/react-tooltip#753]
Would it be possible to add a new prop "arrowSize" to change the size of the arrow?
like so:
 ```javascript
.${uuid}.place-bottom::after {
        border-left: ${arrowSize}px solid transparent;
        border-right: ${arrowSize}px solid transparent;
        top: -6px;
        left: 50%;
        margin-left: -${arrowSize}px;
        border-bottom-color: ${arrowColor};
        border-bottom-style: solid;
        border-bottom-width: 6px;
    }
```

**Comment by danielbarion** [comment]
You still can do the PR for V4, but this will be handled on V5, thanks!

https://github.com/ReactTooltip/react-tooltip/discussions/812

**Comment by danielbarion** [comment]
hi, @FedeTommi can you let me know your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074

**Comment by danielbarion** [comment]
Hi @FedeTommi, this is now possible with V5 (which is still WIP), but please take a look at:

https://react-tooltip.com/docs/examples/styling

I'll close this issue but feel free to give your feedback on the V5 Pull request, thanks!

**Comment by PavelKopecky** [comment]
Hey, is this really implemented? I cannot find anything about it in the docs and cannot find it anywhere in the source files either.

**Comment by danielbarion** [comment]
Hey @PavelKopecky, have you really checked the docs???

https://react-tooltip.com/docs/options

![image](https://github.com/user-attachments/assets/288fe6cf-0069-4255-8433-15c073e21f62)

https://codesandbox.io/s/shy-haze-vxdvtx?file=/src/styles.css

https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/TooltipController/TooltipControllerTypes.d.ts#L19
https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/Tooltip/TooltipTypes.d.ts#L114

It is closed and locked as completed.
