### ISSUE TITLE
Its instance type 'ReactTooltip' is not a valid JSX element.

### ISSUE THREAD

**Issue by DenisGold** [ReactTooltip/react-tooltip#761]
Few days ago newest version of React tooltip return error
'ReactTooltip' cannot be used as a JSX component.
  Its instance type 'ReactTooltip' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.  TS2786

```
  > 68 |                        <ReactTooltip />
       |                         ^
    69 |                </>
    70 |        );
    71 |
    
```
    
    I added pull request with potential fix, please take a look @wwayne or anyone else

**Comment by DenisGold** [comment]
@aronhelser please check it and my PR, maybe you will be able to update rpm library with this potential fix, also @wwayne send me link with fix that works for me  https://stackoverflow.com/a/71828113/3404325

**Comment by ronakiihglobal** [comment]
Any solution for npm users sorry?

**Comment by DenisGold** [comment]
Only for yarn!

"resolutions": {
    "@types/react": "16.9.53",
    "@types/react-dom": "16.9.8"
  }

put this in your package.json and use yarn for install

**Comment by DenisGold** [comment]
Hi Daniel, works perfect! you can close it, thanks
