### ISSUE TITLE
Background color in css does not change top notch

### ISSUE THREAD

**Issue by daceynolan** [ReactTooltip/react-tooltip#768]
When overriding styles in Styled Components, setting the background-color does not change the color of the notch. 

```
const StyledTooltip = styled(ReactTooltip)`
  // using !important to override styles from the library
  background-color: ${({ theme }) => theme.vars.foundationSurface2} !important;
  border-radius: ${({ theme }) => theme.constants.borderRadiusMd} !important;
`;
```
![Screen Shot 2022-05-04 at 9 49 17 PM](https://user-images.githubusercontent.com/54158919/166853144-7388e71e-a920-4e74-9234-c81bd0a75a8f.png)

**Comment by danielbarion** [comment]
hi, @daceynolan can you let me your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074
