### ISSUE TITLE
Version 4.2.21 on npm outdated?

### ISSUE THREAD

**Issue by ansgarsteinkamp** [ReactTooltip/react-tooltip#770]
Version 4.2.21 on npm was published a year ago. What's about all the bug fixes here on GutHub since June of 2021?

**Comment by huner2** [comment]
For those of you who would prefer to install the package from npm,  I've published an npm package based on the 4.2.21 tag on this repository.  This tag did not pass the tests so I changed a single line to get the library working again.  I hope my package will be obsolete soon and the original npm package will be updated.

[@huner2/react-tooltip](https://www.npmjs.com/package/@huner2/react-tooltip)

**Comment by ansgarsteinkamp** [comment]
@aronhelser @wwayne huner2 may be a great choice as an additional maintainer too.

**Comment by aleksspeaker** [comment]
Gentle nudge
@alexgurr @wwayne @aronhelser @danielbarion 🙏🏻 
I'm sorry. I hate to ping people and escalate issues but I have no choice.

**1.5M weekly downloads** guys. Imagine how many people have problems with the react-tooltip on React 18.
Someone has to take action. Please. 🥺

**Comment by huner2** [comment]
@aleksspeaker And others who may continue to view this thread.  I'm not an active maintainer, nor is the answer you're looking for, but in my opinion taking a look at [floating-ui](https://floating-ui.com/docs/react-dom-interactions) as an alternative (with React support of course) may be your best course of action.

**Comment by aleksspeaker** [comment]
@huner2 thank you for the suggestion.
But I think we've got this thing moving again.
[Founder and maintainers looking to pass the torch](https://github.com/ReactTooltip/react-tooltip/issues/794)
So I'm looking forward to the new NPM release soon. :)

**Comment by aleksspeaker** [comment]
Can I help with this somehow?

**Comment by wwayne** [comment]
Hi, sorry I don't know what steps are needed before publishing the package bc I haven't maintained the project for a couple of years.
Maybe we can ask @aronhelser help when he has time and would appreciate if someone can write down the steps for the package publishing

**Comment by aleksspeaker** [comment]
> for the package publishing

This should do:
https://cloudfour.com/thinks/how-to-publish-an-updated-version-of-an-npm-package/

**Comment by aleksspeaker** [comment]
`ping`

**Comment by danielbarion** [comment]
Hi @aleksspeaker, I'm waiting for the permissions to do the next release, sorry for the delay in that issue.

**Comment by aleksspeaker** [comment]
> 

No worries. I just needed to know if it is moving because I have a dependency on it and I don't want to rework all the code after migrating to React 18.

@danielbarion  Thank you for the update!
Please keep us posted even if there are no significant updates. It's still good to know that somebody cares about it.

**Comment by danielbarion** [comment]
Hi @aleksspeaker, 

Please, check my comment here: https://github.com/ReactTooltip/react-tooltip/issues/777#issuecomment-1277767508

I'll wait for your feedback to close that one (will be great if the @ansgarsteinkamp gives some feedback too as he started the issue).

**Comment by aleksspeaker** [comment]
@danielbarion amazing,
I've updated and checked. Everything works fine for me.
Thank you!
