### ISSUE TITLE
How to have one than one style in the same app

### ISSUE THREAD

**Issue by Talaween** [ReactTooltip/react-tooltip#772]
I understand that I can set the style through className passed to <ReactTooltip className="myCustomStyle1"/> which is a direct child of the top component, then it catches all data-tip attributes on children.

however, if I want a specific group of children to have a different style, what should I do?

**Comment by danielbarion** [comment]
hi, @Talaween  can you let me know your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074
