### ISSUE TITLE
Comma separated value for Place prop throws error

### ISSUE THREAD

**Issue by daceynolan** [ReactTooltip/react-tooltip#776]
When trying to pass a list of `place` options as stated in the docs , it does not work and throws an error.  
![Screen Shot 2022-06-14 at 1 37 43 PM](https://user-images.githubusercontent.com/54158919/173641443-256427ee-2d3e-4e89-8aaa-f5b06aa196d1.png)

Error: 
![Screen Shot 2022-06-14 at 1 39 48 PM](https://user-images.githubusercontent.com/54158919/173641941-8df25209-298a-4c2e-989c-24ff8bed285f.png)

**TypeScript Type for Place prop:**
![Screen Shot 2022-06-14 at 1 36 26 PM](https://user-images.githubusercontent.com/54158919/173641519-57080a40-7ffd-4de0-a435-d5cd77211545.png)
![Screen Shot 2022-06-14 at 1 36 20 PM](https://user-images.githubusercontent.com/54158919/173641521-4382dca9-350c-48cf-9df6-5cf41a5e2b00.png)

**The TypeScript Error:** 
![Screen Shot 2022-06-14 at 1 36 03 PM](https://user-images.githubusercontent.com/54158919/173641522-9d84cd61-80d5-480c-a809-6c1452492a9e.png)
![Screen Shot 2022-06-14 at 1 35 57 PM](https://user-images.githubusercontent.com/54158919/173641524-68d8d8e4-0851-427e-8931-e624f34ff851.png)

**Comment by ChARCOOL** [comment]
@daceynolan Hi, I think you misunderstood the type, it's either TOP or RIGHT or BOTTOM or LEFT, you pass only ONE place.

**Comment by daceynolan** [comment]
@ChARCOOL The docs said that you could pass the place comma separated under the values 

![Screen Shot 2022-06-21 at 9 58 59 AM](https://user-images.githubusercontent.com/54158919/174817970-562974b2-a8cb-4b1e-8951-2ccbe31054af.png)

**Comment by alexanderjarl91** [comment]
+1, I'm also having this issue.

**Comment by DavidSentiurin** [comment]
+1
