### ISSUE TITLE
Tooltips do not disappear when I move cursor away from input field

### ISSUE THREAD

**Issue by m21tomas** [ReactTooltip/react-tooltip#777]
I'm writing forms and I need to check if input is valid. 
But right now I'm testing how your Tooltips work in general. It doesn't work properly for me. Either I'm doing smth wrong or your tooltip is wrong.
![image](https://user-images.githubusercontent.com/94525145/174606991-0e3b588d-a165-4dd7-9c90-6d20abce9df4.png)
I have this code:
```jsx
import React, { useState } from 'react';
//...
import ReactTooltip from 'react-tooltip';
//....
function AddNewCanteen() {

return (
            <div>
            <form onSubmit={handleSubmit}>
                <h6 className="py-3">
                    <b>Pridėti naują maitinimo įstaigą:</b>
                </h6>
                <div className="form-group" style={{ position: 'relative', width: '95%' }}>
                    <label htmlFor="name">
                        Pavadinimas <span className="fieldRequired">*</span>
                    </label>
                    <a data-tip data-for='global'>
                        <input
                            type="text"
                            className="form-control mt-2"
                            name="name"
                            id="id_name"
                            value={duomenys.name}
                            onChange={handleChange}
                            onInvalid={validateField}
                            style={
                                duomenys.name.length > 0 ? infoValid.name ? { border: "1px solid lightgray" }
                                    : { border: "2px solid red" }
                                    : { border: "1px solid lightgray" }
                            }
                            required
                            pattern="^[A-ZĄ-Ž]{1}[\S\s]{1,64}$"
                            maxLength={64}
                            data-toggle="tooltip"
                            data-placement="top"
                            title="Įveskite maitinimo įstaigos pavadinimą"
                        />
                    </a>
                    <ReactTooltip id='global' aria-haspopup='true' delayHide={1000} >
                        <p>This is a global react component tooltip</p>
                        <p>You can put every thing here</p>
                        <ul>
                            <li>Word</li>
                            <li>Chart</li>
                            <li>Else</li>
                        </ul>
                    </ReactTooltip>

                    {duomenys.name.length > 0 ? infoValid.name ? <span className="approvemsg"><FontAwesomeIcon icon={faCheck} /></span>
                        : <span className="warningmsg"><FontAwesomeIcon icon={faXmark} /></span>
                        : <span className="approvemsg"></span>}
                    <br></br>
                </div>
                
                //.....
                </div>
          );
}
export default AddNewCanteen;
```
What is wrong with it? 
Why the tooltip doesn't disappear when I move mouse cursor away?
Why does it remain forever?
That really annoys.

**Comment by m21tomas** [comment]
I had to change this:
```jsx
const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(<StrictMode>
  <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
    <Switch>
      <StyledEngineProvider injectFirst>
        <Route path="*" component={App} />
      </StyledEngineProvider>
    </Switch>
  </BrowserRouter>
</StrictMode>
```
to this:
```jsx
const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(
  <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
    <Switch>
      <StyledEngineProvider injectFirst>
        <Route path="*" component={App} />
      </StyledEngineProvider>
    </Switch>
  </BrowserRouter>
```
In other words to remove Strict mode.
Shame on you creators "developers".

**Comment by aronhelser** [comment]
Umm, yea, that's not productive. If you have a suggestion for improving, make it. 

None of the current maintainers are actively working on this component. If you want a fix, contribute a PR.

**Comment by Jamil-Bailony** [comment]
Thanks for mentioning it @m21tomas I have the same issue :(

**Comment by nan0hard** [comment]
Yeah! facing the same issue.

**Comment by Timer91** [comment]
Same

**Comment by nodgear** [comment]
> I had to change this:
> 
> ```js
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> root.render(<StrictMode>
>   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
>     <Switch>
>       <StyledEngineProvider injectFirst>
>         <Route path="*" component={App} />
>       </StyledEngineProvider>
>     </Switch>
>   </BrowserRouter>
> </StrictMode>
> ```
> 
> to this:
> 
> ```js
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> root.render(
>   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
>     <Switch>
>       <StyledEngineProvider injectFirst>
>         <Route path="*" component={App} />
>       </StyledEngineProvider>
>     </Switch>
>   </BrowserRouter>
> ```
> 
> In other words to remove Strict mode. Shame on you creators "developers".

are your really shaming someone who made something for free and you're using?
like... wth?

**Comment by mikulash** [comment]
Hi, I had the similar problem and removing <StrictMode> really did help. But what I find strange is that the strict mode did not really noticed any errors made by the tooltip so I wonder where could be the problem.

**Comment by m21tomas** [comment]
> > I had to change this:
> > ```js
> > const root = ReactDOM.createRoot(document.getElementById("root"));
> > 
> > root.render(<StrictMode>
> >   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
> >     <Switch>
> >       <StyledEngineProvider injectFirst>
> >         <Route path="*" component={App} />
> >       </StyledEngineProvider>
> >     </Switch>
> >   </BrowserRouter>
> > </StrictMode>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to this:
> > ```js
> > const root = ReactDOM.createRoot(document.getElementById("root"));
> > 
> > root.render(
> >   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
> >     <Switch>
> >       <StyledEngineProvider injectFirst>
> >         <Route path="*" component={App} />
> >       </StyledEngineProvider>
> >     </Switch>
> >   </BrowserRouter>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In other words to remove Strict mode. Shame on you creators "developers".
> 
> are your really shaming someone who made something for free and you're using? like... wth?

yes I did. And I don't regret. But I won't blame anymore.

**Comment by DhirajKrVerma** [comment]
> I had to change this:
> 
> ```js
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> root.render(<StrictMode>
>   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
>     <Switch>
>       <StyledEngineProvider injectFirst>
>         <Route path="*" component={App} />
>       </StyledEngineProvider>
>     </Switch>
>   </BrowserRouter>
> </StrictMode>
> ```
> 
> to this:
> 
> ```js
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> root.render(
>   <BrowserRouter forceRefresh basename={process.env.PUBLIC_URL}>
>     <Switch>
>       <StyledEngineProvider injectFirst>
>         <Route path="*" component={App} />
>       </StyledEngineProvider>
>     </Switch>
>   </BrowserRouter>
> ```
> 
> In other words to remove Strict mode. Shame on you creators "developers".

yes It's Working

**Comment by ferdiamg** [comment]
Same here, and can confirm: Removing the strict mode makes the tooltips work again. However its not advised to disable the strict mode just to make a npm package work.

For debugging:
"next": "12.1.6",
"react": "18.2.0",
"react-copy-to-clipboard": "^5.1.0",
"react-dom": "18.2.0",
"react-tooltip": "^4.2.21",
"tailwindcss": "^3.1.3",
"typescript": "4.7.3"

**Comment by aronhelser** [comment]
None of the current "maintainers" are actively developing web apps or this component. We need a community submitted PR to solve this problem.

**Comment by sambaneko** [comment]
It looks like a similar issue was already fixed and merged (#755), but the npm package is not up to date with those changes?  There is also an existing PR that appears to address this (#786).

Can the npm package be updated?

**Comment by sambaneko** [comment]
Alternatively, I tried switching to the npm package provided by pdeszynski in #786, and it is working properly for me with strict mode enabled.

**Comment by m21tomas** [comment]
> Alternatively, I tried switching to the npm package provided by pdeszynski in #786, and it is working properly for me with strict mode enabled.

That's an excellent new. Does it work completely the same like Tooltip from [wwayne] and [aronhelser], but also icluding Strict mode?

**Comment by sambaneko** [comment]
@m21tomas I haven't thoroughly tested it myself, but since it has been submitted as an update for the react-tooltip package, it should support all of the same syntax and commands.

**Comment by syed-ahmad** [comment]
Try setting `isCapture={true}`, that fixed tooltip dismissing on scroll in my Nextjs app.

**Comment by Ali-Aref** [comment]
same issue, any updates ?

**Comment by syed-ahmad** [comment]
> same issue, any updates ?

Did that `isCapture={true}` not work for you @Ali-Aref ?

**Comment by Ali-Aref** [comment]
yes I tried,
in my case it depends to `StrictMode` disabling `StrictMode` makes it work. but, it's not okay to disable `StrictMode` because of an npm package to work (I'm new to react). So, I am looking for any alternative solutions.. if there are any?

**Comment by danielbarion** [comment]
Hi guys, the release **v4.3.0** enables support for React 18 and Next.js strict mode, thanks to @pdeszynski.

**Comment by aleksspeaker** [comment]
I've tested it on v4.3.1.
Tooltips do disappear now when I move cursor away from the target.
