### ISSUE TITLE
Change arrow border radius 

### ISSUE THREAD

**Issue by adir4m** [ReactTooltip/react-tooltip#780]
Hi, how can i change the radius of the arrow to be more rounded?
<img width="340" alt="arrow" src="https://user-images.githubusercontent.com/94120790/175935340-6b57c9f3-2487-4bb5-9640-ea70204ed44a.png">

`<ReactTooltip className="tooltip-custom" id="help" place="top" multiline={true} arrowColor="#121922">
              {helpTooltip}
            </ReactTooltip>`

**Comment by danielbarion** [comment]
hi, @adir4m  can you let me your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
