### ISSUE TITLE
react-tooltip stops working after expanding event list in Full-calendar. 

### ISSUE THREAD

**Issue by tutorplanner-web** [ReactTooltip/react-tooltip#781]
I am using react-tooltip [@fullcalendar/react](https://www.npmjs.com/package/@fullcalendar/react). It works fine when I click on an event. But after expanding the events, it doesn't work. 
Here is the reproducible codesandbox. 
[https://codesandbox.io/s/fullcalendar-daygrid-with-react-tooltip-qrv6l7](https://codesandbox.io/s/fullcalendar-daygrid-with-react-tooltip-qrv6l7)
As you can see, on clicking "Event 001" the tooltip becomes visible. But if we click on "+4 more" button, the tooltip will not work anymore.  If anyone knows how to fix this issue please help.
Thank you.

**Comment by danielbarion** [comment]
Hi @tutorplanner-web, have you tried the `tooltip.rebuild()`?

https://github.com/ReactTooltip/react-tooltip#reacttooltiprebuild

Can you try and let me know, please?

Thanks!
