### ISSUE TITLE
Unable to custom the width of the tooltip based on the content

### ISSUE THREAD

**Issue by ShivaniAmpati** [ReactTooltip/react-tooltip#783]
I would need a tooltip with some width set but unable to achieve it through classes and indeed i dont want to you use <br/> and set multiline={true}

**Comment by lydiautkin** [comment]
+1. Would love to have a width or min-width prop for handling longer strings. The default of 20px is too small.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/2299947/179295091-8193dbb3-ab4b-4215-8033-79d74e856783.png">

**Comment by alfianandinugraha** [comment]
I try set width like this

```javascript
<ReactTooltip
  effect="solid"
  id={tooltipId}
  place={option.tooltip?.position ?? 'top'}
  overridePosition={(
    { top, left },
    currentEvent,
    currentTarget,
    node
  ) => {
    node.style.width = '190px'; // Your custom width
    return {
      top,
      left
    };
  }}
/>
```

Idk, but this is works for me

**Comment by danielbarion** [comment]
Hi, guys can you let me your thoughts here, please? https://github.com/ReactTooltip/react-tooltip/pull/820#issuecomment-1317096074

Also, v5 will not have this problem, but if someone can make a PR to fix v4.x, this will be great!

thanks!

**Comment by danielbarion** [comment]
Hi, closing this issue due to: https://react-tooltip.com/docs/examples/styling#basic-explanation

Please, open a new one if necessary. Thanks!
