### ISSUE TITLE
Change data-type for opened tooltip

### ISSUE THREAD

**Issue by fakhamatia** [ReactTooltip/react-tooltip#785]
I want change `data-type` dynamic for opened tooltip.
I can change Icon with this way but for tooltip not work
I must re-hover to see change
```js
<IconButton
    data-tip={darkMode ? "light" : "dark"}
    data-place="right"
    data-type={darkMode ? "light" : "dark"}
    size="small"
    disableRipple
    color="inherit"
    sx={navbarIconButton}
    onClick={() => {
        handleDarkMode();
    }}
>
    <Icon sx={iconsStyle}>{darkMode ? "light_mode" : "dark_mode"}</Icon>
</IconButton>;
```
![Peek 2022-07-21 16-59](https://user-images.githubusercontent.com/20030910/180214254-5306c3fb-d00c-44ca-b473-cf858db63fb1.gif)

"react-tooltip": "^4.2.21"
"react": "17.0.2"

**Comment by WilliamWelsh** [comment]
Try calling `ReactTooltip.rebuild();` after

**Comment by fakhamatia** [comment]
> 

Not working

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
