### ISSUE TITLE
Not working with NextJS

### ISSUE THREAD

**Issue by JayMehta97** [ReactTooltip/react-tooltip#790]
I want to show tooltip on a input field when a button is clicked. I am able to do that in codesandbox [here](https://codesandbox.io/s/react-tooltip-basic-example-forked-jthk5e) but the exact same code doesn't work in my NextJS app. I also tried checking if the ref was assigned correctly and it is, calling `input.current.focus()` works but `ReactTooltip.show(input.current)` doesn't.

Am I missing something here?

**Comment by mrcMesen** [comment]
Read [this](https://github.com/wwayne/react-tooltip/issues/777) conversation

Basically you need to set strict mode to false on the next config

**Comment by danielbarion** [comment]
Please, check my comment here: https://github.com/ReactTooltip/react-tooltip/issues/777#issuecomment-1277767508

I'll wait for your feedback to close that one.

**Comment by mrcMesen** [comment]
Thanks @danielbarion I'll try it 👍

**Comment by danielbarion** [comment]
Hi @mrcMesen, do you have any updates?

**Comment by danielbarion** [comment]
Marking as resolved based on other tickets, please open a new one if necessary.
Thanks!
