### ISSUE TITLE
BUG: Tooltip is not updating when useState prop updates

### ISSUE THREAD

**Issue by MylesWardell** [ReactTooltip/react-tooltip#792]
## **Example Code Sandbox:**
https://codesandbox.io/s/example-of-background-colour-not-updating-k0mynp

## **Expected Behaviour:**
When a useState prop changes the tooltip rerenders with the new props. In the example above the tooltip should immediately update to green. At minimum the rebuild should update the props.

## **Hotfix:**
I have tried hiding and showing and using refs and this has not fixed the issue. I could not find any temporary solutions.

**Comment by danielbarion** [comment]
Hi @aronhelser @alexgurr @pdeszynski, can you guys check that issue, please?

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
