### ISSUE TITLE
Can we reuse ReactTooltip component by initializing at the root component and accessing it in its child component

### ISSUE THREAD

**Issue by premnkl** [ReactTooltip/react-tooltip#793]
Dear Team,

We started using ReactTooltip inside a component and it is absolutely fine.

Our actual case is to extend it to multiple components. Before making this change to initialize ReactTooltip at each component individually, wanted to check is it possible to initialize ReactTooltip once at the root component and pass data-tip from the child to get it displayed ?

**Comment by danielbarion** [comment]
Hi @premnkl, I believe that is not possible at the moment, but if you can, please submit a PR 🙏🏻

**Comment by danielbarion** [comment]
I'll build the V5 with that suggestion in mind.

Thanks!

**Comment by premnkl** [comment]
Hi @danielbarion ,

Thanks for your comment. I couldn't focus on the PR right now. sorry for that

looking forward for your update on this.

**Comment by danielbarion** [comment]
Hi, @premnkl no problem,

https://react-tooltip.com/docs/examples/state

Please take a look at V5 pre-release, with the controlled state, you can have one tooltip being controlled by a react context API for example.

Please let me know your feedback on this, thanks!

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
