### ISSUE TITLE
Founder and maintainers looking to pass the torch

### ISSUE THREAD

**Issue by aronhelser** [ReactTooltip/react-tooltip#794]
This project has been barely supported by the current maintainers, myself and @roggervalf  for some time. @huumanoid is an inactive maintainer, and the original author @wwayne has moved on and is non-responsive to request. I do not have permissions to add new maintainers to this repo, so we need to identify a fork of this project that will be actively maintained for the future and is able to publish packages to NPM. 

@pdeszynski and @alexgurr are two people who have expressed interest. Please comment on this issue if you are interested!

**Comment by wwayne** [comment]
appreciate @aronhelser for your work and passion, and sorry I don't have time on this project
plz feel free to let me know if there is anything I can do for better maintenance in the next
thanks again for such a long time supporting

**Comment by aronhelser** [comment]
Hi @wwayne I think the best thing for the project is to add @alexgurr as a maintainer, and give them the permission to add other maintainers, and see what happens :)

**Comment by wwayne** [comment]
I just invited @alexgurr to both GitHub and NPM as the collaborator, but I haven't found any options for giving him the permission to invite others, plz let me know if you know how I can do it or I can do the invitation when you asked, thanks : )

**Comment by danielbarion** [comment]
Hi guys, I'm always checking that repository and some other open-source projects, if you guys need it, I can help test PRs and validate new issues in the available time that I have, just please let me know :)

**Comment by wwayne** [comment]
@danielbarion thanks, sounds good to me, let me do it

**Comment by wwayne** [comment]
I moved this repo to the org https://github.com/ReactTooltip, and I invited all the other 3 collaborators as the owner of the org (hope it works).
I set up a logo that I bought a couple of years ago, please feel free to update if you don't like it haha

**Comment by pdeszynski** [comment]
If help's needed, then I will try to help, setup stuff etc, though I don't think I will be better maintainer than you guys (taking into consideration that I feel mostly as a backend dev ;) ).

**Comment by aleksspeaker** [comment]
This is fantastic news.
Now someone needs to publish a new NPM package version.

**Comment by danielbarion** [comment]
Guys, do you need any help with the next release?

If yes, please add me as a maintainer and I'll take a look in my free time to do the next release with the new structure of the repository.

cc @wwayne @aronhelser

**Comment by aronhelser** [comment]
@danielbarion Invited, looks like we missed you at first!

**Comment by danielbarion** [comment]
@aronhelser, I believe that @pdeszynski will be a great helper to take care of that project too

**Comment by danielbarion** [comment]
As Aron reacted with the thumb-up emoji, I sent an invite to @pdeszynski, hope you accept and join us to help and take care of that project too 🙏🏻

**Comment by danielbarion** [comment]
I believe that we already organized a group of maintainers (probably not everyone will be an active developer but we will take care of that project). As if anyone wants to help us, please let us know, or feel free to send PRs :) 

I'm closing that topic for now.
