### ISSUE TITLE
Suggestion: Allow disabling default behavior when controlling manually.

### ISSUE THREAD

**Issue by RonnyLark** [ReactTooltip/react-tooltip#807]
I would like to have a perma-open tooltip but there is no prop to control tooltip showing.
The functions `ReactTooltip.show` and `ReactTooltip.hide` work once, but if I call `ReactTooltip.show` then hover over my element, the tooltip would hide as usual.

Unless there's a workaround I'm not familiar with, I'd like to suggest a way to disable the default behavior in order to allow more granular manual control.
Something like:
```js
const ref = useRef();

useEffect(() => {
  ReactTooltip.disableDefault(ref.current)
}, [ref.current])

return <div ref={ref} data-tip="tip">content</div>
```

Or alternatively, data props like `data-visible` that would be boolean.

**Comment by danielbarion** [comment]
Hi, please check: https://react-tooltip.com/docs/examples/state

Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
