### ISSUE TITLE
Arrow overlaps text when custom padding is applied in v4.4.3

### ISSUE THREAD

**Issue by alexzel** [ReactTooltip/react-tooltip#810]
I use custom padding which leads to text overlapping by arrow in v4.4.3.

In order to reproduce it change the main tooltip in the example application, so it has disabled multiline, solid effect, and custom padding, like the following:

```jsx
<ReactTooltip
  id="main"
  place={place}
  type={type}

  // changes
  effect="solid"
  multiline={false}
  padding="5px 10px"
/>
```

See the difference between v4.4.2 and v.4.43

v4.4.2
![arrow-overlap-v4 4 2](https://user-images.githubusercontent.com/1964324/198520850-f316882a-d49e-48af-b690-9f0a27b4bd2c.png)

v4.4.3
![arrow-overlap-v4 4 3](https://user-images.githubusercontent.com/1964324/198520868-90c8ef15-2df3-47d3-844f-7f0f1a90b39b.png)

It seems like a result of the changes made in https://github.com/ReactTooltip/react-tooltip/pull/806
@erezcarmel @danielbarion

**Comment by danielbarion** [comment]
Thanks for the report @alexzel! 

Can you or @erezcarmel do a PR to fix that one, please? I'll review it as soon as possible!

**Comment by erezcarmel** [comment]
@danielbarion I'm on it. Please assign me to this issue.

**Comment by danielbarion** [comment]
Thank you so much @erezcarmel, I'll do the review and the release tomorrow (or this week) as I'm on travel right now

**Comment by danielbarion** [comment]
Hi @alexzel, can you re-check using version v4.5.0 published today, please?

Thanks @erezcarmel, your PR was already published, thank you so much!

**Comment by alexzel** [comment]
Looks good! Thank you.

**Comment by JonasJuss** [comment]
Hey 👋 

I think this problem might have been re-introduced in v4.5.1:

![image](https://user-images.githubusercontent.com/6849567/204531482-a9501521-10a7-4887-b4b5-22e8cb1ed1f4.png)
![image](https://user-images.githubusercontent.com/6849567/204531587-a04f4c15-2335-4765-9211-a42719fd87d3.png)

I tested with v4.5.0, which works fine:
![image](https://user-images.githubusercontent.com/6849567/204531971-fa957939-9ee8-4853-9060-2483c2bfffc4.png)
