### ISSUE TITLE
Attribute to disable internal styling?

### ISSUE THREAD

**Issue by NemeZZiZZ** [ReactTooltip/react-tooltip#811]
It would be perfect, if `<ReactTooltip>` component will have property to disable internal stylings totally in favor of external CSS, so users can use their own styles, so it will help with styling and maintaining.
The only properties needed are `left/top`, it's more than enough.

**Comment by danielbarion** [comment]
Hi @NemeZZiZZ, sounds great!

Can you do a PR for that, please?
