### ISSUE TITLE
Fixed tooltip position

### ISSUE THREAD

**Issue by jhauser** [ReactTooltip/react-tooltip#825]
The react-tooltip message position moves around when the mouse is moved within the associated div. I find this movement particularly annoying - particularly when the target div is a big box. My preference is a single fixed position that is not affected by mouse position.

I can achieve this with overridePosition but this sets up top and left relative to the window - rather than the target div or it's wrapper. This makes the positioning much more complex - i.e. in setting up the offsets and managing window resize.

Am I missing something here? Is there a way to fix the message position or perhaps to find the target div position more easily.

**Comment by danielbarion** [comment]
Hi @jhauser, just confirming: have you tried the `solid` option instead of `float` (default)
https://reacttooltip.github.io/react-tooltip/

This will be changed in V5 and `solid` (the fixed tooltip into the anchor element) will be the default behavior.

Can you confirm, please?

**Comment by jhauser** [comment]
If all else fails ... read the instructions.

Perfect - thanks for pointing that out.
