### ISSUE TITLE
text cut off at the bottom

### ISSUE THREAD

**Issue by ydainna** [ReactTooltip/react-tooltip#827]
Hello I open this issue because parfoit the text is cut at the bottom some letters the bottom is not visible ....
![image](https://user-images.githubusercontent.com/32979492/204286048-4ad19045-b014-4a4e-973a-b0a4c3407e31.png)

**Comment by LennartSpitzner** [comment]
+1

I am pretty sure this got introduced by the new arrow-implementation and affects 4.5.0 but now 4.4.0.

The tooltip has a `::before` that is just a box and an `::after` that is the rotated box that forms the arrow. The tooltip has `padding: 8px 21px;`, so with `position=top` or `position=bottom` the 8px is too little so the box ends up being on-top of the content. I guess whether it actually hides text also depends on the font/line-height/other stuff, but `::before` shouldn't overlap the content regardless. I am not sure what purpose the box even - I guess you can color the arrow or something?

**Comment by ydainna** [comment]
Hi! I found the solution ... using the doc 
basically i used the padding props on <ReactTooltip /> it works for sure. but i think it would be good if it was fixed without the need to add the padding props

**Comment by danielbarion** [comment]
I'll keep both issues opened, if someone can do a PR for that, I'll be very thankful, thanks!

**Comment by danielbarion** [comment]
Please, take a look at https://react-tooltip.com/docs/examples/basic-examples

And let me know your thoughts, thanks!
