### ISSUE TITLE
Hiding on page blur

### ISSUE THREAD

**Issue by LennartSpitzner** [ReactTooltip/react-tooltip#828]
When links have tooltips, if you ctrl-click them to open in a new tab, the original tab will end up with a "stuck" tooltip, i.e. it the mouseLeave doesn't trigger despite the mouse having moved in the newly-opened tab.

My naive idea would be to add a window blur-event-listener in `listenForTooltipExit` but maybe it should be statically installed listener. Or something else. Haven't tested at all.

Any hints about sensible implementations? I can prepare a PR.

**Comment by danielbarion** [comment]
My only concern is about performance if we have a lot of tooltips on the same page, a lot of listeners will probably be added for each tooltip, but this is an already known problem from V4.

Please, do a PR for that, and thanks for reporting, I'll check the V5 implementation and see if this occurs in V5.

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
