### ISSUE TITLE
v5 beta error

### ISSUE THREAD

**Issue by ziyue5** [ReactTooltip/react-tooltip#829]
Hi, I upgrade my react-tooltip version to V5.0.0-beta.0 so that I could use classNameArrow to customize my arrow. However, here is a compile error when I run 'npm start'.

> ERROR in ./node_modules/react-tooltip/dist/react-tooltip.esm.js 2656:5-10
export 'useId' (imported as 'useId') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

**Comment by danielbarion** [comment]
Hi @ziyue5,

Thank you so much for the test and give the feedback!

Can you share your import and use of ReactTooltip, please?

Have you taken a look at https://react-tooltip.com/docs/getting-started?

Please take a look on those examples:

React
https://codesandbox.io/s/still-monad-yfi4fn?file=/package.json:259-290

React TS
https://codesandbox.io/s/affectionate-wozniak-4kotc9?file=/src/App.tsx

Both are using `V5.0.0-beta.0`, but `V5.0.0-beta.1` fixes the type error in TS projects, unfortunately, right now SandBox doesn't have `V5.0.0-beta.1` yet as this one was release few mins ago.

I'll update the examples later

**Comment by danielbarion** [comment]
Hey @ziyue5, I just realized, which version of React are you using?

https://react-tooltip.com/docs/upgrade-guide/changelog-v4-v5#improvements

`useId` os only available on React >= v18

**Comment by ziyue5** [comment]
> Hey @ziyue5, I just realized, which version of React are you using?
> 
> https://react-tooltip.com/docs/upgrade-guide/changelog-v4-v5#improvements
> 
> `useId` os only available on React >= v18

Oh! My react version is v17. Thank you for your reminder. I downgraded back to v4 and it ran pretty well.
