### ISSUE TITLE
Trigger react-tooltip when text is getting overflown

### ISSUE THREAD

**Issue by satyaki1** [ReactTooltip/react-tooltip#830]
Hi,
I am using react-tooltip over text. Presently, the tooltip is visible always irrespective of whether the text is getting overflown and an ellipsis is visible on the element. I want to show the react-tooltip only when the text is getting overflown. 
Is there any way we can achieve this using react-tooltip?

**Comment by danielbarion** [comment]
Hi,

Can you share the version of react-tooltip are you using, please?

**Comment by danielbarion** [comment]
This version has no support with React 18, if you are using React 18, please upgrade to the next one, also, the community did some contributions until the latest V4.x.x version, please pick one.

Also if you can, please test V5: https://github.com/ReactTooltip/react-tooltip/pull/820

It's in progress but can already be tested, and as faster as I receive feedback, I can improve and release a ready-for-production V5.

Thanks!

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
