### ISSUE TITLE
tooltip not hiding issue

### ISSUE THREAD

**Issue by konstantin-shatalov** [ReactTooltip/react-tooltip#831]
It seems there are still issues regarding the tooltip not closing in version 4.5.1.
I see that issue #769 was closed however the issue is still occurring.

Checkout the this code sandbox: https://codesandbox.io/s/zealous-sanderson-8l96ko?file=/src/App.js
In the image attached you can see that two tooltips remain open after the cursor has left.

The issue isn't always easily reproduce but I have found that in implementations where multiple tooltips are stacked vertically
if you move the cursor up and down overtop of them, then exit the build in simulated browser to the left the tooltips remain

![2022-12-02_15-35-40](https://user-images.githubusercontent.com/53061844/205381313-f4e17268-462b-4b0b-a69a-3f6903532410.png)

**Comment by danielbarion** [comment]
Hi @konstantin-shatalov!

Thank you for the report,

Please check the V5 beta and let me know your thoughts.

https://github.com/ReactTooltip/react-tooltip/pull/820

**Comment by zeghmouri** [comment]
Hi there,
Check my code below, I hope this turnaround can help you :)
```javascript
const [tooltip, showTooltip] = useState(true);
 <ShareIcon 
         data-tip="Link copied successfully" 
         data-event="click"
         onMouseLeave={() => {
           showTooltip(false);
           setTimeout(() => showTooltip(true), 50);
         }}
  />
  {tooltip && 
      <ReactTooltip 
            place="right" 
            afterShow={() => { navigator.clipboard.writeText(URL);}}
       />
  }
```
As you see I am using conditional rendering to show the tooltip.

**Comment by danielbarion** [comment]
Hi @konstantin-shatalov,

@zeghmouri showed you an example of V4,

here is your example using V5: https://codesandbox.io/s/nice-bogdan-vhji0c?file=/src/App.js

**Comment by zeghmouri** [comment]
I still did not migrate to V5 but I will do  it soon
Thank you so much @danielbarion for all your efforts.

**Comment by konstantin-shatalov** [comment]
Hi @danielbarion 

I tried creating couple of codesandboxes with v5, and was not able to replicate the issue so far. Will have to keep an eye, since this is hard to replicate.

**Comment by danielbarion** [comment]
ok @konstantin-shatalov, I'll keep this issue opened until v5 gets a stable release for production or until someone does a fix for v4.

thanks!

**Comment by danielbarion** [comment]
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!
