### ISSUE TITLE
[BUG] When using `delayShow`, hovering away doesn't keep the tooltip from opening

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#835]
**Describe the bug**
In v4, when using the `delayShow` prop, if the user hovers away from the anchor element before the delay from `delayShow`, the tooltip never appears. In v5, hovering the element will alway make the tooltip appear, even after hovering away.

**Version of Package**
v5.0.0

**To Reproduce**
- Set `delayShow` to a reasonable amount (`2000` should be good enough).
- Briefly hover over the anchor element, and hover away from it.
- The tooltip will still appear after the 2 seconds.

> This is easily seen in the docs page https://react-tooltip.com/docs/examples/delay

**Expected behavior**
When hovering on the anchor element for a period shorther than `delayShow`, the tooltip should never appear.

**Additional context**
Looking into the [source code](https://github.com/ReactTooltip/react-tooltip/blob/54a9b56cf11df33ccc372e497f466c3e0abd2f7c/src/components/Tooltip/Tooltip.tsx#L84-L92), this seems to have been an intentional design decision. IMHO, the behavior in v4 is ideal, so I'd just change that whole block to this:

```ts
if (tooltipShowDelayTimerRef.current) {
  clearTimeout(tooltipShowDelayTimerRef.current)
}
```

**Comment by danielbarion** [comment]
Hi @gabrieljablonski, for this feature (`delayShow`), I tried to replicate the v4 option and I tried to think in the use cases, but the final solution for `delayShow` was the only one that I was not 100% sure about if this was the best decision (everything else looks good to be, can not be the best but I'm totally open to suggestions).

Go ahead and do the change, let's do a release with this update and if someone feels that one needs to be different, the person will create a issue here and we can take a look 😄
