### ISSUE TITLE
[BUG] Types not available on the npm package

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#839]
**Describe the bug**
Types such as `PlacesType`, `VariantType`, ..., not available on the package available via npm, so no autocomplete :(

**Version of Package**
v5.0.0

**Expected behavior**
Custom types should be bundled in the `react-tooltip.d.ts` file.

**Comment by danielbarion** [comment]
Hey!

I really need help with this one, that is the first time I'm building a typescript package for NPM, if you have any suggestions or know how to improve this one, please let me know!
