### ISSUE TITLE
[BUG] Clipping when parent container has `position: relative` and `overflow: hidden`

### ISSUE THREAD

**Issue by gabrieljablonski** [ReactTooltip/react-tooltip#840]
**Describe the bug**
When using the component inside a container with `position: relative` and `overflow: hidden`, the tooltip is clipped.

**Version of Package**
v5.0.0

**To Reproduce**
- Create a container with `position: relative` and `overflow: hidden`.
- Create an element inside it to be used as the anchor.
- Create a `<Tooltip />` inside it.
- The tooltip will be clipped.

**Screenshots**
![image](https://user-images.githubusercontent.com/21102974/206360372-bfeb0c0f-202e-4200-b6ad-fb94071f7dc7.png)

**Additional context**
This is due to the tooltip using `position: absolute`. The obvious workaround is removing the `position: relative` from the parent, but that's not always viable.

**Comment by bhavinzwt** [comment]
I am still getting this same issue after adding positionStrategy="fixed".

This is the code.

`<Tooltip
                        anchorId={`ticket`}
                        content={`Content`}
                        place="top"
                        variant="light"
                        className="bg-white !py-0.5 !px-1.5 !text-xs font-medium z-10"
                        positionStrategy="fixed"
                      />`
                      
                      
Issue of screenshot: 
![image](https://github.com/ReactTooltip/react-tooltip/assets/58025684/710d27a4-65a8-45d8-bbf0-31cf542732f9)

**Comment by gabrieljablonski** [comment]
@bhavinzwt try moving the tooltip somewhere else on the DOM, if possible after your other components. If that's doesn't work, try using z-index.

If that doesn't work either, please open a new issue with more information, and hopefully a reproducible example.

**Comment by dev-johnny-gh** [comment]
The tooltip element should be rendered on the root of the document, like the body, using createPortal. Otherwise, it will cause many edge cases.
