### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smultar** [ReactTooltip/react-tooltip#842]
**Describe the bug**
Unsure what the root of the cause is, but for some reason the tooltips are showing, regardless of hover states.

**Version of Package**
v^5.0.0

**To Reproduce**
Make the tooltip a component, and then have that component wrap a child object.

**Expected behavior**
Expected the tooltip to be generated by the component with its children objects.

**Screenshots**
Visual of the bug itself.
![image](https://user-images.githubusercontent.com/6223536/206451213-6441e629-1266-4184-9f32-5f994f0b16a8.png)
Component this is being used in.
![image](https://user-images.githubusercontent.com/6223536/206451247-fa51ccca-8397-4ec1-bcff-6ab100bc4366.png)
Where the component is being used.
![image](https://user-images.githubusercontent.com/6223536/206451392-186e196d-b976-4f37-820a-2283c24a06e2.png)

**Additional context**
I don't know if it helps, that the parent components are positioned, relative.

**Comment by danielbarion** [comment]
Hi @smultar, I'll need to take a deep look and reproduce the problem, but can you try use the `enabled` differently, please?

Instead, use a variable to render or not the tooltip in V5, can you try the controlled state, please? 

https://react-tooltip.com/docs/examples/state#controlled-tooltip-state

the `isOpen` prop: https://react-tooltip.com/docs/options

**Comment by loicnico96** [comment]
Make sure you have ```import "react-tooltip/dist/react-tooltip.css"```

**Comment by smultar** [comment]
Well, that solved it. I didn't realize the CSS was separate now in the latest update.
