### ISSUE TITLE
[FEAT REQ] Dynamically setting style

### ISSUE THREAD

**Issue by ryanong** [ReactTooltip/react-tooltip#843]
**Is your feature request related to a problem? Please describe.**
In v4 of react tooltip we were able to set the bg of the tooltip dynamically, in v5 we would have to create a classname for every permutation of color we desire to set the background.

**Describe the solution you'd like**
As an alternative to setting className I'd love to be able to set style

**Comment by danielbarion** [comment]
Hi @ryanong, sounds great to me and it makes sense!

I'll add this one, thanks for the suggestion!
