### ISSUE TITLE
One tooltip, many anchors

### ISSUE THREAD

**Issue by jamieshepherd** [ReactTooltip/react-tooltip#847]
One of the big advantages of `react-tooltip` <= v4 was you could have a single tooltip somewhere in the root of your application and just scatter the `data-tip` attribute around your application and it would "just work". It looks like having a specific `anchorId` -> `id` relationship in v5 enforces a 1:1 relationship. Unless undocumented, can we support or provide non-verbose ways to achieve this? Thanks.

**Comment by jamieshepherd** [comment]
Yeah, I could definitely figure out how to do it - but it's so verbose compared to V4. #845 looks like a step in the right direction - even still it looks dramatically more verbose than its predecessor.

**Comment by danielbarion** [comment]
Yes, I agree, but the problem with V4 being less verbose, many people related performance issues while using v4, so, one of the main focuses of V5 was to improve the performance with less processing (do not spend resources if we can save this resource).

**Comment by gabrieljablonski** [comment]
> Yeah, I could definitely figure out how to do it - but it's so verbose compared to V4. #845 looks like a step in the right direction - even still it looks dramatically more verbose than its predecessor.

Having to use providers and refs will definitely make it a bit more verbose, but as Daniel mentioned, this will make things run much more reliably and with better performance. 

In the future we can definitely look into a provider/ref-less approach, but I personally don't know of many viable alternatives that are not too hard to implement, and that will perform just as good or better of what we're soon will be doing with refs.

**Comment by gabrieljablonski** [comment]
@jamieshepherd 

I believe [this example](https://github.com/ReactTooltip/react-tooltip/blob/tooltip-provider/src/App.tsx#L6-L20) should help reduce the worries about verbosity.
The only relevant thing not shown below is that the component must be inside the provider.

```tsx
function WithProviderMinimal() {
  return (
    <section style={{ marginTop: '100px' }}>
      <p>
        <TooltipWrapper place="bottom" content="Shared Global Tooltip">
          <button>Minimal 1</button>
        </TooltipWrapper>
        <TooltipWrapper place="right" content="Shared Global Tooltip">
          <button>Minimal 2</button>
        </TooltipWrapper>
      </p>
      <Tooltip />
    </section>
  )
}
```

Just missing some more testing, this should be live soon.

**Comment by danielbarion** [comment]
https://react-tooltip.com/docs/examples/multiple-anchors

**Comment by jamieshepherd** [comment]
Hi @gabrieljablonski @danielbarion - Thanks for updating the issue and providing examples - this looks much easier to use. Thanks again!
