### ISSUE TITLE
Cannot find matching version for react-tooltip when npm installing

### ISSUE THREAD

**Issue by treyorr** [ReactTooltip/react-tooltip#850]
When trying to download versions of react-tooltip. 
When trying specific versions, receive this error "No matching version found for react-tooltip"

When installing @latest, I see version 0.0.3 is installed. 

Is this an NPM issue or something you guys should be aware of?

**Comment by danielbarion** [comment]
Hi @treyorr, any update on that?

**Comment by treyorr** [comment]
Hi, sorry, the issue was completely unrelated so you can close this. Thank
you
