### ISSUE TITLE
import interfaces from library

### ISSUE THREAD

**Issue by Slonevskyi08** [ReactTooltip/react-tooltip#854]
Hello! Thanks for developing the library!

I have a question about how I can import interfaces from a library. In my project, I use TS and want to create a component to which I can partially transfer props that I will use in the tooltip, which is a child of this component. So how I can import the interfaces from the library? Thank you!

**Comment by MylesWardell** [comment]
Bump on this. I also would like the prop interface similar to the v4 implementation 👍 . I think it should be as simple as exporting `ITooltipWrapper` from the `react-tooltip.d.ts` file

**Comment by danielbarion** [comment]
Can you guys please let me know if this answer the question for now?
Thanks!

**Comment by Slonevskyi08** [comment]
Yeah, thanks Daniel!

**Comment by danielbarion** [comment]
thanks to @gabrieljablonski 😃
