### ISSUE TITLE
[FEAT REQ] Option to remove the arrow on the tooltip

### ISSUE THREAD

**Issue by charlesmooredev** [ReactTooltip/react-tooltip#856]
I was curious if you could add an option to remove the tooltip arrow all together - I'm using custom CSS that is has some issues due to the arrow. I have the classNameArrow set to transparent, but the way I have the class for the actual tooltip itself seems to have interferences from the arrow. Here is an attached screenshot showing what I mean, thanks!

![image](https://user-images.githubusercontent.com/37604197/207744172-ba3ae2f0-b547-41bb-9f8f-ee2fc34201a2.png)

**Comment by danielbarion** [comment]
Hi,

We will take a look to add a new prop to disable the tooltip arrow, but for now, before we release this feature, can you try please add a display none to it?

```
.hideArrow {
  display: none;
}
```
