### ISSUE TITLE
Is there a way to not wrap with another element when using "TooltipWrapper"?

### ISSUE THREAD

**Issue by michalvadak** [ReactTooltip/react-tooltip#858]
When using `TooltipWrapper` it gets dificult to style the original component because it gets wrapped with another `span` element. Is there a way to make it without the `span` wrapper and still use the "Multiple anchors" feature?

**Comment by gabrieljablonski** [comment]
Unfortunately, when trying to implement it without a wrapping element, the tooltip only worked properly with regular html elements (`span`, `div`, ...), but stopped working when using react components.

If you have any suggestions that would make styling easier, we'd like to hear it.

Until then, you'll have to go through the extra steps to style the anchor components.
