### ISSUE TITLE
How can I force text to be displayed in 1 line?

### ISSUE THREAD

**Issue by Simoneth** [ReactTooltip/react-tooltip#870]
Hi,
Thanks for this wonderful plugin! 

How can I force text to be displayed in 1 line?  My use case:

```
<div className="heart" data-tip="Save it!" id="album0"}>
<ReactTooltip />
```

I tried with  `<ReactTooltip multiline={false} />` ...I tried also to change` data-tip` in my `div` with `data-tip-content` and `data-tooltip-content`, but nothing works, the tip is shown in 2 rows: Save / it!

**Comment by gabrieljablonski** [comment]
What version of the `react-tooltip` package are you using?

**Comment by Simoneth** [comment]
> What version of the `react-tooltip` package are you using?

Here we go:
```
"react": "17.0.2",
"next": "12.0.7",
"react-tooltip": "^4.2.21"
```

**Comment by gabrieljablonski** [comment]
Can you try updating to the latest version (v5.3.0)? [The docs](https://react-tooltip.com/docs/getting-started) have all the info you need to do it.

**Comment by gabrieljablonski** [comment]
Actually I've just seen you're working with React 17, which is not supported by `react-tooltip` v5.

In case you can't upgrade to React 18, you should stick to v4.

Did you follow [the examples](https://reacttooltip.github.io/react-tooltip/) in the v4 docs? The sample code you provided seems to be missing the `data-for` prop on the anchor element, and `id` on the tooltip element. It should look something like this:

```tsx
<div 
  className="heart"
  data-tip="Save it!"
  data-for="heart-tooltip"
  id="album0"} 
/>
<ReactTooltip id="heart-tooltip" />
```

**Comment by Simoneth** [comment]
> Actually I've just seen you're working with React 17, which is not supported by `react-tooltip` v5.
> 
> In case you can't upgrade to React 18, you should stick to v4.
> 
> Did you follow [the examples](https://reacttooltip.github.io/react-tooltip/) in the v4 docs? The sample code you provided seems to be missing the `data-for` prop on the anchor element, and `id` on the tooltip element. It should look something like this:
> 
> ```tsx
> <div 
>   id="album0"
>   className="heart"
>   data-for="heart-tooltip"
>   data-tip="Save it!"
> />
> <ReactTooltip id="heart-tooltip" />
> ```

Thanks for reply,
This doesn't help me, but I found the issue, it's related to this CSS style on hover `transform: scale(1.2);`.
Apart to remove that style, is it possible a workaround?

P.S.
How can I use ReactTooltip in a list if I have to use an ID?

**Comment by danielbarion** [comment]
Hi @Simoneth, v4 is deprecated and not supported anymore because the codebase is totally different and obsolete, please upgrade to V5 as soon as possible.

**Comment by Simoneth** [comment]
> Hi @Simoneth, v4 is deprecated and not supported anymore because the codebase is totally different and obsolete, please upgrade to V5 as soon as possible.

Sorry but is it compatible with `React v17.0.2`?

**Comment by danielbarion** [comment]
Hi, no, only React >= v18
