### ISSUE TITLE
[BUG] ReactTooltip - class="__react_component_tooltip" - border-radius: undefinedpx;

### ISSUE THREAD

**Issue by jeremycourtaban** [ReactTooltip/react-tooltip#871]
**Describe the bug**
ReactTooltip component (class="__react_component_tooltip") has border-radius: undefinedpx set in the DOM on page load before the first display.
Note: it doesn't affect the use of the library.

**Version of Package**
v4.5.1

**To Reproduce**
Go to the [v4 demo](https://reacttooltip.github.io/react-tooltip/).
Search for `<div id="main" class="__react_component_tooltip">` in the browser dev tool DOM inspector.
Check the corresponding CSS and how the initial border-radius: undefinedpx prop change when the tooltip is displayed.
Note: when the tooltip is hidden again, the border-radius value stay valid.

**Expected behavior**
A valid CSS border-radius pixel value on page load.

**Screenshots**
Before first tooltip display on page load:
![react_tooltip_v4_border_radius_undefined_1](https://user-images.githubusercontent.com/52508006/208820846-700e4e2b-ef7b-459c-ba22-0628deb3a88a.png)
After first tooltip display:
![react_tooltip_v4_border_radius_undefined_2](https://user-images.githubusercontent.com/52508006/208820898-9c80b7ac-fb7d-42f4-a458-78af2b86a811.png)

**Desktop**
 - OS: [Ubuntu 20.04.5 LTS]
 - Browser: [Chrome / Firefox]
 - Version: [107.0.5304.110 / 108.0]

**Comment by danielbarion** [comment]
Hi @jeremycourtaban, thank you so much for the report, but v4 or less is deprecated, and no longer possible to do a fix because the codebase was written from scratch to v5.

Can you test V5 and let me now if the problem still happen, please?

**Comment by jeremycourtaban** [comment]
Hi @danielbarion, v5 tested on some examples on the [Web site](https://react-tooltip.com/docs/category/examples) and [CodeSandbox](https://codesandbox.io/s/still-monad-yfi4fn?fontsize=14&hidenavigation=1&theme=dark) and all is good, the tooltip has border-radius: 3px valid value. Ticket canceled and closed.
