### ISSUE TITLE
[BUG] Tooltips as react children element don't show anything

### ISSUE THREAD

**Issue by fmilioni** [ReactTooltip/react-tooltip#872]
**Describe the bug**
The tooltip is not displayed when it is created with custom html (React children elements). The [children  example](https://react-tooltip.com/docs/examples/children) is broken too.

**Version of Package**
v5.3.0

**To Reproduce**
```jsx
<anyElement id="element-id" />

<Tooltip anchorId="element-id">
  <p>should work</p>
</Tooltip>
````

➡️ **Workaround** ⬅️

Just add `content="."` and it should works for now.

```jsx
<anyElement id="element-id" />

<Tooltip anchorId="element-id" content=".">
  <p>now work</p>
</Tooltip>
````

**Expected behavior**
Should show tooltip

**Desktop (please complete the following information if possible or delete this section):**
 - OS: Windows
 - Chrome
 - Latest

**Comment by gabrieljablonski** [comment]
Hi Felipe! 

We had noticed this issue earlier but hadn't started investigating it yet. Your workaround made it quite easy to realize what was causing the issue, so big thanks for that.

We should have a version with the fix up and running soon.

**Comment by phoenixeliot** [comment]
Yeah, I also found that it only shows the `children` if I set the `content` either as a prop or as a data attribute.
