### ISSUE TITLE
[BUG] `click` event not working with `TooltipWrapper`

### ISSUE THREAD

**Issue by invfo** [ReactTooltip/react-tooltip#878]
**Describe the bug**
When I use a `TooltipWrapper` for the tooltip anchor, `["click"]` value for `events` attribute (or `data-tooltip-events="click"`) doesn't work.

**Version of Package**
v5.3.1

**To Reproduce**
[Steps to reproduce the behavior (code sandbox)](https://codesandbox.io/s/quirky-shadow-eo58v3?file=/src/App.js)

**Expected behaviour**
There's a way to have a tooltip with several anchors that gets shown on click.

**Desktop (please complete the following information if possible or delete this section):**
 - OS: macOS 13.1
 - Browser: Brave
 - Version: 1.46.144

**Comment by gabrieljablonski** [comment]
Hi Darya.

Thanks for the report, #879 should fix this problem.

v5.3.2 will be deployed today with the fix.

**Comment by gabrieljablonski** [comment]
Already deployed. Let us know if everything works as expected now.

**Comment by invfo** [comment]
Thank you for the quick fix. It works as expected 👌
