### ISSUE TITLE
[FEAT REQ] Add className prop to TooltipWrapper component

### ISSUE THREAD

**Issue by ccasper89** [ReactTooltip/react-tooltip#882]
**Is your feature request related to a problem? Please describe.**
I have tried migrating from react-tooltip v4 to v5 to solve a problem with tooltips occasionally not closing. One of the specifics is that I need to add tooltips to table cells that have ellipsis text overflow enabled. For performance reasons a single tooltip is used for the entire table. The change of this functionality in v5 with the use of a TooltipWrapper wrapped around the table cell causes the ellipsis text overflow to be disabled. This wouldn't be a big issue if there was a way to set css to the TooltipWrapper <span>. Unfortunately I do not see a clear way to able to add styling. Style and className properties aren't included, the rendered span element is also without a defined class that could be used. 

**Describe the solution you'd like**
Adding className property to the TooltipWrapper component which sets the class of the wrapping <span> element.

**Describe alternatives you've considered**
Adding a style prop as in Tooltip component would solve the issue as well. 
Also just a hardcoded default class name to the wrappers span element would work.

**Comment by gabrieljablonski** [comment]
Thanks for the suggestion, this is definitely something that would be useful.

If you'd like, you can submit a PR with that feature. If not, we'll get around to it soon.
