### ISSUE TITLE
[BUG] Changelog is out of date with Github Releases

### ISSUE THREAD

**Issue by mitchwd** [ReactTooltip/react-tooltip#883]
**Describe the bug**
Looks like the [CHANGELOG.md](https://github.com/ReactTooltip/react-tooltip/blob/master/CHANGELOG.md) file is out of date with the Github Releases, found here: https://github.com/ReactTooltip/react-tooltip/releases
Hoping the maintainers can either update the script that automatically updates CHANGELOG.md to fill in the blank versions, or add a courtesy message to CHANGELOG.md to look at the Github Releases page instead.

**Comment by danielbarion** [comment]
Hi @mitchwd, the CHANGELOG.md is just related to v4, as v5 was built from scratch we deleted all the files from the project and created a new flow when we released v5.

But you're right, it's not clear that CHANGELOG.md is just related to v4 and GitHub releases for v5, we will add a message into CHANGELOG.md, thank you for the report!

**Comment by mitchwd** [comment]
Legend. Thanks @danielbarion!
