### ISSUE TITLE
[BUG] Package fails to import on Next 13

### ISSUE THREAD

**Issue by brunocangs** [ReactTooltip/react-tooltip#887]
**Describe the bug**
Next 13 tries to import the package as an ES Module as defined by the `type: module` field in package.json but fails, with an error as the `main` file is `.cjs`.

**Version of Package**
v5.3.3

**To Reproduce**
- Create a new NextJS app with `create-next-app`
- Install `react-tooltip`
- Setup the package and add a tooltip to the `pages/index.ts` file.

**Expected behavior**
The package's `type` and `main` should match their type

**Screenshots**
![image](https://user-images.githubusercontent.com/30100875/210382677-9c60ecf8-a9ee-4b66-84cc-c06402d8ce03.png)

**Desktop (please complete the following information if possible or delete this section):**
 - OS: MacOS 13.0.1

**Comment by danielbarion** [comment]
🤦🏻‍♂️ 

This makes sense, can you do a PR, please?

Thanks for the report!

**Comment by itsikcircle** [comment]
I've been facing the same issue, and send a PR here https://github.com/ReactTooltip/react-tooltip/pull/888

**Comment by danielbarion** [comment]
PR merged and released.

Thanks everyone!

https://github.com/ReactTooltip/react-tooltip/releases/tag/v5.3.4
