### ISSUE TITLE
CDN style link

### ISSUE THREAD

**Issue by jsdude0220** [ReactTooltip/react-tooltip#891]
I have one question.
Is there a CDN link that can use with external for style?
In some case, the `import 'react-tooltip/dist/react-tooltip.css';` does not work, so would like to know any cdn link if it's available already.
Thanks.

**Comment by jsdude0220** [comment]
Thanks for your quick response.
Btw I just realized it is not related with style importing stuff.
Here are error details. Would you pls take a look if you are available?

`ERROR in ./node_modules/react-tooltip/dist/react-tooltip.esm.min.js 562:14-15`

`export 'useId' (imported as 'n') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)`

Above is error description, just wondering what is the issue.
Please let me know if you have experience with this issue.
Thanks in advance.

**Comment by gabrieljablonski** [comment]
That probably means you're not using react 18, which is a dependency for v5. You should probably update to it if possible.

**Comment by jsdude0220** [comment]
Oh, I see, currently I am using the react v17 now and just need to keep this version for some reason.
Maybe react-tooltip v4 will be worked with react v17?

**Comment by danielbarion** [comment]
Hi @jsdude0220, yes, v4 works with react v17, but we strongly recommend upgrading to v5 because of performance and some bugs on v4 that don't exist on v5.

**Comment by jsdude0220** [comment]
Ah, I see,
I will try to update the react version.
Thanks, just close the issue.
