### ISSUE TITLE
How to update tooltip content?

### ISSUE THREAD

**Issue by stephanbogner** [ReactTooltip/react-tooltip#896]
(First of all thanks for maintaining this library!)

### Context:
I have a tooltip/popover with dynamic content (a tiny statistics panel):
![Screenshot from 2023-01-10 11-19-58](https://user-images.githubusercontent.com/7897006/211462598-bac0ddb3-5530-4ca4-81da-98153ac550b7.png)

### Code:
I am passing a component like it's mentioned in the docs: `data-tooltip-html={ReactDOMServer.renderToString(<RatingStatistics/>)}`.

### Issue:
`ReactDOMServer.renderToString` doesn't seem to get triggered when the component changes, but also if I manually update `data-tooltip-html` the tooltip content itself doesn't get updated.

### Question:
How does one change the content of `data-tooltip-html` and make it affect the displayed tooltip?

Thanks already in advance!

**Comment by stephanbogner** [comment]
I just noticed that my usecase might not be technically a tooltip anymore. I am considering that for this use case a [Headless-UI popover](https://headlessui.com/react/popover) might be the better choice ... but I am unsure so any answer would nevertheless be appreciated :)

**Comment by stephanbogner** [comment]
Hi @gabrieljablonski 

Thanks for replying and sure, **[here you go](https://codesandbox.io/s/suspicious-wiles-8s44yf?file=/src/App.js)** (or check out the code below):

(Note: I now used headless UI so I don't _need_ the problem to be solved but it might still be worth solving)

```
import React, { useState } from "react";
import { Tooltip } from 'react-tooltip';
import 'react-tooltip/dist/react-tooltip.css';
import "./styles.css";

export default function App() {
  const [randomNumber, setRandomNumber] = useState(-1);

  function handleClick() {
    setRandomNumber(Math.round(Math.random() * 10000));
  }

  return (
    <div className="App">
      <div>Random number: {randomNumber}</div>
      <button onClick={handleClick}>Change number</button>
      <h1 id="my-element" data-tooltip-html={randomNumber}>Hover me</h1>
      <Tooltip anchorId="my-element" />
    </div>
  );
}
```

In the screenshot you can see that the hover still shows `-1` which is the initial state and not the current state:
![Screenshot from 2023-01-12 10-12-08](https://user-images.githubusercontent.com/7897006/211967174-946ac3d2-9d1c-4aa6-b9be-9ec5f4bf1578.png)

**Comment by gabrieljablonski** [comment]
Thanks for taking the time.

It is clearly indeed a bug, and we'll definitely be looking into it.

**Comment by stephanbogner** [comment]
> Thanks for taking the time.
> 
> It is clearly indeed a bug, and we'll definitely be looking into it.

Thanks!
