### ISSUE TITLE
[BUG] Tooltip is displayed after an anchor element as is

### ISSUE THREAD

**Issue by altafard** [ReactTooltip/react-tooltip#897]
**Describe the bug**
Tooltip doesn't work after following all instructions from documentation.

**Version of Package**
v5.4.0

**To Reproduce**

Import react-tooltip after installation

```js
import { Tooltip } from 'react-tooltip'
```

Create anchor element

```html
<p id="my-anchor-element">Tooltip</p>
```

Create Tooltip element

```jsx
<Tooltip anchorId="my-anchor-element" content="hello world" place="top" />
```

**Expected behavior**
Tooltip content is hidden and appears above element on hover.

**Screenshots**
<img width="491" alt="image" src="https://user-images.githubusercontent.com/28362919/211677180-0a1455fc-5017-4f69-8f4f-56b327a07122.png">

**Desktop (please complete the following information if possible or delete this section):**
 - OS: macOS
 - Browser Chrome
 - Version 108.0.5359.124 (Official Build) (arm64)

**Comment by TiE23** [comment]
Same here. Amazed this was only posted an hour ago. I'm going through the chore of updating my project's tools: React 17 -> 18 and NextJS 12 -> 13. We I saw an issue with my v4 tooltip never disappearing I decided it might be work updating react-tooltip. So, just 30 minutes ago I updated to v5 and I'm this same exact issue.

**Comment by gabrieljablonski** [comment]
Are you guys doing `import 'react-tooltip/dist/react-tooltip.css'`? 

We should probably make it more clear about this.

**Comment by TiE23** [comment]
> Are you guys doing `import 'react-tooltip/dist/react-tooltip.css'`?

![that-worked](https://user-images.githubusercontent.com/2433505/211687324-a9e9beb4-ebf1-4064-8c21-6e11039fe1be.gif)

> We should probably make it more clear about this.

Indeed, I definitely assumed it was only in the case I desired to customize the styles.

**Comment by danielbarion** [comment]
> Indeed, I definitely assumed it was only in the case I desired to customize the styles.

V4 has the styles included with JS files and inserted as inline styles into tooltip elements, to override the styles this way, the community had to use `!important`.

V5 we simplified and made the styles optional, you can import the styles and use the default styles we provided, or you can create your own styles and add them into `className` related props: https://react-tooltip.com/docs/examples/styling

**Comment by altafard** [comment]
> Are you guys doing `import 'react-tooltip/dist/react-tooltip.css'`?
> 
> We should probably make it more clear about this.

Many thanks! It wasn't obvious for me to use this css explicitly. Now it works.

**Comment by gabrieljablonski** [comment]
Good to hear. We'll update the docs to make that clearer.
