### ISSUE TITLE
Box shadow for tooltip and arrow

### ISSUE THREAD

**Issue by sthadathil** [ReactTooltip/react-tooltip#900]
How can I add box-shadow for the tooltip and arrow? The tooltip not properly visible if the page background color is similar to the tooltip background color.

**Comment by danielbarion** [comment]
Hi @sthadathil, you can try https://react-tooltip.com/docs/examples/styling

**Comment by gabrieljablonski** [comment]
As mentioned, this can be achieved by referring to the examples in the docs.

If any problems arise, feel free to reopen this issue.
