### ISSUE TITLE
react-simple-maps usage?

### ISSUE THREAD

**Issue by bnbon** [ReactTooltip/react-tooltip#905]
I wonder if anyone has used this with `react-simple-maps` yet, that is how I heard of this package, but their documentation covers v4.

I tried doing the conversion of the import and changing the <ReactTooltip>Content<ReactTooltip> to <Tooltip content="Content"/> but I also think I need to add a pair of ID's for every country? I'd rather use the single instance of a tooltip and set the label to the country dynamically – do I need to use the Provider approach?

Many Thanks

**Comment by danielbarion** [comment]
Hi @bonbonio, please take a look at this section in our docs: https://react-tooltip.com/docs/examples/multiple-anchors
