### ISSUE TITLE
[BUG] Build warnings related to 'useId'.

### ISSUE THREAD

**Issue by maosin77** [ReactTooltip/react-tooltip#906]
Hi, thanks for the good work your library is doing a great job. However, I have a problem. 

**Describe the bug**
I get a warning during the build.

```
./node_modules/react-tooltip/dist/react-tooltip.esm.min.js
Attempted import error: 'useId' is not exported from 'react' (imported as 'n').
```

**Version of Package**
5.5.1

**Context**
In my project we are using react 17.x.
`useId`  which you are using was introduced in react 18.
I believe it is cause of the issue.
Is there any change to use eg. [uuid](https://www.npmjs.com/package/uuid) instead of `useId`? 

Of course, I understand the decision to use the latest react features. However, I believe that the process of migrating to the latest versions will continue for some time in existing projects. So I think that backwards compatibility will be a great value.

please see my PR: https://github.com/ReactTooltip/react-tooltip/pull/907

**Comment by gabrieljablonski** [comment]
Thanks for reporting this.

As noted by [my comment](https://github.com/ReactTooltip/react-tooltip/pull/907#issuecomment-1387366486), an unique id is not necessary for the provider to work properly. #911 addresses this.

**Comment by maosin77** [comment]
Cool! Thanks for quick fix!
