### ISSUE TITLE
[FEAT REQ]: Close tooltip using the escape key

### ISSUE THREAD

**Issue by andykimchris** [ReactTooltip/react-tooltip#908]
**Is your feature request related to a problem? Please describe.**

I can't see from the docs whether it's possible to escape a tooltip and close it. If so, I would be happy to help address this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gabrieljablonski** [comment]
Are you referring to being able to close the tooltip by pressing the escape key? If so, this feature is yet to be implemented.

Feel free to submit a PR if you'd like. I suggest for it to be disabled by default, and enabled using a prop called `closeOnEscape`.

**Comment by andykimchris** [comment]
Awesome thanks!!!
