### ISSUE TITLE
overlapping target areas

### ISSUE THREAD

**Issue by mdodge-ecgrow** [ReactTooltip/react-tooltip#914]
Using the old version, I was able to achieve this using some kinda annoying code playing with onMouseLeave and onMouseEnter.  It was kind of a pain.  Hoping there might be an easier way with the new version of this plugin.

This is what my container looks like:
![image](https://user-images.githubusercontent.com/57459547/213784667-4589903c-f783-492c-8e89-40c606d585c8.png)

So when I hover over any of the green area, it will show a tooltip, and that works fine.
![image](https://user-images.githubusercontent.com/57459547/213784956-fd95c388-b816-4cd5-9cb6-8197e3e1605c.png)

However, when I hover over the black arrow, I want to show a different tooltip.  And that is not working.  So with the old version, i had to do something like this:
```js
onMouseLeave={() => {
	Tooltip.show(pocketLabel.current);
}}
onMouseEnter={() => {
	Tooltip.hide(pocketLabel.current);
}}
```

**Comment by gabrieljablonski** [comment]
The first that comes to mind is having a `tooltipContent` state which will be passed to the tooltip `content` prop. Then you can control this state when hovering the arrow.

If for some random reason you actually need two tooltip components (which I don't believe would be the case most of the time) you can try doing absolute positioning with the arrow.

**Comment by mdodge-ecgrow** [comment]
Thanks, I was able to get it working the way i needed with state content with mouse enter and leave again.

One more thing, I feel like the default z-index should be a bit higher.  I don't have z-index set to anything special on my green containers, but it is still being hidden.  In the browser dev tools, if I set the z-index to just 1, it will show over that container.

![image](https://user-images.githubusercontent.com/57459547/213804187-a8ba1fc8-0b42-468d-bda0-1e2368be3c25.png)

**Comment by gabrieljablonski** [comment]
> Thanks, I was able to get it working the way i needed with state content with mouse enter and leave again.

Good to know.

> I feel like the default z-index should be a bit higher.

The tooltip container actually does not actually set a z-index, so it's positioning follows the regular DOM flow, which (I believe) means elements that come later (or are nested deeper) appear on top. You can probably fix this without setting the z-index, simply by putting the tooltip element higher up in the DOM:

```tsx
<MyCard />
<MyCard />
{/* comes after other elements /*}
<Tooltip />
```
or


```tsx
<MyCards>
  <MyCard />
  <MyCard />
</MyCards>
{/* nested higher /*}
<Tooltip />
```

For more complex use cases, you can set the z-index by using the `className` prop and a custom class, or directly through the `styles`.
