### ISSUE TITLE
How to make test of TooltipWrapper with @testing-library on React

### ISSUE THREAD

**Issue by finaly55** [ReactTooltip/react-tooltip#919]
Hello, I would like to know how to do tests of TooltipWrapper with @testing-library on React.
I'm test with code, but it's not working.

Version of Package : 5.5.2

My test code is :
```
test("Affichage d'un tooltip de type information", async () => {
    // when
    await render(
    <TooltipProvider>
        <Tooltip id={"informative"}>
        </Tooltip>
        <main>
            <TooltipWrapper tooltipId={'informative'} content={'textContentTooltip'}>
              <span>tooltip</span>
            </TooltipWrapper>
        </main>
    </TooltipProvider>
    );

    // then
    expect(screen.queryByText('textContentTooltip')).not.toBeInTheDocument();
    await userEvent.hover(screen.getByText('tooltip'));
    expect(screen.getByText('textContentTooltip')).toBeInTheDocument();
});
```

I feel like it can't hover over the element because it can't find "textContentTooltip". 
Do you have any other leads by chance?

Thank you in advance for your answers ! :)

**Edit (solution work for me) :**
```
test("Affichage d'un tooltip de type information", async () => {
    // when
    await render(
    <TooltipProvider>
          <Tooltip id={"informative"}>
          </Tooltip>
          <main>
              <TooltipWrapper tooltipId={'informative'} content={'textContentTooltip'}>
                <span>tooltip</span>
              </TooltipWrapper>
          </main>
      </TooltipProvider>
    );

    // then
    expect(screen.queryByText('textContentTooltip')).not.toBeInTheDocument();
    await userEvent.hover(screen.getByText('tooltip'));
    expect(await screen.findByText('textContentTooltip')).toBeInTheDocument();
});
```

**Comment by gabrieljablonski** [comment]
When using `<TooltipWrapper />`, your component **must** be inside as `<TooltipProvider />`. 

Try doing that first. If it doesn't work, we'll see what's the correct approach.

**Comment by finaly55** [comment]
Thanks for your answer, indeed it was missing <TooltipWrapper> but that was not all. I managed to get the code to work but not in the "cleanest" way.
I had to add the "click" to events Tootip like this : `events={['click', 'hover']}` and change `screen.hover` to `screen.click` in test file. Maybe is it a bug ? Do you have a solution to use `screen.hover` ?

**Comment by finaly55** [comment]
I tried several cases and only the clicks seem to work, what do you think?
![image](https://user-images.githubusercontent.com/34056080/214892978-88252654-04bb-4585-8ed1-dd6d25d27308.png)

**Comment by gabrieljablonski** [comment]
Not sure what your exact setup is, but the test below worked for me. The only change from the first sample code you posted is the provider and the use of `waitFor()`. 

Since it takes a few render cycles (not sure how many, would need to test it) for the tooltip to update the text after you hover the anchor element, you should wait a bit before checking. 100ms seems fine to me.

```tsx
import '@testing-library/jest-dom'
import * as React from 'react'
import userEvent from '@testing-library/user-event'
import { render, screen, waitFor } from '@testing-library/react'

import { Tooltip, TooltipWrapper, TooltipProvider } from '../src'

test('show tooltip on hover', async () => {
  render(
    <TooltipProvider>
      <Tooltip id="informative" />
      <main>
        <TooltipWrapper tooltipId="informative" content="textContentTooltip">
          <span>tooltip</span>
        </TooltipWrapper>
      </main>
    </TooltipProvider>,
  )
  expect(screen.queryByText('textContentTooltip')).not.toBeInTheDocument()
  await userEvent.hover(screen.getByText('tooltip'))
  await waitFor(() => expect(screen.getByText('textContentTooltip')).toBeInTheDocument(), {
    timeout: 100,
  })
})
```

**Comment by finaly55** [comment]
Thank you for your answer, it works now ! We had to wait for the tooltip to appear. 
I replaced `waitFor` by `await screen.findByText('textContentTooltip')`. 
I edited my post to include the final solution. Thanks again for your help!

**Comment by blwinters** [comment]
Oddly, I had to add `await` to the `userEvent.hover` portion to resolve the noisy warning `an update was not wrapped in act() ...`
