### ISSUE TITLE
[BUG] TS compile: "TS2456: Type alias 'Middleware' circularly references itself."

### ISSUE THREAD

**Issue by bobmazy** [ReactTooltip/react-tooltip#920]
**Describe the bug**
Error thrown when compiling react app with typescript v4.9.4 and using yarn pnp.
[Example project](https://github.com/bobmazy/react-typescript)

`.yarn/__virtual__/react-tooltip-virtual-7b0a038807/0/cache/react-tooltip-npm-5.7.0-8f25b21000-1d3ae9afc9.zip/node_modules/react-tooltip/dist/react-tooltip.d.ts:16:6 - error TS2456: Type alias 'Middleware' circularly references itself.`

**Version of Package**
v5.6.0

**To Reproduce**
1. add typescript `v4.9.4` to react app 
2. use yarn pnp
3. use react-tooltip `v5.6.0`
4. compile

or 
1. clone https://github.com/bobmazy/react-typescript
2. run `yarn`
3. run `yarn tsc`

**Expected behavior**
React App should compile without any error

**Comment by gabrieljablonski** [comment]
Thanks for reporting this. `"skipLibCheck": true` was hiding this problem when running the build.
