### ISSUE TITLE
[BUG] The tooltip remains displayed when deleting an element with WrapperTooltip

### ISSUE THREAD

**Issue by finaly55** [ReactTooltip/react-tooltip#924]
**Describe the bug**
Scenario, I have a delete button on an element, the button is enclosed by a WrapperTooltip.
I hover the button, tooltip shows.
I click the button, button goes away, tooltip remains.

**Version of Package**
v5.7.0

**To Reproduce**
```
<TooltipProvider>
    <Tooltip id={"informative"}>
    </Tooltip>
    <main>
        <TooltipWrapper tooltipId={'informative'} content={'textContentTooltip1'}>
             <btn onClick="Close()">close</btn>
        </TooltipWrapper>
        <TooltipWrapper tooltipId={'informative'} content={'textContentTooltip2'}>
             <btn onClick="Close()">close</btn>
        </TooltipWrapper>
        <TooltipWrapper tooltipId={'informative'} content={'textContentTooltip3'}>
             <btn onClick="Close()">close</btn>
         </TooltipWrapper>
    </main>
</TooltipProvider>
```

Thank you in advance for your answers ! :)

**Comment by gabrieljablonski** [comment]
Thanks for reporting, v5.7.2 has been released with a fix for this. 

It should be noted that the new code watches for the anchor element being removed from the DOM, so you should make sure the wrapper also gets removed when the button does.
