### ISSUE TITLE
[BUG] Tooltips fail to render in production build

### ISSUE THREAD

**Issue by tony-cocco** [ReactTooltip/react-tooltip#936]
**Describe the bug**
The tooltip does not render when used in production minified project. `_app-eda58d659857c8fd.js:15 Uncaught (in promise) TypeError: b is not a function` (minified name which isn't super helpful).

**Version of Package**
v5.7.0 and 5.7.4

**To Reproduce**
We use nextjs, so running `yarn build` and then `yarn start` to use the minified production build:
1. Hover item with tooltip.
2. Observe error in inspector.

**Expected behavior**
I expect the tooltip to appear as it does when running `yarn dev`.

**Desktop**
 - OS: Mac Ventura 13.1
 - Browser Chrome@latest

**Additional context**
Rolling back to 5.3.2 works as expected.

I know this might not be super helpful considering the issue only appears in a minified build. Please let me know if there's any other information that might help.

**Comment by gabrieljablonski** [comment]
I'm assuming you're running a project with Next.js 13. It appears there are some issues with the new minifier being used in version 13, so you can set `swcMinify: false` in the options to go back to the old minifier. See #933 for more info.

If it ends up being something else, feel free to reopen the issue.

**Comment by tony-cocco** [comment]
Thanks for the quick response. We are using Next13. 

🥂

**Comment by vincentwinkel** [comment]
Why is this ticket closed?
Thanks for this (temporarily) workarorund, but asking people to disable the default Nest 13 minifier in their project because of 1 dependency module is **not** a fix.

I also have this problem in production:
v5.10: the whole website is unusable
v5.11: the error occurs when hoverr the element

**Comment by gabrieljablonski** [comment]
@vincentwinkel Upgrade to `next@13.3.0` or later. See #1001, or [the troubleshooting page](https://react-tooltip.com/docs/troubleshooting#nextjs-typeerror-f-is-not-a-function) for more details.
