### ISSUE TITLE
[BUG] Tooltip displays under contents when automatically flipped inside a td element

### ISSUE THREAD

**Issue by tom-ads** [ReactTooltip/react-tooltip#937]
**Describe the bug**
When using the `Tooltip` component inside a `td` element it displays the Tooltip under the contents of the other table cells it is covering (see code example or screenshots for demo). It seems to only occur when the Tooltip is flipped due to the available space.

In our setup, we have a `div` surrounding the table with `overflow-x: auto` and `overflow-y: hidden`, this is causing the first row element to flip the Tooltip to below the progress indicator as shown in the screenshots.

**Version of Package**
v5.7.4

**To Reproduce**
Have put an example of the rough setup we have for tables, with the issue occurring:
[Code example](https://codesandbox.io/s/gallant-galois-7wt9vg?file=/src/App.js)

**Expected behavior**
Tooltip should display above the contents it covers when flipped

**Screenshots**
Tooltip displays above contents, not flipped due to available space:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/86882192/216817699-3d5d9058-8e2a-4194-a7c1-3e4f73d7a7cf.png">

Tooltip displays under contents, has been flipped due to no available space at the top:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/86882192/216817708-bf304f59-beb8-4d22-8e2d-7eab704ebe36.png">

**Desktop:**
 - OS: macOS Monterey@12.3 
 - Browser: Chrome@latest

**Additional context**
Have seen mentioned before about the use of `ReactToolTip.rebuild()`, but this seems to have been removed with the switch to floating-ui?

**Comment by tom-ads** [comment]
Can be closed. Seems tailwind transform was causing the issue on the `tr` element, weird.

**Comment by rossicler-hostalky** [comment]
Can you share what did you do? I'm having a very similar problem, and I'm also using tailwind
