### ISSUE TITLE
Typos in the docs

### ISSUE THREAD

**Issue by sabinbaniya** [ReactTooltip/react-tooltip#941]
**Describe the bug**
Hey, I have seen some typos in the [v4->v5 changelog](https://react-tooltip.com/docs/upgrade-guide/changelog-v4-v5) page. Can I go ahead and fix those typos?

**Version of Package**
Related to docs

**To Reproduce**
NA

**Expected behavior**
There are some typos in the docs

**Comment by gabrieljablonski** [comment]
For sure, you can submit a PR.

**Comment by sabinbaniya** [comment]
Oh okay.
