### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'current') on `preact` project

### ISSUE THREAD

**Issue by jduffy3** [ReactTooltip/react-tooltip#944]
**Describe the bug**
Getting the following in console

```
react-tooltip.esm.min.js:10 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'current')
    at P (react-tooltip.esm.min.js:10:4693)
    at B (react-tooltip.esm.min.js:10:8460)
    at Jt.jsx (react-tooltip.esm.min.js:10:9183)
    at k.un [as constructor] (react-tooltip.esm.min.js:15:10887)
    at k.H [as render] (preact.module.js:1:8671)
    at I (preact.module.js:1:6362)
    at O (preact.module.js:1:3538)
    at I (preact.module.js:1:6630)
    at O (preact.module.js:1:3538)
    at D (preact.module.js:1:7848)
```

**Version of Package**
v5.7.5

**To Reproduce**
Checkout branch `upgrade/react-tooltip` from https://github.com/defmethodinc/just-not-sorry

* run `npm install`
* run `npm start:chrome`
* login to gmail account
* compose new email with a "trigger word" e.g. just
* Observe error in console

**Expected behavior**
Tooltip should render, eventually (once finish setting other props on updated version; 
At least no errors should display in console.

**Screenshots**

**Desktop (please complete the following information if possible or delete this section):**
 - Chrome
 - Frameworks [Preact 10.12.1 ]

**Comment by gabrieljablonski** [comment]
Currently, this library has `react` and `react-dom` as peer dependencies. If you edit `node_modules/react-tooltip/package.json` and change it so the build uses the unminified versions:

```json
{
  ...
  "main": "dist/react-tooltip.cjs.js",
  "module": "dist/react-tooltip.esm.js",
  ...
}
```

You'll see that the error is due to the `ReactCurrentOwner` object being undefined.

I'm not sure what can be done to make it so `react-tooltip` is seamlessly compatible with `preact`. Any suggestions are appreciated.

**Comment by gabrieljablonski** [comment]
Tested and this seems to work now with `npm i react-tooltip@latest`. There was an issue though when importing `react-tooltip/dist/react-tooltip.css`.

This project bundler doesn't seem to like `:root` declarations, so I got it to work by copying the contents of the CSS file manually into the project CSS file, but there's probably a proper way of doing this.
