### ISSUE TITLE
[BUG] Tooltip placement is wrong with CSS `zoom`

### ISSUE THREAD

**Issue by goztrk** [ReactTooltip/react-tooltip#945]
**Describe the bug**
If the CSS `zoom` value of target element is different than `1`, the Tooltip shows in a wrong position. This happens even if `positionStrategy` is set to `fixed`.

**Version of Package**
v5.7.5

**To Reproduce**
Add `style={{zoom: 1.5}}` to the target element.

**Expected behavior**
It should show on the top. but offset is way wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/1487670/219367598-11fb6caf-77fe-4d50-8d0f-4af6e1db9d3c.png)

**Desktop (please complete the following information if possible or delete this section):**
 - OS: Windows 11
 - Browser Chrome
 - Version 109
 - Frameworks Remix.run / React 18

**Additional context**
None

**Comment by gabrieljablonski** [comment]
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#:~:text=Non%2Dstandard%3A%20This%20feature%20is%20non%2Dstandard%20and%20is%20not%20on%20a%20standards%20track.%20Do%20not%20use%20it%20on%20production%20sites%20facing%20the%20Web%3A%20it%20will%20not%20work%20for%20every%20user.%20There%20may%20also%20be%20large%20incompatibilities%20between%20implementations%20and%20the%20behavior%20may%20change%20in%20the%20future.), `zoom` is non-standard and you should avoid using it.

Try doing `transform: scale(1.5)` instead. If you run into any problems using it then, feel free to open another issue.
