### ISSUE TITLE
How to prevent scrollbar from appearing when using the tooltip?

### ISSUE THREAD

**Issue by alina-kala4ik** [ReactTooltip/react-tooltip#953]
**Describe the bug**
scrollbar appears when tooltip appears 

**Version of Package**
v5.7.5

**To Reproduce**
https://codesandbox.io/s/eager-water-6tvblc?file=/src/index.js
(I use state with additional logic on my app, for not showing tooltip on mobile)

**Expected behavior**
scrollbar shouldn't appears 

**Screenshots**
https://user-images.githubusercontent.com/52624465/220127295-9bdb45e4-1129-465a-8cca-9354f2d87422.mov

**Comment by gabrieljablonski** [comment]
By default, the tooltip is placed on the DOM with absolute positioning.

You can use `<Tooltip positionStrategy="fixed" />` to change that and prevent the scrollbar from appearing.

**Comment by wds4** [comment]
I am getting the same bug, and it is not fixed with `<Tooltip positionStrategy="fixed" />`. However, `<Tooltip clickable />` seems to get rid of the scrollbar for some strange reason.

**Comment by danielbarion** [comment]
Which version are you using @wds4?

**Comment by wds4** [comment]
react-tooltip 5.8.2, [this project](https://github.com/wds4/pretty-good)
