### ISSUE TITLE
[BUG] `useLayoutEffect` warning in dev mode

### ISSUE THREAD

**Issue by joulev** [ReactTooltip/react-tooltip#954]
**Describe the bug**
When using `react-tooltip`, there is a `useLayoutEffect` warning, although the tooltip itself works fine.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be 
encoded into the server renderer's output format. This will lead to a mismatch 
between the initial, non-hydrated UI and the intended UI. To avoid this, 
useLayoutEffect should only be used in components that render exclusively on the 
client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

    at he (/Users/joulev/dev/www/debug/node_modules/.pnpm/react-
tooltip@5.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/react-tooltip/dist/react-
tooltip.cjs.min.js:15:3103)
    at exports.Tooltip (/Users/joulev/dev/www/debug/node_modules/.pnpm/react-
tooltip@5.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/react-tooltip/dist/react-
tooltip.cjs.min.js:15:7943)
    ...
```

**Version of Package**
v5.8.1

**To Reproduce**
* Clone https://github.com/joulev/debug/tree/react-tooltips-uselayouteffect-warning
* `pnpm install`
* `pnpm dev`
* Above warning is shown.

**Expected behavior**
No warning should be shown.

**Screenshots**
N/A

**Additional context**
The repro repo uses Next.js 13, but this one is different from #933 as I have disabled SWC minification.

**Comment by gabrieljablonski** [comment]
According to [this link](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a) a few big react projects currently use the following workaround:

```ts
import { useLayoutEffect, useEffect } from 'react';
const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect;
export default useIsomorphicLayoutEffect;
```

Apparently there aren't any undesired side effects, so we're probably going to include this soon.

Thanks for reporting it.

**Comment by gabrieljablonski** [comment]
`react-tooltip@5.8.2` has been released with this fix.

**Comment by k2xl** [comment]
I'm seeing this on `    "react-tooltip": "^5.21.6",`

**Comment by gabrieljablonski** [comment]
@k2xl please open a new issue and provide more information about your environment (framework you're using and the version, etc). If possible, a reproducible sample would help a lot.
