### ISSUE TITLE
How to change the tooltip opacity?

### ISSUE THREAD

**Issue by zzeynall** [ReactTooltip/react-tooltip#955]
Hi! I just need to access to show class to add opacity: 1, after tooltip is shown. Thank you

**Comment by danielbarion** [comment]
Hi @zzeynall,

If you check here: https://react-tooltip.com/docs/examples/styling#explanation

You will see the show class like:
```
.show {
  visibility: visible;
  opacity: var(--rt-opacity);
}
```

So, you just need to update the opacity variable:

```
--rt-opacity: 1;
```

Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
