### ISSUE TITLE
How to rebuild in v5

### ISSUE THREAD

**Issue by alexb148** [ReactTooltip/react-tooltip#963]
In v4, my understanding of best practice was to create one `<ReactTooltip />` element at the top level of the app, and then in any component that required a tooltip you would run `ReactTooltip.rebuild()` to ensure that any content injected after the main `<ReactTooltip />` was rendered would work as expected.

In v5 I see that there is no rebuild method, but any elements with "data-tooltip-content" that are added after the`<ReactTooltip />` element was rendered do not work.

What is the new best practice here? Are we now expected to add a unique `<ReactTooltip />` element in every single component that needs tooltips, instead of simply rebuilding one single `<ReactTooltip />` element?

Unfortunately I cannot see anything about this in the docs or the upgrade guide. I would suggest this information is added in if possible.

Thanks for any help!

**Comment by gabrieljablonski** [comment]
What version are you using? Since v5.8.2, any changes made to the DOM after the tooltip is rendered should be detected automatically.

If that isn't happening, it is either a bug, or an use case we're unfamiliar with. If you're using the lastest version, we'd appreciate a sample project reproducing the problem so we can investigate.

**Comment by alexb148** [comment]
Ah I see, it looks like it was my own fault - I missed that you now have to manually import the css yourself 🤦‍♂️

It might be worth adding that information about `rebuild()` no longer being required to the upgrade guide, so no one else has to ask the question here.

Thank you for your help!

**Comment by gabrieljablonski** [comment]
> It might be worth adding that information about `rebuild()` no longer being required to the upgrade guide

For sure, we've already had it happen a few times. We'll definitely be doing that soon. Thanks for reporting.
