### ISSUE TITLE
[FEAT REQ]: Indicate the actual place where tooltip is rendered in some way

### ISSUE THREAD

**Issue by binomialstew** [ReactTooltip/react-tooltip#969]
**Is your feature request related to a problem? Please describe.**
I have a similar need to [this feature request](https://github.com/ReactTooltip/react-tooltip/issues/868), but I don't think there have been any changes made related to it before it was closed.

I can use the `place` prop that is being set on the tooltip in my styling to "track" the place that is being set, but the `place` I am setting is not always respected. For example, if I have set `place="top"`, but there is no room at the top of the anchor element, the tooltip is positioned at the bottom of the anchor element. I can see why this is done, but the styling I have depending on `place` has no knowledge of the placement being different than the prop value, so the styling used is different than what it should be for the actual placement when it differs from the set value.

From the place prop description: `Position relative to the anchor element where the tooltip will be rendered (if possible).` The "if possible" part is what makes it impossible to use the same value for `place` in my implementation of this tooltip.

**Describe the solution you'd like**
Can we expose the `place` context or apply classNames to the tooltip to reflect the actual placement used?

**Additional context**
I am adding a border to the arrow shape and need to use the placement to determine what sides of the border should be set to `none` in order to only show a border around the outer edge.

**Comment by gabrieljablonski** [comment]
This is definitely extremely useful, and quite easy to implement.

Try out the beta release for #970 with `yarn add react-tooltip@5.9.1-beta.0` and let us know if it works as expected.

**Comment by gabrieljablonski** [comment]
Forgot to mention, since exposing the actual placement with a callback or something else would be a lot more cumbersome, I went with the following classes:

```
.react-tooltip__place-top 
.react-tooltip__place-right
.react-tooltip__place-bottom
.react-tooltip__place-left
```

**Comment by binomialstew** [comment]
Beautiful! It works great for me.

**Comment by gabrieljablonski** [comment]
I'll leave this open until we merge the PR.
