### ISSUE TITLE
v5.9.1 fails to compile

### ISSUE THREAD

**Issue by andrewdowis** [ReactTooltip/react-tooltip#971]
**Describe the bug**
When I npm install with legacy peer dependencies, I am no longer able to compile my app. Nothing changed in my webpack and this error started roughly a day ago, about the time of the latest release. When I switch back to 5.8.3, I compile successfully.

```
ERROR in ../node_modules/react-tooltip/dist/react-tooltip.esm.min.js 1:4496
Module parse failed: Unexpected token (1:4496)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Version of Package**
v5.9.1

**To Reproduce**
`package.json` adds `react-tooltip` via `"react-tooltip": "^5.7.4",`
npm install --legacy-peer-deps
npm run start

**Expected behavior**
React app compiles successfully

 - Webpack 4
 - React 17
 - Node 16.19.0
 - npm 8.19.3

**Additional context**
changing my import to `"react-tooltip": "5.7.4",` or even `5.8.3` allows the app to compile, so I can only surmise it's an issue with the latest release

**Comment by danielbarion** [comment]
Hi @andrewdowis,

I'm not sure if you checked the release notes, but on `5.9.0` we did a new release using Esbuild instead of Rollup to bundle the package, this reduced the size of the package to ~5kb

https://github.com/ReactTooltip/react-tooltip/releases/tag/v5.9.0

Can you please provide one example with the error, so we can check and fix it? (a github repository with the problem happening will be great!)

**Comment by andrewdowis** [comment]
i cannot provide a repo but if the issue is "known" as part of the 5.9.0 update then i'll close it

**Comment by danielbarion** [comment]
just to clarify, before we release `5.9.0`, we tested with a new project of Create React App, and with the docs, all examples still working as expected, so, if you or someone is facing a problem with the build after `5.9.0`, please let us now with a reproducible example, so we can debug and fix the issue.

thanks!
