### ISSUE TITLE
[FEAT REQ] Keep dependencies external in build results

### ISSUE THREAD

**Issue by GerkinDev** [ReactTooltip/react-tooltip#974]
**Is your feature request related to a problem? Please describe.**
Building an app that imports @floating-ui results in the transitive dependency being included twice. Moreover, stats in bundlephobia does not reflect the size of this module itself, but concatenated with all its deps.

**Describe the solution you'd like**
Mark dependencies as external in rollup config, so that the app bundling handles resolution itself

**Describe alternatives you've considered**
Use the source directly

**Comment by gabrieljablonski** [comment]
This is definitely something we weren't considering. We'll see how to approach this since we've recently migrated to esbuild as the default bundler. Thanks for the suggestion.

**Comment by GerkinDev** [comment]
Thank you :) a quick lookaround & inspection of the dist esm build reveals that dependencies weight about half the size of the minified file. I know it isn't much, since the minified is pretty light, but duplicate transitive dependencies add up quite quickly

Cheers ! :beers:

**Comment by gabrieljablonski** [comment]
> about half the size of the minified file

> I know it isn't much

50% is actually quite a lot IMO, it would only start being less relevant if we were talking about <<<1KB.

I'm not super experienced with optimal practices when it comes to bundling, so I'm not sure how best to approach this. @danielbarion will probably have some more interesting perspectives.

If you also have any further suggestions regarding this, we'd be glad to hear.

**Comment by GerkinDev** [comment]
Having contributed to multiple front-end libs myself, I took the habit to keep almost every deps of those libs as peer dependencies (except very small ones) and configure the bundler to preserve import/require statements, EXCEPT for builds that aims to be distributed via CDN.
When user build their app, via a bundler, it makes its best to link to the same module if version ranges matches.

I never used esbuild though, but if you're OK with it, I can do the tests, PR with config & a couple of stats. I love bundlers, and I would be pleased to give you a hand
