### ISSUE TITLE
[BUG] when you select clickable and events: click you cant click  element inside, without closing tooltip

### ISSUE THREAD

**Issue by hernandiazz9** [ReactTooltip/react-tooltip#978]
**Describe the bug**

**Version of Package**
vX.X.X

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Smartphone (please complete the following information if possible or delete this section):**
 - Frameworks [e.g. React 18, Next.js 13]

**Additional context**

**Comment by gabrieljablonski** [comment]
As you can see on the example in the [docs page](https://react-tooltip.com/docs/getting-started#clickable-tooltip), it should work fine. Can you provide a sample project showing the problem?

**Comment by hernandiazz9** [comment]
Yes, when you open when hover, you can click great, the problem is when you set the `events={[click]}` and prop clickable, when you click a button the popover close.

**Comment by hernandiazz9** [comment]
try this up.
                
                   `<a id="not-clickable">◕‿‿◕</a>
			<Tooltip events={['click']} anchorSelect="#not-clickable">
				<button>You cant click me :(</button>
			</Tooltip>
			<a id="clickable">◕‿‿◕</a>
			<Tooltip
				events={['click']}
				anchorSelect="#clickable"
				clickable
			>
				<button>You can click me!</button>
			</Tooltip>`

**Comment by gabrieljablonski** [comment]
You're right, I misread your description. Try out the beta release for #979 with the version `react-tooltip@5.10.0-beta.1` and let us know if it works as expected.

By the way, this PR also deprecates `events` and introduces a new prop `openOnClick`, which I recommend you use instead.

**Comment by hernandiazz9** [comment]
Yeah!! it's working! with this PR `react-tooltip@5.10.0-beta.1`

**Comment by gabrieljablonski** [comment]
Good to know. The issue will be closed when the PR gets merged. Thanks for reporting.
