### ISSUE TITLE
[BUG] react-tooltip.esm.min.js - Unexpected token

### ISSUE THREAD

**Issue by Nagrom33** [ReactTooltip/react-tooltip#981]
**Describe the bug**
When I want to run `npm run start` I'm getting following error.
If you need more information about other packages I'm using let me know.

**Version of Package**
v5.10.0

**Error message**
```Failed to compile.

./node_modules/react-tooltip/dist/react-tooltip.esm.min.js 321:11
Module parse failed: Unexpected token (321:11)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         }
|       });
>     a = x ?? a, c = v ?? c, p = {
|       ...p,
|       [w]: {

```

**Comment by Nagrom33** [comment]
I found an solution but I don't know if this is the good way. 
How I fix it:

change browserslist as @adlerer suggests:
```
"browserslist": [
  ">0.2%",
  "not dead",
  "not op_mini all"
],
```
(make sure you don't have special config for development in browserslist)

clear npm cache:

`pm cache clean --force`
reinstall things like @Gel suggests:

`rm -rf node_modules && rm -f package-lock.json && npm i`

Founded from: https://stackoverflow.com/questions/63423384/you-may-need-an-additional-loader-to-handle-the-result-of-these-loaders

**Comment by danielbarion** [comment]
Hi, can you try this beta version and let me know if it worked, please?

```
react-tooltip@5.10.1-beta.4
```

**Comment by danielbarion** [comment]
@Nagrom33 can you try this beta version and let me know if it worked, please?

```
react-tooltip@5.10.1-beta-8
```

**Comment by jeyang** [comment]
@danielbarion - getting this issue as well.

`react-tooltip@5.10.1-beta-8` doesn't fix it, I get the same error.
same for `react-tooltip@5.10.0` and `react-tooltip@5.9.0`

`react-tooltip@5.8.1` works.

**Comment by gabrieljablonski** [comment]
Sorry for the delay.

Are you able to let us know if using `react-tooltip@5.10.2-beta.4` **without** the manual browserlist fix works?

**Comment by jbarriospd** [comment]
thanks, it works!

**Comment by danielbarion** [comment]
Or the latest release that we did on react-tooltip

**Comment by gabrieljablonski** [comment]
Closing this since no response from OP. Feel free to reopen if it still doesn't work after testing with the latest version (`npm i react-tooltip@latest`).
