### ISSUE TITLE
Error when calling node.contains because it is not a method

### ISSUE THREAD

**Issue by rolandpoulter** [ReactTooltip/react-tooltip#985]
https://github.com/ReactTooltip/react-tooltip/blob/master/src/components/Tooltip/Tooltip.tsx#L377

When `node` is undefined or when `contains` is not a method this causes an uncaught exception.

Suggest changing the expression to:

```
node?.contains && node.contains(activeAnchor)
```

This will prevent errors from happening

**Comment by gabrieljablonski** [comment]
Fixed on `react-tooltip@5.10.1`. Thanks for reporting.
