### ISSUE TITLE
Beta version: Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by binomialstew** [ReactTooltip/react-tooltip#986]
**Describe the bug**
I'm seeing `Cannot read properties of undefined (reading 'current')` in beta version `5.10.1-beta-9`. I do not see this error in `5.10.1-beta.4`.

Looks like `ReactCurrentOwner.current` is undefined.

**Comment by danielbarion** [comment]
hi @binomialstew can you check our PRs and the comments (beta releases) and let me know if the latest beta releases work for you?

https://github.com/ReactTooltip/react-tooltip/pull/984 `yarn add react-tooltip@5.10.1-beta-10` - rollup

https://github.com/ReactTooltip/react-tooltip/pull/982 `yarn add react-tooltip@5.10.1-beta-9` - esbuild

**Comment by gabrieljablonski** [comment]
Same as said on #987.

Please test out `react-tooltip@5.10.2-beta.4` and let us know about this specific issue.

**Comment by binomialstew** [comment]
I don't see this issue any longer, but I do see this when trying to access the tooltip in a `next.js@13.2.4` production build:
```js
floating-ui.core.browser.min.mjs:1 Uncaught (in promise) TypeError: f is not a function
    at d (floating-ui.core.browser.min.mjs:1:860)
```

**Comment by gabrieljablonski** [comment]
Can you try `next.js@13.2.5-canary.22`? Apparently this version fixed a similar issue for us, so I'd appreciate if you could test it.

**Comment by gabrieljablonski** [comment]
> For some reason, `noArrow` is not applying the class necessary to hide the arrow in your `5.10.2-beta.x`

Just a slight oversight when refactoring some class names. Already commited the fix to an open PR which will be merged and released soon. Thanks for reporting.

Regarding this issue we are considering it as a bug on Next.js, since the update fixes it.

`react-tooltip@5.10.5` has been released, and it addresses the other issues that were closed today.
