### ISSUE TITLE
ESLint warning: Package subpath './dist/react-tooltip' is not defined

### ISSUE THREAD

**Issue by binomialstew** [ReactTooltip/react-tooltip#987]
**Describe the bug**
When importing:
```
import 'react-tooltip/dist/react-tooltip.css';
```

I see the following error through eslint:
```
Resolve error: Package subpath './dist/react-tooltip' is not defined by "exports" in /Users/[username]/Sites/[projectname]/node_modules/react-tooltip/package.json
```

I'm not sure exactly where './dist/react-tooltip' is being requested (not in my codebase), but adding this to the react-tooltip package `exports` resolves it:
```
"exports": {
    ...
    "./dist/react-tooltip": "./dist/react-tooltip.cjs.js"
  },
```

**Version of Package**
v5.10.1-beta.4

**Comment by danielbarion** [comment]
hi @binomialstew can you check our PRs and the comments (beta releases) and let me know if the latest beta releases work for you?

https://github.com/ReactTooltip/react-tooltip/pull/984 `yarn add react-tooltip@5.10.1-beta-10` - rollup

https://github.com/ReactTooltip/react-tooltip/pull/982 `yarn add react-tooltip@5.10.1-beta-9` - esbuild

**Comment by binomialstew** [comment]
I still see this issue in both `react-tooltip@5.10.1-beta-10` and `react-tooltip@5.10.1-beta-9`. Both also contain [this more serious issue for us](https://github.com/ReactTooltip/react-tooltip/issues/972).

I think this should be added to package exports: `"./dist/react-tooltip": "./dist/react-tooltip.cjs.js"`

**Comment by gabrieljablonski** [comment]
Hey @binomialstew

Following up on this issue, could you please test `react-tooltip@5.10.2-beta.4` and let us know if this specific problem still happens? We'll be addressing each issue that's still open to see if the rollup build still has stuff we have to fix.

**Comment by binomialstew** [comment]
@gabrieljablonski, I do still see this warning using `react-tooltip@5.10.2-beta.4`.

**Comment by gabrieljablonski** [comment]
Whenever you get the time, if you could provide a sample repository where we could reproduce this warning, it would help us immensely.

**Comment by binomialstew** [comment]
@gabrieljablonski, [here you go](https://github.com/binomialstew/react-tooltip-import-warning). If you clone it and run `npm ci`, you should see the warning in your editor upon opening `src/app.js`. You should also see the warning in your terminal when running `npm run start`.
<img width="694" alt="Screen Shot 2023-04-06 at 12 42 13 PM" src="https://user-images.githubusercontent.com/6164653/230443354-222883c8-a269-4a22-bec4-57bea018c78c.png">

**Comment by gabrieljablonski** [comment]
Thanks for taking the time. Can confirm that editing the `package.json` manually with 

```
"exports": {
    ...
    "./dist/react-tooltip": "./dist/react-tooltip.cjs.js"
  },
```

fixes it, though I'm not sure if `cjs` or `esm` would be the most appropriate mode for this entry.

This issue (#987) along with #1000 and #1002 can definitely all be fixed together. Whenever @danielbarion has the time, he'll look into fixing all of these properly.

Thanks for reporting!

**Comment by binomialstew** [comment]
> Can confirm that editing the `package.json` manually

Confirmed. Both `cjs` or `esm` works to kill the warning.

Thanks for taking care of it!

**Comment by danielbarion** [comment]
Hi, can you test this beta release and let us know, please?

Beta version:
```
yarn add react-tooltip@5.10.6-beta.1005.1
```
or
```
npm i react-tooltip@5.10.6-beta.1005.1
```

PS: I didn't add the entry that @gabrieljablonski mentioned in this beta release, but if this one doesn't work, I can add and release a new beta version.

**Comment by binomialstew** [comment]
@danielbarion , `react-tooltip@5.10.6-beta.1005.1` doesn't correct the issue

**Comment by danielbarion** [comment]
thanks for confirming @binomialstew 

And this one?

Beta version:
```
yarn add react-tooltip@5.10.6-beta.1005.2
```
or
```
npm i react-tooltip@5.10.6-beta.1005.2
```

Commit: https://github.com/ReactTooltip/react-tooltip/pull/1005/commits/74327ca1a757d40daf5427b0d8322001269273f2

**Comment by binomialstew** [comment]
Is this fixed in [v5.10.6](https://github.com/ReactTooltip/react-tooltip/releases/tag/v5.10.6).

**Comment by gabrieljablonski** [comment]
> Is this fixed in [v5.10.6](https://github.com/ReactTooltip/react-tooltip/releases/tag/v5.10.6).

Not yet, we're reviewing #1005 and `react-tooltip@5.10.7` should be released by tomorrow with the fix.

**Comment by gabrieljablonski** [comment]
Please test the official release `react-tooltip@5.11.1` and let us know.

**Comment by binomialstew** [comment]
> Please test the official release react-tooltip@5.11.1 and let us know.

Works for me. Thank you!

**Comment by binomialstew** [comment]
This doesn't correct the issue and I see the exports don't have the ones that are needed. In `v5.11.1`:
```
 "exports": {
    ".": "./dist/react-tooltip.cjs.js",
    "./dist/*.js": "./dist/*.js",
    "./dist/react-tooltip.css": "./dist/react-tooltip.css",
    "./package.json": "./package.json"
  },
```

In the one I confirmed is fixed:
```
"exports": {
    ".": {
      "types": "./dist/react-tooltip.d.ts",
      "require": "./dist/react-tooltip.min.cjs",
       "import": "./dist/react-tooltip.min.mjs",
       "default": "./dist/react-tooltip.min.cjs"
     },
     "./dist/react-tooltip": "./dist/react-tooltip.min.cjs",
     "./dist/react-tooltip.css": "./dist/react-tooltip.min.css",
     "./dist/react-tooltip.d.ts": "./dist/react-tooltip.d.ts",
     "./package.json": "./package.json"
  },
  ```
