### ISSUE TITLE
Position is off if the content of the tootip's height changes

### ISSUE THREAD

**Issue by akraines** [ReactTooltip/react-tooltip#993]
### Discussed in https://github.com/ReactTooltip/react-tooltip/discussions/991

<div type='discussions-op-text'>

<sup>Originally posted by **akraines** March 28, 2023</sup>
It seems that position is off if the content of the tooltip's height changes. Is there a way to indicate to the tooltip to recalculate its position based on the height of the dynamic content of the tooltip?
I'm trying to work out why tooltips are being positioned way out of place on first render of the cell in my app. On the second render it positions itself correctly. I have considered 2 possibilities:
1. The tooltip is associated with a row that is being rendered as part of a virtual list.
2. The height of the tooltip changes as part of its first render [it first says loading and then displays the content.] As a test I gave the tooltip a fixed height and it seemed to fix the issue.</div>

I looked into it further and made a repro: https://stackblitz.com/edit/react-ts-ay7kkp?file=App.tsx,index.tsx

**Comment by gabrieljablonski** [comment]
Check [this example](https://stackblitz.com/edit/react-ts-rtgmca?file=package.json,App.tsx) and try it out with the beta release `react-tooltip@5.10.2-beta.3` and let me know if it works.

**Comment by akraines** [comment]
It worked like a charm. Thank you. See my comment to the pull request for a suggestion about how to circumvent the need to use a forwarded ref.
